######################################################################
# Automatically generated by qmake (1.08a) Sat Dec 18 16:03:25 2004
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pimdelegate.h pimmodel.h pimeditor.h pimviewer.h pimsignalhub.h
SOURCES += main.cpp pimdelegate.cpp pimmodel.cpp pimeditor.cpp pimviewer.cpp pimsignalhub.cpp
RESOURCES += pimelim.qrc
