TEMPLATE    = app
CONFIG+= qt warn_on release
TARGET      = receiver
SOURCES    += main.cpp
unix:LIBS  += -lqui
win32:LIBS += $(QTDIR)/lib/qui.lib
INTERFACES	= mainform.ui 
IMAGEFILE	= images.cpp
PROJECTNAME	= receiver
LANGUAGE	= C++
INCLUDEPATH	+= $(QTDIR)/tools/designer/uilib
