TEMPLATE    = app
CONFIG+= qt warn_on release
TARGET      = receiver
SOURCES    += main.cpp
unix:LIBS  += -lqresource
win32:LIBS += $(QTDIR)/lib/qresource.lib
INTERFACES	= mainform.ui 
IMAGEFILE	= images.cpp
PROJECTNAME	= receiver
LANGUAGE	= C++
{SOURCES+=images.cpp}
