#############################################################################
# $Id: //depot/qt/main/examples/desktop/GNUmakefile#3 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = desktop

include $(QTDIR)/GNUmakefile.inc
