#############################################################################
# $Id: //depot/qt/main/tools/msg2qm/GNUmakefile#1 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = msg2qm

include $(QTDIR)/GNUmakefile.inc
