#!/bin/sh

[ -f $HOME/.qt-license ] || exit $((96+16));

. $HOME/.qt-license >/dev/null 2>&1
[ -z "$LicenseKey" ] && exit $((96+17))
echo $LicenseKey | grep "....-....-...." >/dev/null 2>&1 || exit $((96+17))

keyTest=`echo $LicenseKey | cut -b1`
case $keyTest in
  *) ###
     ;;
  *) exit $((96+18)) ;;
esac

exit 0