#############################################################################
# $Id: //depot/qt/main/extensions/network/src/GNUmakefile#2 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = qnetwork

include $(QTDIR)/GNUmakefile.inc
