/****************************************************************************
**
** Copyright (C) 1992-$THISYEAR$ $TROLLTECH$. All rights reserved.
**
** This file is part of the $MODULE$ of the Qt Toolkit.
**
** $TROLLTECH_DUAL_LICENSE$
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
****************************************************************************/

/* This file is autogenerated from the Unicode 4.0.1 database. Do not edit */

//
//  W A R N I N G
//  -------------
//
// This file is not part of the Qt API.  It exists for the convenience
// of internal files.  This header file may change from version to version
// without notice, or even be removed.
//
// We mean it.
//

// See http://www.unicode.org/reports/tr24/tr24-5.html

enum Script {
    Common,
    Greek,
    Cyrillic,
    Armenian,
    Hebrew,
    Arabic,
    Syriac,
    Thaana,
    Devanagari,
    Bengali,
    Gurmukhi,
    Gujarati,
    Oriya,
    Tamil,
    Telugu,
    Kannada,
    Malayalam,
    Sinhala,
    Thai,
    Lao,
    Tibetan,
    Myanmar,
    Georgian,
    Hangul,
    Ogham,
    Runic,
    Khmer,
    Inherited,
    ScriptCount = Inherited,
    Latin = Common,
    Ethiopic = Common,
    Cherokee = Common,
    CanadianAboriginal = Common,
    Mongolian = Common,
    Hiragana = Common,
    Katakana = Common,
    Bopomofo = Common,
    Han = Common,
    Yi = Common,
    OldItalic = Common,
    Gothic = Common,
    Deseret = Common,
    Tagalog = Common,
    Hanunoo = Common,
    Buhid = Common,
    Tagbanwa = Common,
    Limbu = Common,
    TaiLe = Common,
    LinearB = Common,
    Ugaritic = Common,
    Shavian = Common,
    Osmanya = Common,
    Cypriot = Common,
    Braille = Common,
    Buginese = Common,
    Coptic = Common,
    NewTaiLue = Common,
    Glagolitic = Common,
    Tifinagh = Common,
    SylotiNagri = Common,
    OldPersian = Common,
    Kharoshthi = Common,
    Balinese = Common,
    Cuneiform = Common,
    Phoenician = Common,
    PhagsPa = Common,
    Nko = Common
};

enum { ScriptSentinel = 32 };

