/****************************************************************************
** $Id: //depot/qt/main/src/kernel/qkeycode.h#19 $
**
** Definition of keyboard codes
**
** Created : 931030
**
** Copyright (C) 1992-1998 Troll Tech AS.  All rights reserved.
**
** This file is part of Troll Tech's internal development tree for Qt.
**
** This header text will be replaced by an appropriate text by the
** mkdist script which generates external distributions.
**
** If you are using the Qt Professional Edition or the Qt Free Edition,
** please notify Troll Tech at <info@troll.no> if you see this text.
**
** To Troll Tech developers: This header was generated by the script
** fixcopyright-int. It has the same number of text lines as the free
** and professional editions to avoid line number inconsistency.
**
*****************************************************************************/

#ifndef QKEYCODE_H
#define QKEYCODE_H

#ifndef QT_H
#include "qglobal.h"
#include "qnamespace.h"
#endif // QT_H

// all key codes are now in the Qt namespace class

#endif // QKEYCODE_H
