/****************************************************************************
** $Id: //depot/qt/main/src/kernel/qobjectdict.h#6 $
**
** Definition of QObjectDictionary
**
** Created : 940807
**
** Copyright (C) 1992-1998 Troll Tech AS.  All rights reserved.
**
** This file is part of Troll Tech's internal development tree for Qt.
**
** This header text will be replaced by an appropriate text by the
** mkdist script which generates external distributions.
**
** If you are using the Qt Professional Edition or the Qt Free Edition,
** please notify Troll Tech at <info@troll.no> if you see this text.
**
** To Troll Tech developers: This header was generated by the script
** fixcopyright-int. It has the same number of text lines as the free
** and professional editions to avoid line number inconsistency.
**
*****************************************************************************/

#ifndef QOBJECTDICT_H
#define QOBJECTDICT_H

#ifndef QT_H
#include "qmetaobject.h"
#include "qdict.h"
#endif // QT_H


//
// The object dictionary is a collection of QMetaObjects
//


#if defined(QT_DLL)
template class Q_EXPORT QDict<QMetaObject>;
#endif


class Q_EXPORT QObjectDictionary : public QDict<QMetaObject>
{
public:
    QObjectDictionary(int size=17,bool cs=TRUE,bool ck=TRUE) :
	QDict<QMetaObject>(size,cs,ck) {}
    QObjectDictionary( const QObjectDictionary &dict ) : QDict<QMetaObject>(dict) {}
   ~QObjectDictionary() { clear(); }
    QObjectDictionary &operator=(const QObjectDictionary &dict)
	{ return (QObjectDictionary&)QDict<QMetaObject>::operator=(dict); }
};

// Global object dictionary defined in qmetaobject.cpp

extern Q_EXPORT QObjectDictionary *objectDict;


#endif // QOBJECTDICT_H
