##############################################################
# Automatically generated by qmake Mon May 21 18:38:12 2001
##############################################################

TEMPLATE += app
TARGET += qurloperator
CONFIG -= moc

# Input
SOURCES += main.cpp
INTERFACES	= mainview.ui 
DBFILE	= qurloperator.db
PROJECTNAME	= Qurloperator
LANGUAGE	= C++
