##############################################################
# Automatically generated by qmake (1.01a) Fri Nov 16 15:47:13 2001
##############################################################

TEMPLATE = app
DEPENDPATH += /home/jasmin/qt/tests/qdoc3/

# Input
HEADERS += atom.h\
           bookgenerator.h\
           codechunk.h\
           codemarker.h\
           codeparser.h\
           config.h\
           cppcodemarker.h\
           cppcodeparser.h\
           doc.h\
           generator.h\
           htmlgenerator.h\
           jscodemarker.h\
           location.h\
           loutgenerator.h\
           mangenerator.h\
           messages.h\
           node.h\
           plaincodemarker.h\
           quickcodeparser.h\
           quoter.h\
           separator.h\
           sgmlgenerator.h\
           stringset.h\
           tokenizer.h\
           tree.h\
           webgenerator.h
SOURCES += bookgenerator.cpp\
           codechunk.cpp\
           codemarker.cpp\
           config.cpp\
           cppcodemarker.cpp\
           cppcodeparser.cpp\
           doc.cpp\
           generator.cpp\
           htmlgenerator.cpp\
           jscodemarker.cpp\
           location.cpp\
           main.cpp\
           mangenerator.cpp\
           messages.cpp\
           node.cpp\
           plaincodemarker.cpp\
           quickcodeparser.cpp\
           quoter.cpp\
           separator.cpp\
           stringset.cpp\
           tokenizer.cpp\
           tree.cpp\
           webgenerator.cpp
