data 'LPic' (5000) {
    $"0002 0011 0003 0001 0000 0000 0002 0000"
    $"0008 0003 0000 0001 0004 0000 0004 0005"
    $"0000 000E 0006 0001 0005 0007 0000 0007"
    $"0008 0000 0047 0009 0000 0034 000A 0001"
    $"0035 000B 0001 0020 000C 0000 0011 000D"
    $"0000 005B 0004 0000 0033 000F 0001 000C"
    $"0010 0000 000B 000E 0000"
};


data 'TEXT' (5002, "English") {
"Qt COMMERCIAL LICENSE AGREEMENT\n"
"FOR PROFESSIONAL AND ENTERPRISE EDITIONS\n"
"\n"
"Agreement version 2.8 \n"
"\n"
"IMPORTANT-READ CAREFULLY: \n"
"1. This Trolltech End-User License Agreement ('Agreement') is a legal\n"
"agreement between you (either an individual or a legal entity)\n"
"('Licensee') and Trolltech AS ('Trolltech') for the Trolltech software\n"
"product(s) accompanying this Agreement, which include(s) computer\n"
"software and may include 'online' or electronic documentation,\n"
"associated media, and printed materials, including the source code,\n"
"example programs and the documentation ('Licensed Software').\n"
"\n"
"2. The Licensed Software is protected by copyright laws and\n"
"international copyright treaties, as well as other intellectual\n"
"property laws and treaties. The Licensed Software is licensed, not\n"
"sold.\n"
"\n"
"3. Some of the files in the Licensed Software have been grouped into\n"
"Modules. These files contain specific notices defining the Module of\n"
"which they are a part. The Modules licensed to Licensee are specified\n"
"in the license certificate ('License Certificate') accompanying the\n"
"Licensed Software. The terms of the License Certificate are considered\n"
"part of the Agreement. In the event of inconsistency or conflict\n"
"between the language of this Agreement and the License Certificate,\n"
"the provisions of this Agreement shall govern.\n"
"\n"
"4. By installing, copying, or otherwise using the Licensed Software,\n"
"Licensee agrees to be bound by the terms of this Agreement. If\n"
"Licensee does not agree to the terms of this Agreement, Licensee may\n"
"not install, copy, or otherwise use the Licensed Software. Licensee\n"
"may, however, return it to Licensee's place of purchase within 14 days\n"
"of purchase for a full refund. In addition, by installing, copying, or\n"
"otherwise using any updates or other components of the Licensed\n"
"Software that Licensee receives separately as part of the Licensed\n"
"Software ('Updates'), Licensee agrees to be bound by any additional\n"
"license terms that accompany such Updates. If Licensee does not agree\n"
"to the additional license terms that accompany such Updates, Licensee\n"
"may not install, copy, or otherwise use such Updates.\n"
"\n"
"5. Upon Licensee's acceptance of the terms and conditions of this\n"
"Agreement, Trolltech grants Licensee the right to use the Licensed\n"
"Software in the manner provided below.\n"
"\n"
"6. Trolltech grants to Licensee as an individual a personal,\n"
"nonexclusive, non-transferable, perpetual license to make and use\n"
"copies of the Licensed Software for the sole purposes of designing,\n"
"developing, and testing Licensee's software product(s)\n"
"('Applications'). Licensee may install copies of the Licensed Software\n"
"on an unlimited number of computers provided that Licensee is the only\n"
"individual using the Licensed Software. If Licensee is an entity,\n"
"Trolltech grants Licensee the right to designate one, and only one,\n"
"individual within Licensee's organization who shall have the sole\n"
"right to use the Licensed Software in the manner provided\n"
"above. Licensee may at any time, but not more frequently that once\n"
"every six (6) months, designate another individual to replace the\n"
"current designated user by notifying Trolltech, so long as there is no\n"
"more than one designated user at any given time.\n"
"\n"
"7. Verification: Trolltech may, upon its reasonable request and at its\n"
"expense, audit Licensee with respect to the use of the Licensed\n"
"Software. Any such audit shall be conducted during regular business\n"
"hours at Licensee's facilities and shall not unreasonably interfere\n"
"with Licensee's business activities. Trolltech will not remove, copy,\n"
"or redistribute any electronic material during the course of an\n"
"audit. The Licensee does not implicitly grant Trolltech any form of\n"
"license agreement. If an audit reveals that Licensee is using the\n"
"Licensed Software in a way that is in material violation of the terms\n"
"of the Agreement, then Licensee shall pay Trolltech's reasonable costs\n"
"of conducting the audit. In the case of a material violation, Licensee\n"
"agrees to pay Trolltech any amounts owing that are attributable to the\n"
"unauthorized use. In the alternative, Trolltech reserves the right, at\n"
"Trolltech's sole option, to terminate the licenses for the Licensed\n"
"Software.\n"
"\n"
"8. The Licensed Software may provide links to third party libraries or\n"
"code (collectively 'Third Party Libraries') to implement various\n"
"functions. Third Party Libraries do not comprise part of the Licensed\n"
"Software. In some cases, access to Third Party Libraries may be\n"
"included along with the Licensed Software delivery as a convenience\n"
"for development and testing only. Such source code and libraries as\n"
"are or may be listed in the '.../src/3rdparty' source tree delivered\n"
"with the Licensed Software, as may be amended from time to time, do\n"
"not comprise the Licensed Software. Licensee acknowledges (1) that\n"
"some Third Party Libraries may require additional licensing of\n"
"copyright and patents from the owners of such, and (2) that\n"
"distribution of any of the Licensed Software referencing any portion\n"
"of a Third Party Library may require appropriate licensing from such\n"
"third parties.\n"
"\n"
"GENERAL TERMS THAT APPLY TO APPLICATIONS AND REDISTRIBUTABLES\n"
"9. Trolltech grants Licensee a nonexclusive, royalty-free right to\n"
"reproduce and distribute the object code form of certain portions of\n"
"the Licensed Software ('Redistributables'), as specified in Appendix\n"
"1, for execution on any operating system of a type listed in the\n"
"License Certificate ('Platforms'). Copies of Redistributables may only\n"
"be distributed with and for the sole purpose of executing Applications\n"
"permitted under this Agreement that Licensee has created using the\n"
"Licensed Software. Under no circumstances may any copies of\n"
"Redistributables be distributed separately.\n"
"\n"
"10. The license granted in this Agreement for Licensee to create\n"
"Applications and distribute them and the Redistributables (if any) to\n"
"Licensee's customers is subject to all of the following conditions:\n"
"(i) all copies of the Applications Licensee creates must bear a valid\n"
"copyright notice, either Licensee's own or the copyright notice that\n"
"appears on the Licensed Software; (ii) Licensee may not remove or\n"
"alter any copyright, trademark or other proprietary rights notice\n"
"contained in any portion of the Licensed Software; (iii)\n"
"Redistributables, if any, shall be licensed to Licensee's customer 'as\n"
"is'; (iv) Licensee will indemnify and hold Trolltech, its related\n"
"companies and its suppliers, harmless from and against any claims or\n"
"liabilities arising out of the use, reproduction or distribution of\n"
"Applications; (v) Applications must be developed using a licensed,\n"
"registered copy of the Licensed Software; (vi) Applications must add\n"
"primary and substantial functionality to the Licensed Software; (vii)\n"
"Applications may not pass on functionality which in any way makes it\n"
"possible for others to create software with the Licensed Software;\n"
"(viii) Applications may not compete with the Licensed Software; (ix)\n"
"Licensee may not use Trolltech's or any of its suppliers' names,\n"
"logos, or trademarks to market Application(s), except to state that\n"
"Application was developed using the Licensed Software.\n"
"\n"
"NOTE: Qt Free Edition is licensed under the terms of the GPL and not\n"
"under this Agreement. If Licensee has, at any time, developed all (or\n"
"any portions of) the Application(s) using Trolltech's publicly\n"
"licensed Qt Free Edition, Licensee must comply with Trolltech's\n"
"requirements (see\n"
"http://www.trolltech.com/developer/download/qt-x11.html) and license\n"
"such Application(s) (or any portions derived there from) under the\n"
"terms of the Free Software Foundation's GNU General Public License\n"
"version 2 (the 'GPL') a copy of which is located at\n"
"http://www.gnu.org/copyleft/gpl.html#SEC1 (i.e., any Product(s) and/or\n"
"parts, components, portions thereof developed using GPL licensed\n"
"software, including Qt Free Edition, must be licensed under the terms\n"
"of the GPL, and the GPL-based source code must be made available upon\n"
"request).\n"
"\n"
"WARRANTY DISCLAIMER\n"
"11. The Licensed Software is licensed to Licensee 'as is'. To the\n"
"maximum extent permitted by applicable law, Trolltech on behalf of\n"
"itself and its suppliers, disclaims all warranties and conditions,\n"
"either express or implied, including, but not limited to, implied\n"
"warranties of merchantability, fitness for a particular purpose, title\n"
"and non-infringement with regard to the Licensed Software.\n"
"\n"
"LIMITATION OF LIABILITY\n"
"12. If, Trolltech's warranty disclaimer notwithstanding, Trolltech is\n"
"held liable to Licensee, whether in contract, tort or any other legal\n"
"theory, based on the Licensed Software, Trolltech's entire liability\n"
"to Licensee and Licensee's exclusive remedy shall be, at Trolltech's\n"
"option, either (A) return of the price Licensee paid for the Licensed\n"
"Software, or (B) repair or replacement of the Licensed Software,\n"
"provided Licensee returns to Trolltech all copies of the Licensed\n"
"Software as originally delivered to Licensee. Trolltech shall not\n"
"under any circumstances be liable to Licensee based on failure of the\n"
"Licensed Software if the failure resulted from accident, abuse or\n"
"misapplication, nor shall Trolltech under any circumstances be liable\n"
"for special damages, punitive or exemplary damages, damages for loss\n"
"of profits or interruption of business or for loss or corruption of\n"
"data. Any award of damages from Trolltech to Licensee shall not exceed\n"
"the total amount Licensee has paid to Trolltech in connection with\n"
"this Agreement.\n"
"\n"
"SUPPORT AND UPDATES\n"
"13. Licensee will be eligible to receive email based software\n"
"developer support and access to Updates ('Support and Updates') to the\n"
"Licensed Software for a period not to exceed one year from the date of\n"
"initial delivery ('Initial Term'), in accordance with Trolltech's then\n"
"current policies and procedures, if any. Such policies and procedures\n"
"may be changed from time to time. Following the Initial Term,\n"
"Trolltech will no longer make the Licensed Software available to\n"
"Licensee unless Licensee purchases additional Support and Updates\n"
"according to section 15 below.\n"
"\n"
"GENERAL PROVISIONS\n"
"\n"
"14. Licensee Name: Trolltech may include Licensee's company name in a\n"
"publicly available list of Trolltech customers.\n"
"\n"
"15: Renewal of Support and Updates: Licensee may purchase additional\n"
"Support and Updates following the Initial Term at Trolltech's terms\n"
"and conditions applicable at the time of renewal.\n"
"\n"
"16. Termination: Trolltech may terminate the Agreement at any time\n"
"immediately upon written notice by Trolltech to Licensee if Licensee\n"
"breaches this Agreement, fails to pay the fees for the Licensed\n"
"Software, or infringes Trolltech's intellectual property in or to the\n"
"Licensed Software. Upon termination of the Licenses, Licensee shall\n"
"return to Trolltech all copies of Licensed Software that were supplied\n"
"by Trolltech. All other copies of Licensed Software in the possession\n"
"or control of Licensee must be erased or destroyed. An officer of\n"
"Licensee must promptly deliver to Trolltech a written confirmation\n"
"that this has occurred.\n"
"\n"
"17. Entire Agreement: This Agreement constitutes the complete\n"
"agreement between the parties and supersedes all prior or\n"
"contemporaneous discussions, representations, and proposals, written\n"
"or oral, with respect to the subject matters discussed herein. No\n"
"modification of this Agreement will be effective unless contained in a\n"
"writing executed by an authorized representative of each party. No\n"
"term or condition contained in Licensee's purchase order will apply\n"
"unless expressly accepted by Trolltech in writing. If any provision of\n"
"the Agreement is found void or unenforceable, the remainder will\n"
"remain valid and enforceable according to its terms. If any remedy\n"
"provided is determined to have failed for its essential purpose, all\n"
"limitations of liability and exclusions of damages set forth in this\n"
"Agreement shall remain in effect.\n"
"\n"
"18. Governing law, legal venue: This Agreement shall be construed,\n"
"interpreted and governed by the laws of Norway, the legal venue to be\n"
"Oslo City Court. Trolltech reserves all rights not specifically\n"
"granted in this Agreement.\n"
"\n"
"\n"
"\n"
"Appendix 1:\n"
"Parts of the Licensed Software that are permitted for distribution\n"
"('Redistributables'):\n"
"\n"
"- The Licensed Software's main and plug-in libraries in object code\n"
"  form\n"
"- The Licensed Software's help tool in object code/executable\n"
"  form ('Qt Assistant')\n"
"- The Licensed Software's translator tool in object code/executable\n"
"  form ('Qt Linguist')\n"
"\n"
"Parts of the Licensed Software that are not permitted for distribution\n"
"include, but are not limited to:\n"
"\n"
"- The Licensed Software's source code and header files\n"
"- The Licensed Software's documentation\n"
"- The Licensed Software's designer tool ('Qt Designer')\n"
"\n"
};


resource 'STR#' (5002, "English") {
    {   /* array StringArray: 9 elements */
        /* [1] */
        "English",
        /* [2] */
        "Agree",
        /* [3] */
        "Disagree",
        /* [4] */
        "Print",
        /* [5] */
        "Save...",
        /* [6] */
        "IMPORTANT - Read this License Agreement carefully before clicking on "
        "the \"Agree\" button.  By clicking on the \"Agree\" button, you agree "
        "to be bound by the terms of the License Agreement.",
        /* [7] */
        "Software License Agreement",
        /* [8] */
        "This text cannot be saved. This disk may be full or locked, or the file "
        "may be locked.",
        /* [9] */
        "Unable to print. Make sure you’ve selected a printer."
    }
};

