#############################################################################
# $Id: makeqtmake,v 1.2 1998/02/26 09:36:21 hanord Exp  Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = syncpop

include $(QTDIR)/GNUmakefile.inc
