#############################################################################
# $Id: //depot/qt/main/tests/syncpop/Makefile#4 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = syncpop

!INCLUDE $(QTDIR)\Makefile.inc
