#############################################################################
# $Id: //depot/qt/main/src/util/mergetr/GNUmakefile#1 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = msgmerge

include $(QTDIR)/GNUmakefile.inc
