#############################################################################
# $Id: //depot/qt/main/src/util/mergetr/Makefile#1 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = msgmerge

!INCLUDE $(QTDIR)\Makefile.inc
