#############################################################################
# $Id: makeqtmake.bat,v 1.1 1998/07/02 16:55:53 hanord Exp  Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = combobox

include $(QTDIR)/GNUmakefile.inc
