#############################################################################
# $Id: //depot/qt/main/tutorial/t10/Makefile#16 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = t10

!INCLUDE $(QTDIR)\Makefile.inc
