#############################################################################
# Makefile for building mex
# Generated by tmake at 14:08, 1997/07/09
#     Project: mex.pro
#    Template: e:\tmake\lib\win32-msvc\app.t
#############################################################################

####### Compiler, tools and options

CC	=	cl
CFLAGS	=	-nologo -W3 -O1
INCPATH	=	-I$(QTDIR)\include
LINK	=	link
LFLAGS	=	/NOLOGO /SUBSYSTEM:windows
LIBS	=	$(QTDIR)\lib\qt.lib user32.lib gdi32.lib comdlg32.lib wsock32.lib
MOC	=	moc

####### Files

HEADERS =	
SOURCES =	mex.cpp
OBJECTS =	mex.obj
SRCMOC	=	
OBJMOC	=	
TARGET	=	mex.exe

####### Implicit rules

.SUFFIXES: .cpp .c

.cpp.obj:
	$(CC) -c $(CFLAGS) $(INCPATH) -Fo$@ $<

.c.obj:
	$(CC) -c $(CFLAGS) $(INCPATH) -Fo$@ $<

####### Build rules

all: $(TARGET) 

$(TARGET): $(OBJECTS) $(OBJMOC)
	$(LINK) $(LFLAGS) /OUT:$(TARGET) @<<
	    $(OBJECTS) $(OBJMOC) $(LIBS)
<<

moc: $(SRCMOC)

clean:
	-del mex.obj
	-del $(TARGET)

####### Compile

mex.obj: mex.cpp

