######################################################################
# Automatically generated by qmake (1.08a) Tue Nov 30 16:54:45 2004
######################################################################

TEMPLATE = app
CONFIG -= moc
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += events.cpp
CONFIG += qt warn_on debug  create_prl link_prl
OBJECTS_DIR=.obj/debug-shared
MOC_DIR=.moc/debug-shared
