######################################################################
# Automatically generated by qmake (1.02a) Tue Apr 23 16:34:46 2002
######################################################################

TEMPLATE = app
CONFIG -= moc

# Input
TARGET = test
SOURCES += main.cpp
