#############################################################################
# $Id: $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = startup

!INCLUDE $(QTDIR)\Makefile.inc
