######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 15 13:45:41 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += signalbug.h
SOURCES += signalbug.cpp
