#!/bin/bash


# Generate Makefile from .pro file
qmake

# Compile the program which creates the compressed project data file
g++ buildresources.cpp -I$QTDIR/include -L$QTDIR/lib -o buildresources -lqt

# Run the program using the setup.xml installation setup file
./buildresources -basepath SetupExampleFiles/ setup.xml > resourcedata.cpp

# Compile the resource data to link with the project
g++ -c resourcedata.cpp

# Build everything
make

# Run and test it
./qinstall

