######################################################################
# Automatically generated by qmake (1.02a) Thu Apr 18 18:56:53 2002
######################################################################

TEMPLATE = app
CONFIG -= moc

# Input
SOURCES += main.cpp

DEFINES += QT_USE_USING_NAMESPACE

