#############################################################################
# $Id: //depot/qt/main/tests/examples/tutorial/t11/GNUmakefile#1 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = t11

include $(QTDIR)/GNUmakefile.inc
