#############################################################################
# $Id: //depot/qt/main/extensions/opengl/examples/box/Makefile#8 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = box

!INCLUDE $(QTDIR)\Makefile.inc
