#############################################################################
# $Id: //depot/qt/2.2/examples/table/Makefile#1 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = statistics

!INCLUDE $(QTDIR)\Makefile.inc
