#############################################################################
# $Id: //depot/qt/main/extensions/nsplugin/src/Makefile#15 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = qnp

!INCLUDE $(QTDIR)\Makefile.inc
