#############################################################################
# $Id: //depot/qt/main/tests/netwm/GNUmakefile#2 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 2000 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = netwm

include $(QTDIR)/GNUmakefile.inc
