#############################################################################
# $Id: //depot/qt/main/tests/netwm/Makefile#2 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 2000 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = netwm

!INCLUDE $(QTDIR)\Makefile.inc
