#############################################################################
# $Id: //depot/qt/main/examples/listbox/GNUmakefile#3 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = listbox

include $(QTDIR)/GNUmakefile.inc
