#############################################################################
# $Id: //depot/qt/main/examples/tooltip/GNUmakefile#4 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = tooltip

include $(QTDIR)/GNUmakefile.inc
