#############################################################################
# $Id: //depot/qt/main/tests/fontrawname/GNUmakefile#2 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = fr

include $(QTDIR)/GNUmakefile.inc
