#############################################################################
# $Id: //depot/qt/main/tests/2000/Makefile#4 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = 2000

!INCLUDE $(QTDIR)\Makefile.inc
