#############################################################################
# $Id: //depot/qt/main/tests/spinbox/GNUmakefile#4 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = spin

include $(QTDIR)/GNUmakefile.inc
