#############################################################################
# $Id: makeqtmake,v 1.1 1998/02/25 18:12:02 hanord Exp  Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = spinbox

!INCLUDE $(QTDIR)\Makefile.inc
