#!/bin/sh
if [  $# -gt 1 ]; then
	rm -f $1
	touch $1
	for i in $@; do  
		grep -v "Reimplemented from" $i |
		grep -v "^ <a" |
		sed -ne 's/.*<a href=\"\([^\"]*\)\">\([^<]*\)<\/a>.*/\"\2\"\|'$i'\|\1/pg'  |
		grep -v "^\"More...\"" | 
		grep -v "^\"List of all member functions.\"" ; 
	done | awk -F \| '{ s=$3; if (substr($3,1,1)=="#") s=$2$3; print $1,s }' | sort | uniq > $1
else
	echo Usage: $0 indexfile filenames
fi
