#!/usr/bin/perl

undef $/;

@lines;
$output = $ARGV[ 0 ];

while ( <ARGV> ) {
  while (/.*<title.*>([^<]*)<\/title>.*/g ) {
    $line = $1;
    $line =~ s/\n//g;
    push( @lines, "$line | $ARGV\n" );
  }
}

@lines = sort( @lines );
open( INDEX, "> $output" );
print INDEX @lines;
close( INDEX );

################# old shell script ##################
##!/bin/sh
#if [  $# -gt 1 ]; then
#	rm -f $1
#	touch $1
#	for i in $@; do #### many, many hacks :-)
#  		cat $i |
#		tr "\n" " " |
#		sed -ne "s/.*<title.*>\([^<]*\)<\/title>.*/\1 | $i@/pg" |
#		tr "@" "\n" ;
#	done | sort -b > $1
#else
#	echo Usage: $0 indexfile filenames
#fi
