######################################################################
# Automatically generated by qmake (1.08a) Mon Dec 6 20:32:30 2004
######################################################################

TEMPLATE = app
CONFIG -= moc
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += timers.cpp
CONFIG += qt warn_on debug  create_prl link_prl
OBJECTS_DIR=.obj/debug-shared
MOC_DIR=.moc/debug-shared
