#############################################################################
# $Id: makeqtmake.bat,v 1.1 1998/07/02 16:55:53 hanord Exp  Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = themes

!INCLUDE $(QTDIR)\Makefile.inc
