######################################################################
# Automatically generated by qmake (2.00a) Wed Mar 23 09:13:03 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h scribblearea.h
SOURCES += main.cpp mainwindow.cpp scribblearea.cpp
