#############################################################################
# $Id: makeqtmake,v 1.3 1996/01/22 13:46:00 hanord Exp $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = keypad

include $(QTDIR)/GNUmakefile.inc
