#############################################################################
# $Id: //depot/qt/main/tests/examples/tutorial/t4/GNUmakefile#2 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = t4

include $(QTDIR)/GNUmakefile.inc
