#############################################################################
# $Id: //depot/qt/main/tests/examples/tutorial/t4/Makefile#1 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = t4

!INCLUDE $(QTDIR)\Makefile.inc
