#############################################################################
# $Id: //depot/qt/main/extensions/xt/src/GNUmakefile#3 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = qxt

include $(QTDIR)/GNUmakefile.inc
