#############################################################################
# $Id: //depot/qt/main/extensions/xt/src/Makefile#3 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = qxt

!INCLUDE $(QTDIR)\Makefile.inc
