#############################################################################
# $Id: //depot/qt/main/extensions/xt/src/Makefile#1 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = qxt

!INCLUDE $(QTDIR)\Makefile.inc
