#############################################################################
# $Id: //depot/qt/main/extensions/opengl/examples/gear/GNUmakefile#1 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = gear

include $(QTDIR)/GNUmakefile.inc
