#############################################################################
# $Id: //depot/qt/2.2/src/GNUmakefile#1 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1999 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = myplugin
include $(QTDIR)/GNUmakefile.inc
