######################################################################
# Automatically generated by qmake (1.07a) Fri Feb 27 11:08:58 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += ftpviewitem.h
INTERFACES += connectdialog.ui ftpmainwindow.ui
SOURCES += ftpmainwindow.ui.h ftpviewitem.cpp main.cpp
CONFIG += qt warn_on debug  create_prl link_prl
OBJECTS_DIR=.obj/release-shared
MOC_DIR=.moc/release-shared
