######################################################################
# Automatically generated by qmake (1.05a) Thu Feb 6 08:14:43 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
INTERFACES += form1.ui form2.ui
SOURCES += main.cpp
CONFIG += qt warn_on debug
