#############################################################################
# $Id: //depot/qt/main/tests/qtranslator_gui1/GNUmakefile#2 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = addressbook

include $(QTDIR)/GNUmakefile.inc
