#############################################################################
# $Id: //depot/qt/main/tests/winmanager/GNUmakefile#1 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 2000 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = winmanager

include $(QTDIR)/GNUmakefile.inc
