#############################################################################
# $Id: //depot/qt/main/tests/winmanager/Makefile#1 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 2000 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = winmanager

!INCLUDE $(QTDIR)\Makefile.inc
