TEMPLATE    = app
CONFIG      = qt warn_on release
TARGET      = dynamic
SOURCES    += main.cpp
unix:LIBS  += -lqresource
win32:LIBS += $(QTDIR)/lib/qresource.lib
INTERFACES	= mainform.ui 
IMAGEFILE	= images.cpp
PROJECTNAME	= dynamic
LANGUAGE	= C++
{SOURCES+=images.cpp}
