#############################################################################
# $Id: //depot/qt/main/tutorial/t13/Makefile#16 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = t13

!INCLUDE $(QTDIR)\Makefile.inc
