#############################################################################
# $Id: //depot/qt/main/examples/checklists/GNUmakefile#2 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = checklists

include $(QTDIR)/GNUmakefile.inc
