#############################################################################
# $Id: //depot/qt/main/util/qtranslator/GNUmakefile#2 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = qtranslator

include $(QTDIR)/GNUmakefile.inc
