#############################################################################
# $Id: //depot/qt/main/util/qtranslator/Makefile#5 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = qtranslator

!INCLUDE $(QTDIR)\Makefile.inc
