#############################################################################
# $Id: //depot/qt/main/examples/picture/Makefile#4 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = picture

!INCLUDE $(QTDIR)\Makefile.inc
