#############################################################################
# $Id: //depot/qt/main/tests/url/GNUmakefile#7 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = url

include $(QTDIR)/GNUmakefile.inc
