#############################################################################
# $Id: //depot/qt/main/examples/customlayout/Makefile#2 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = customlayout

!INCLUDE $(QTDIR)\Makefile.inc
