TEMPLATE    = app
CONFIG+= qt warn_on release
TARGET      = receiver
SOURCES    += main.cpp
unix:LIBS  += -lqui
win32:LIBS += $(QTDIR)/lib/qui.lib
HEADERS += receiver.h
SOURCES += receiver.cpp
INCLUDEPATH	+= $(QTDIR)/tools/designer/uilib
INTERFACES	= mainform.ui 
DBFILE	= receiver.db
IMAGEFILE	= images.cpp
PROJECTNAME	= receiver
LANGUAGE	= C++
