#############################################################################
# $Id: //depot/qt/main/tests/qbrowser/GNUmakefile#4 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = qbrowser

include $(QTDIR)/GNUmakefile.inc
