TEMPLATE	= app
CONFIG	= qt warn_on release
TARGET	= assistent
SOURCES	= main.cpp helpwindow.cpp topicchooserimpl.cpp helpdialogimpl.cpp
HEADERS	= helpwindow.h topicchooserimpl.h helpdialogimpl.h
INTERFACES	= mainwindow.ui topicchooser.ui helpdialog.ui 
DBFILE	= assistent.db
PROJECTNAME	= Assistent
LANGUAGE	= C++
