#!/bin/sh

LEN="$1"
STR="$2"
PAD="$3"
STRLEN=`echo $STR | wc -c`
echo "$STR\c"
    
EXTRALEN=`expr $LEN - $STRLEN`
while [ "$EXTRALEN" -gt 0 ]; do
   echo "$PAD\c"
   EXTRALEN=`expr $EXTRALEN - 1`
done
echo #return
