# $Id: //depot/qt/main/examples/application/Makefile#5 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = designer

!INCLUDE $(QTDIR)\Makefile.inc
