#############################################################################
# $Id: //depot/qt/main/tutorial/t3/Makefile#14 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = t3

!INCLUDE $(QTDIR)\Makefile.inc
