TEMPLATE	= lib
CONFIG		+= qt dll release
HEADERS		= 
SOURCES		= grapher.cpp
unix:LIBS	= -lqnp -lXt
win32:LIBS	= $$QT_BUILD_TREE/lib/qnp.lib $$QT_BUILD_TREE/lib/qtmain.lib
DEF_FILE	= grapher.def
RC_FILE		= grapher.rc
TARGET		= grapher
win32:TARGET	= npgrapher
