#############################################################################
# $Id: //depot/qt/main/extensions/nsplugin/examples/grapher/Makefile#5 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = grapher

!INCLUDE $(QTDIR)\Makefile.inc
