#############################################################################
# $Id: //depot/qt/main/tutorial/t4/Makefile#16 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = t4

!INCLUDE $(QTDIR)\Makefile.inc
