#############################################################################
# $Id: //depot/qt/main/tests/getopenfilenames/Makefile#1 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = gofs

!INCLUDE $(QTDIR)\Makefile.inc
