TEMPLATE	= app
CONFIG += qt warn_on release
TARGET	= richedit
INTERFACES	= richedit.ui 
DBFILE	= richedit.db
IMAGEFILE	= images.cpp
PROJECTNAME	= richedit
LANGUAGE	= C++
{SOURCES+=images.cpp}
SOURCES += main.cpp
