#############################################################################
# Qt Makefile - doc
#############################################################################
# $Id: //depot/qt/main/doc/Makefile#6 $

showfiles showsources:
	@echo *.doc

clean:
	-rm -f *~ *% #*

obj include depend:
