SOURCES	+= main.cpp 
TARGET      = receiver
IMAGEFILE	= images.cpp
FORMS	= mainform.ui 
TEMPLATE	=app
CONFIG	+= qt warn_on release
INCLUDEPATH	+= $(QTDIR)/tools/designer/uilib
win32:LIBS	+= $(QTDIR)/lib/qui.lib
unix:LIBS	+= -lqui
DBFILE	= receiver.db
LANGUAGE	= C++
