SOURCES	+= main.cpp 
TARGET      = receiver
IMAGEFILE	= images.cpp
FORMS	= mainform.ui 
TEMPLATE	=app
CONFIG	+= qt warn_on release
INCLUDEPATH	+= $$QT_SOURCE_TREE/tools/designer/uilib
LIBS	+= -lqui
DBFILE	= receiver.db
LANGUAGE	= C++
