#############################################################################
# $Id: //depot/qt/main/examples/menu/Makefile#3 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = menu

!INCLUDE $(QTDIR)\Makefile.inc
