######################################################################
# Automatically generated by qmake (2.00a) Tue Apr 26 15:21:59 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += controllerwindow.h previewwindow.h
SOURCES += controllerwindow.cpp main.cpp previewwindow.cpp
