#############################################################################
# $Id: //depot/qt/main/tests/identify/GNUmakefile#4 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = identify

include $(QTDIR)/GNUmakefile.inc
