#############################################################################
# $Id: //depot/qt/main/examples/application/Makefile#4 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = application

include $(QTDIR)/Makefile.inc
