#############################################################################
# $Id: //depot/qt/main/tests/xvisualinfo/Makefile#2 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = xvi

!INCLUDE $(QTDIR)\Makefile.inc
