/*
  htmlchunk.h
*/

#ifndef HTMLCHUNK_H
#define HTMLCHUNK_H

class QString;

/*
  The HtmlChunk class represents a chunk of HTML read by HtmlReader.  The chunk
  should correspond to one Doc comment.

  The HTML chunk read (generated by the previous qdoc run) is compared to the
  new HTML chunk.  The method isSame() returns TRUE if the HTML chunk is
  (probably) the same as the argument.  qdoc is allowed to miss a few changes,
  but it must never report a change where there was none.
*/
class HtmlChunk
{
public:
    HtmlChunk();
    HtmlChunk( const QString& oldHtml );
    HtmlChunk( const HtmlChunk& chk );

    HtmlChunk& operator=( const HtmlChunk& chk );

    bool isSame( const QString& newHtml ) const;
    int length() const { return len; }

private:
    int len;
};

#endif
