#############################################################################
# $Id: //depot/qt/main/examples/helpviewer/Makefile#4 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = helpviewer

!INCLUDE $(QTDIR)\Makefile.inc
