/*! \quickclass QAccel */
/*! \quickclass QAction */
/*! \quickclass QActionGroup */
/*! \quickclass QApplication */
/*! \quickclass QAquaStyle */
/*! \quickclass QBoxLayout */
/*! \quickclass QButton */
/*! \quickclass QButtonGroup */
/*! \quickclass QCDEStyle */
/*! \quickclass QCanvas */
/*! \quickclass QCanvasView */
/*! \quickclass QCheckBox */
/*! \quickclass QClipboard */
/*! \quickclass QColorDialog */
/*! \quickclass QColorDrag */
/*! \quickclass QComboBox */
/*! \quickclass QCommonStyle */
/*! \quickclass QCopChannel */
/*! \quickclass QDataBrowser */
/*! \quickclass QDataPump */
/*! \quickclass QDataTable */
/*! \quickclass QDataView */
/*! \quickclass QDatabase */
/*! \quickclass QDatabaseCursor */
/*! \quickclass QDatabaseField */
/*! \quickclass QDatabaseIndex */
/*! \quickclass QDatabaseQuery */
/*! \quickclass QDatabaseRecord */
/*! \quickclass QDateTimeEdit */
/*! \quickclass QDesktopWidget */
/*! \quickclass QDial */
/*! \quickclass QDialog */
/*! \quickclass QDns */
/*! \quickclass QDockArea */
/*! \quickclass QDockWindow */
/*! \quickclass QDoubleValidator */
/*! \quickclass QDragObject */
/*! \quickclass QEditorFactory */
/*! \quickclass QErrorMessage */
/*! \quickclass QFileDialog */
/*! \quickclass QFileIconProvider */
/*! \quickclass QFontDialog */
/*! \quickclass QFrame */
/*! \quickclass QFtp */
/*! \quickclass QGLWidget */
/*! \quickclass QGrid */
/*! \quickclass QGridLayout */
/*! \quickclass QGridView */
/*! \quickclass QGroupBox */
/*! \quickclass QHBox */
/*! \quickclass QHBoxLayout */
/*! \quickclass QHButtonGroup */
/*! \quickclass QHGroupBox */
/*! \quickclass QHeader */
/*! \quickclass QHttp */
/*! \quickclass QHttpClient */
/*! \quickclass QIconDrag */
/*! \quickclass QIconFactory */
/*! \quickclass QIconView */
/*! \quickclass QImageDrag */
/*! \quickclass QInputDialog */
/*! \quickclass QIntValidator */
/*! \quickclass QLCDNumber */
/*! \quickclass QLabel */
/*! \quickclass QLayout */
/*! \quickclass QLineEdit */
/*! \quickclass QListBox */
/*! \quickclass QListBoxItem */
/*! \quickclass QListView */
/*! \quickclass QListViewItem */
/*! \quickclass QLocalFs */
/*! \quickclass QMainWindow */
/*! \quickclass QMenuBar */
/*! \quickclass QMessageBox */
/*! \quickclass QMotifPlusStyle */
/*! \quickclass QMotifStyle */
/*! \quickclass QMultiLineEdit */
/*! \quickclass QNPInstance */
/*! \quickclass QNPWidget */
/*! \quickclass QNetworkOperation */
/*! \quickclass QNetworkProtocol */
/*! \quickclass QObject */
/*! \quickclass QObjectCleanupHandler */
/*! \quickclass QObjectList */
/*! \quickclass QPlatinumStyle */
/*! \quickclass QPopupMenu */
/*! \quickclass QProcess */
/*! \quickclass QProgressBar */
/*! \quickclass QProgressDialog */
/*! \quickclass QPushButton */
/*! \quickclass QRadioButton */
/*! \quickclass QRegExpValidator */
/*! \quickclass QSGIStyle */
/*! \quickclass QScrollBar */
/*! \quickclass QScrollView */
/*! \quickclass QServerSocket */
/*! \quickclass QSessionManager */
/*! \quickclass QSignal */
/*! \quickclass QSignalMapper */
/*! \quickclass QSizeGrip */
/*! \quickclass QSlider */
/*! \quickclass QSocket */
/*! \quickclass QSocketNotifier */
/*! \quickclass QSound */
/*! \quickclass QSpinBox */
/*! \quickclass QSplitter */
/*! \quickclass QStatusBar */
/*! \quickclass QStoredDrag */
/*! \quickclass QStyle */
/*! \quickclass QStyleSheet */
/*! \quickclass QTabBar */
/*! \quickclass QTabDialog */
/*! \quickclass QTabWidget */
/*! \quickclass QTable */
/*! \quickclass QTextBrowser */
/*! \quickclass QTextDrag */
/*! \quickclass QTextEdit */
/*! \quickclass QTextView */
/*! \quickclass QTimer */
/*! \quickclass QToolBar */
/*! \quickclass QToolButton */
/*! \quickclass QToolTipGroup */
/*! \quickclass QTranslator */
/*! \quickclass QUriDrag */
/*! \quickclass QUrlOperator */
/*! \quickclass QVBox */
/*! \quickclass QVBoxLayout */
/*! \quickclass QVButtonGroup */
/*! \quickclass QVGroupBox */
/*! \quickclass QValidator */
/*! \quickclass QWidget */
/*! \quickclass QWidgetStack */
/*! \quickclass QWindowsStyle */
/*! \quickclass QWizard */
/*! \quickclass QWorkspace */
