/*! \quickclass Accel */
/*! \quickclass AccessibleObject */
/*! \quickclass Action */
/*! \quickclass ActionGroup */
/*! \quickclass Application */
/*! \quickclass AquaStyle */
/*! \quickclass BoxLayout */
/*! \quickclass Button */
/*! \quickclass ButtonGroup */
/*! \quickclass CDEStyle */
/*! \quickclass Canvas */
/*! \quickclass CanvasView */
/*! \quickclass CheckBox */
/*! \quickclass Clipboard */
/*! \quickclass ColorDialog */
/*! \quickclass ColorDrag */
/*! \quickclass ComboBox */
/*! \quickclass CommonStyle */
/*! \quickclass CopChannel */
/*! \quickclass DataBrowser */
/*! \quickclass DataPump */
/*! \quickclass DataTable */
/*! \quickclass DataView */
/*! \quickclass Database */
/*! \quickclass DatabaseCursor */
/*! \quickclass DatabaseField */
/*! \quickclass DatabaseIndex */
/*! \quickclass DatabaseQuery */
/*! \quickclass DatabaseRecord */
/*! \quickclass DateTimeEdit */
/*! \quickclass DesktopWidget */
/*! \quickclass Dial */
/*! \quickclass Dialog */
/*! \quickclass Dns */
/*! \quickclass DockArea */
/*! \quickclass DockWindow */
/*! \quickclass DoubleValidator */
/*! \quickclass DragObject */
/*! \quickclass EditorFactory */
/*! \quickclass ErrorMessage */
/*! \quickclass FileDialog */
/*! \quickclass FileIconProvider */
/*! \quickclass FontDialog */
/*! \quickclass Frame */
/*! \quickclass Ftp */
/*! \quickclass GLWidget */
/*! \quickclass Grid */
/*! \quickclass GridLayout */
/*! \quickclass GridView */
/*! \quickclass GroupBox */
/*! \quickclass HBox */
/*! \quickclass HBoxLayout */
/*! \quickclass HButtonGroup */
/*! \quickclass HGroupBox */
/*! \quickclass Header */
/*! \quickclass Http */
/*! \quickclass HttpClient */
/*! \quickclass IconDrag */
/*! \quickclass IconFactory */
/*! \quickclass IconView */
/*! \quickclass ImageDrag */
/*! \quickclass InputDialog */
/*! \quickclass IntValidator */
/*! \quickclass LCDNumber */
/*! \quickclass Label */
/*! \quickclass Layout */
/*! \quickclass LineEdit */
/*! \quickclass ListBox */
/*! \quickclass ListBoxItem */
/*! \quickclass ListView */
/*! \quickclass ListViewItem */
/*! \quickclass LocalFs */
/*! \quickclass MacStyle */
/*! \quickclass MainWindow */
/*! \quickclass MenuBar */
/*! \quickclass MessageBox */
/*! \quickclass MotifPlusStyle */
/*! \quickclass MotifStyle */
/*! \quickclass MultiLineEdit */
/*! \quickclass NPInstance */
/*! \quickclass NPWidget */
/*! \quickclass NetworkOperation */
/*! \quickclass NetworkProtocol */
/*! \quickclass Object */
/*! \quickclass ObjectCleanupHandler */
/*! \quickclass ObjectList */
/*! \quickclass PlatinumStyle */
/*! \quickclass PopupMenu */
/*! \quickclass Process */
/*! \quickclass ProgressBar */
/*! \quickclass ProgressDialog */
/*! \quickclass PushButton */
/*! \quickclass RadioButton */
/*! \quickclass RegExpValidator */
/*! \quickclass SGIStyle */
/*! \quickclass ScrollBar */
/*! \quickclass ScrollView */
/*! \quickclass ServerSocket */
/*! \quickclass SessionManager */
/*! \quickclass Signal */
/*! \quickclass SignalMapper */
/*! \quickclass SizeGrip */
/*! \quickclass Slider */
/*! \quickclass Socket */
/*! \quickclass SocketNotifier */
/*! \quickclass Sound */
/*! \quickclass SpinBox */
/*! \quickclass Splitter */
/*! \quickclass StatusBar */
/*! \quickclass StoredDrag */
/*! \quickclass Style */
/*! \quickclass StyleSheet */
/*! \quickclass TabBar */
/*! \quickclass TabDialog */
/*! \quickclass TabWidget */
/*! \quickclass Table */
/*! \quickclass TextBrowser */
/*! \quickclass TextDrag */
/*! \quickclass TextEdit */
/*! \quickclass TextView */
/*! \quickclass Timer */
/*! \quickclass ToolBar */
/*! \quickclass ToolButton */
/*! \quickclass ToolTipGroup */
/*! \quickclass Translator */
/*! \quickclass UriDrag */
/*! \quickclass UrlOperator */
/*! \quickclass VBox */
/*! \quickclass VBoxLayout */
/*! \quickclass VButtonGroup */
/*! \quickclass VGroupBox */
/*! \quickclass Validator */
/*! \quickclass Widget */
/*! \quickclass WidgetStack */
/*! \quickclass WindowsStyle */
/*! \quickclass Wizard */
/*! \quickclass Workspace */
