#############################################################################
# $Id: //depot/qt/main/src/moc/GNUmakefile#18 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = moc

include $(QTDIR)/GNUmakefile.inc
