#############################################################################
# $Id: //depot/qt/main/src/moc/GNUmakefile#19 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = moc
RELEASE = 1
include $(QTDIR)/GNUmakefile.inc
