#############################################################################
# $Id: //depot/qt/main/examples/validator/Makefile#4 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = validator

!INCLUDE $(QTDIR)\Makefile.inc
