#!/usr/bin/perl

chdir($ENV{"HOME"} . "/trial");
$p = `pwd`; print $p;

print "CREATE QT/WIN32 TRIAL\n\n";

@complist = ( "msvc5",  "msvc4",  "borland5",  "gcc" );
@offslist = ( 2230779,  00000,    00000,       00000 );
$correct = 0;

while ( ! $correct ) {
    do {
	print "Name ...... ";
	$name = <STDIN>;
	chop $name;
    } while ($name eq "");
    print "Company ... ";
    $company = <STDIN>;
    chop $company;
    do {
	print "Email ..... ";
	$email = <STDIN>;
	chop $email;
    } while ($email eq "");
    do { 
	print "Compiler .. (1=msvc5, 2=msvc4, 3=borland5, 4=gcc) ";
	$compiler = <STDIN>;
	chop $compiler;
    } while ($compiler =~ /[^1-5]$/);
    $offset = $offslist[$compiler-1];
    $compiler = $complist[$compiler-1];

    print "\nIs this correct? [y] ";
    $answer = <STDIN>;
    chop $answer;
    $correct = $answer eq "" || $answer eq "y" || $answer eq "Y";
}

$file = $compiler . "/qt/lib/";
if ( $compiler eq "gcc" ) {
    $file .= "libqt.a";
} else {
    $file .= "qt.lib";
}
$comp_arg = "-company $company" if $company;

# SQL Stored Procedure: add_trial "$name", "$company", "$email"
# Returns a serial number.
$serial = 123;

# SQL:
# If (SELECT count(*) FROM qt_trials WHERE name LIKE "$name") > 0
#   give a warning that the same person has registered it twice
#
# If (SELECT count(*) FROM qt_trials WHERE company LIKE "$company") > 0
#   print out list of all people from that company that have evaluated
#   before.

$t=`qtrial -name $name $comp_arg -email $email -file $file -offset $offset -serial $serial`;
print $t;

# -----------

#    print "\nYou have entered the following information:\n";
#    print "\tName ...... ${name}\n";
#    print "\tCompany ... " . (($company eq "") ? "<none>" : $company) . "\n";
#    print "\tEmail ..... ${email}\n";
#    print "\tCompiler .. ${compiler}\n";
