#############################################################################
# $Id: //depot/qt/2.2/examples/application/Makefile#2 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = util
LIBTARGET = 1

!INCLUDE $(QTDIR)\Makefile.inc
