#!/usr/bin/perl -w -i

use strict;
use vars qw($prev);

BEGIN { $prev = '' }

while ( <> ) {
    s/images\\/images\//g;
    if ( /^ALIGN="LEFT"/ and $prev =~ /^SRC="/ ) {
	s/LEFT/center/;
    }

    $prev = $_;

    print;
}

