#############################################################################
# $Id: //depot/qt/main/examples/forever/Makefile#4 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = forever

!INCLUDE $(QTDIR)\Makefile.inc
