TEMPLATE	= app
CONFIG += qt warn_on debug
TARGET	= assistant
SOURCES	= main.cpp helpwindow.cpp topicchooserimpl.cpp helpdialogimpl.cpp
HEADERS	= helpwindow.h topicchooserimpl.h helpdialogimpl.h
INTERFACES	= mainwindow.ui topicchooser.ui finddialog.ui helpdialog.ui 
DBFILE	= assistiant.db
PROJECTNAME	= Assistant
LANGUAGE	= C++
DESTDIR	= ../../bin
