#!/usr/bin/perl

chdir "$ENV{HOME}/qt/e/examples/launcher";

$ENV{QWS_LOADFONTS}=1;
$ENV{QWS_NOSHARED}=1;

use POSIX ":sys_wait_h";
$QWS_PORT=17986;

system("/usr/sbin/fbset -depth 16 1024x768-70; ".
       "setterm -powersave off; ".
       "setterm -blank 0; ".
       "rm /tmp/.QtEmbedded*; "
);

$ENV{QWS_MOUSE_PROTO}="MouseMan:/dev/mouse MouseMan:/dev/usb/mouse0";
$ENV{QTDIR}="/home/warwick/qt/e";

$file_qws = "../../util/qws/qws"; $args_qws="+k";
$file_launcher = "./launcher"; $args_launcher="";

# Leave stdout on console so people see it is real
#
#$silence="2>/dev/null >/dev/null";
$silence="2>>log";
unlink "log";

system("killall $file_qws 2>/dev/null");

sub kill_them___kill_them_all {
    # kill all those talking to the server
    @p=map { chomp; $_ } split / /,`fuser -n tcp ,localhost,$QWS_PORT`;
    shift @p;
    @pids = @p;
    @p=map { chomp; s/[a-z]//; $_ } split / /,`fuser /dev/fb0`;
    shift @p;
    @pids = grep { $_ != $$ && $_ != getppid } (@pids, @p);
    print "$$ Kill: ".join(" ",@pids)."\r\n";
    map { if ( $_ ) { print "kill $_\r\n"; kill 15, $_; } } sort @pids;
    sleep 1;
    map { if ( $_ ) { print "kill $_\r\n"; kill 9, $_; } } sort @pids;
    system("rm /tmp/.QtEmbedded*");
}

kill_them___kill_them_all;

$continue=10;

$SIG{INT} = $SIG{TERM} = sub {
    $continue=0;
};

while ( $continue-- ) {
    {
        if ( !$server ) {
	    unless ( $server = fork() ) {
		exec "exec $file_qws $args_qws $silence";
		$fail++;
		print "Server exec failed\n";
		exit 0;
	    }
	    print "Server $server\n";
	    select(undef,undef,undef,0.5);
	}
	if ( !$client ) {
	    unless ( $client = fork() ) {
		exec "exec $file_launcher $args_launcher $silence";
		$fail++;
		print "Client exec failed\n";
		exit 0;
	    }
	    print "Client $client";
	}
    }

    if ( $ARGV[0] eq "-1" ) {
	wait;
    } else {
	for (1..3) {
	    $dead = wait;
	    $r = $?;
print "$dead died ($r)\n\r";
	    if ( $dead > 0 ) {
		if ( $dead == $client ) {
printf "Client dies...\r\n";
		    $client = 0;
		    if ( $server ) {
			kill_them___kill_them_all;
		    }
		    if ( $r>>8 == 3 ) {
			$continue=0;
		    }
		} elsif ( $dead == $server ) {
printf "Server dies...\r\n";
		    $server = 0;
		    print "NO SERVER! Killing clients...\r\n";
		    #system("mv core core.qws");
		    if ( $client ) {
			    #system("kill $client 2>/dev/null");
			    #sleep 1;
			    system("kill -9 $client 2>/dev/null");
			    sleep 1;
		    }
		    kill_them___kill_them_all;
		} else {
printf "Who?\r\n";
		}
	    }
	}
    }
}

system("kbd_mode -a");
system("setterm -reset");
system("reset");
kill_them___kill_them_all;
system("kbd_mode -a");
system("setterm -reset");
system("reset");
