# $Source: /tmp/cvs/qt/examples/Makefile,v $
#

####### Tools

TMAKE	=	tmake

####### Directories

SUBDIRS =	

####### Targets

all: targets

showdirs:
	@echo $(SUBDIRS)

targets:

galore:

tmake:

clean:

Makefile: examples.t examples.pro
	$(TMAKE) examples.pro -o Makefile

