# $Source: /tmp/cvs/qt/examples/Makefile,v $
#

####### Tools

TMAKE	=	tmake

####### Directories

SUBDIRS =	dirview \
		layout \
		picture \
		scrollview \
		validator \
		application \
		dragdrop \
		popup \
		xform \
		drawlines \
		drawdemo \
		cursor \
		forever \
		menu \
		progress \
		splitter \
		hello \
		table \
		desktop \
		rot13 \
		tooltip \
		wizard \
		i18n \
		lineedits \
		listviews \
		buttons_groups \
		rangecontrols \
		progressbar \
		tabdialog \
		listbox_combo \
		themes \
		checklists \
		richtext \
		qiconview \
		customlayout

####### Targets

all: targets

showdirs:
	@echo $(SUBDIRS)

targets:
	cd dirview
	$(MAKE)
	cd ..
	cd layout
	$(MAKE)
	cd ..
	cd picture
	$(MAKE)
	cd ..
	cd scrollview
	$(MAKE)
	cd ..
	cd validator
	$(MAKE)
	cd ..
	cd application
	$(MAKE)
	cd ..
	cd dragdrop
	$(MAKE)
	cd ..
	cd popup
	$(MAKE)
	cd ..
	cd xform
	$(MAKE)
	cd ..
	cd drawlines
	$(MAKE)
	cd ..
	cd drawdemo
	$(MAKE)
	cd ..
	cd cursor
	$(MAKE)
	cd ..
	cd forever
	$(MAKE)
	cd ..
	cd menu
	$(MAKE)
	cd ..
	cd progress
	$(MAKE)
	cd ..
	cd splitter
	$(MAKE)
	cd ..
	cd hello
	$(MAKE)
	cd ..
	cd table
	$(MAKE)
	cd ..
	cd desktop
	$(MAKE)
	cd ..
	cd rot13
	$(MAKE)
	cd ..
	cd tooltip
	$(MAKE)
	cd ..
	cd wizard
	$(MAKE)
	cd ..
	cd i18n
	$(MAKE)
	cd ..
	cd lineedits
	$(MAKE)
	cd ..
	cd listviews
	$(MAKE)
	cd ..
	cd buttons_groups
	$(MAKE)
	cd ..
	cd rangecontrols
	$(MAKE)
	cd ..
	cd progressbar
	$(MAKE)
	cd ..
	cd tabdialog
	$(MAKE)
	cd ..
	cd listbox_combo
	$(MAKE)
	cd ..
	cd themes
	$(MAKE)
	cd ..
	cd checklists
	$(MAKE)
	cd ..
	cd richtext
	$(MAKE)
	cd ..
	cd qiconview
	$(MAKE)
	cd ..
	cd customlayout
	$(MAKE)
	cd ..

galore:
	cd dirview
	dirview.exe
	cd ..
	cd layout
	layout.exe
	cd ..
	cd picture
	picture.exe
	cd ..
	cd scrollview
	scrollview.exe
	cd ..
	cd validator
	validator.exe
	cd ..
	cd application
	application.exe
	cd ..
	cd dragdrop
	dragdrop.exe
	cd ..
	cd popup
	popup.exe
	cd ..
	cd xform
	xform.exe
	cd ..
	cd drawlines
	drawlines.exe
	cd ..
	cd drawdemo
	drawdemo.exe
	cd ..
	cd cursor
	cursor.exe
	cd ..
	cd forever
	forever.exe
	cd ..
	cd menu
	menu.exe
	cd ..
	cd progress
	progress.exe
	cd ..
	cd splitter
	splitter.exe
	cd ..
	cd hello
	hello.exe
	cd ..
	cd table
	table.exe
	cd ..
	cd desktop
	desktop.exe
	cd ..
	cd rot13
	rot13.exe
	cd ..
	cd tooltip
	tooltip.exe
	cd ..
	cd wizard
	wizard.exe
	cd ..
	cd i18n
	i18n.exe
	cd ..
	cd lineedits
	lineedits.exe
	cd ..
	cd listviews
	listviews.exe
	cd ..
	cd buttons_groups
	buttons_groups.exe
	cd ..
	cd rangecontrols
	rangecontrols.exe
	cd ..
	cd progressbar
	progressbar.exe
	cd ..
	cd tabdialog
	tabdialog.exe
	cd ..
	cd listbox_combo
	listbox_combo.exe
	cd ..
	cd themes
	themes.exe
	cd ..
	cd checklists
	checklists.exe
	cd ..
	cd richtext
	richtext.exe
	cd ..
	cd qiconview
	qiconview.exe
	cd ..
	cd customlayout
	customlayout.exe
	cd ..

tmake:
	cd dirview
	$(TMAKE) dirview.pro -o Makefile
	cd ..
	cd layout
	$(TMAKE) layout.pro -o Makefile
	cd ..
	cd picture
	$(TMAKE) picture.pro -o Makefile
	cd ..
	cd scrollview
	$(TMAKE) scrollview.pro -o Makefile
	cd ..
	cd validator
	$(TMAKE) validator.pro -o Makefile
	cd ..
	cd application
	$(TMAKE) application.pro -o Makefile
	cd ..
	cd dragdrop
	$(TMAKE) dragdrop.pro -o Makefile
	cd ..
	cd popup
	$(TMAKE) popup.pro -o Makefile
	cd ..
	cd xform
	$(TMAKE) xform.pro -o Makefile
	cd ..
	cd drawlines
	$(TMAKE) drawlines.pro -o Makefile
	cd ..
	cd drawdemo
	$(TMAKE) drawdemo.pro -o Makefile
	cd ..
	cd cursor
	$(TMAKE) cursor.pro -o Makefile
	cd ..
	cd forever
	$(TMAKE) forever.pro -o Makefile
	cd ..
	cd menu
	$(TMAKE) menu.pro -o Makefile
	cd ..
	cd progress
	$(TMAKE) progress.pro -o Makefile
	cd ..
	cd splitter
	$(TMAKE) splitter.pro -o Makefile
	cd ..
	cd hello
	$(TMAKE) hello.pro -o Makefile
	cd ..
	cd table
	$(TMAKE) table.pro -o Makefile
	cd ..
	cd desktop
	$(TMAKE) desktop.pro -o Makefile
	cd ..
	cd rot13
	$(TMAKE) rot13.pro -o Makefile
	cd ..
	cd tooltip
	$(TMAKE) tooltip.pro -o Makefile
	cd ..
	cd wizard
	$(TMAKE) wizard.pro -o Makefile
	cd ..
	cd i18n
	$(TMAKE) i18n.pro -o Makefile
	cd ..
	cd lineedits
	$(TMAKE) lineedits.pro -o Makefile
	cd ..
	cd listviews
	$(TMAKE) listviews.pro -o Makefile
	cd ..
	cd buttons_groups
	$(TMAKE) buttons_groups.pro -o Makefile
	cd ..
	cd rangecontrols
	$(TMAKE) rangecontrols.pro -o Makefile
	cd ..
	cd progressbar
	$(TMAKE) progressbar.pro -o Makefile
	cd ..
	cd tabdialog
	$(TMAKE) tabdialog.pro -o Makefile
	cd ..
	cd listbox_combo
	$(TMAKE) listbox_combo.pro -o Makefile
	cd ..
	cd themes
	$(TMAKE) themes.pro -o Makefile
	cd ..
	cd checklists
	$(TMAKE) checklists.pro -o Makefile
	cd ..
	cd richtext
	$(TMAKE) richtext.pro -o Makefile
	cd ..
	cd qiconview
	$(TMAKE) qiconview.pro -o Makefile
	cd ..
	cd customlayout
	$(TMAKE) customlayout.pro -o Makefile
	cd ..

clean depend:
	cd dirview
	$(MAKE) $*
	cd ..
	cd layout
	$(MAKE) $*
	cd ..
	cd picture
	$(MAKE) $*
	cd ..
	cd scrollview
	$(MAKE) $*
	cd ..
	cd validator
	$(MAKE) $*
	cd ..
	cd application
	$(MAKE) $*
	cd ..
	cd dragdrop
	$(MAKE) $*
	cd ..
	cd popup
	$(MAKE) $*
	cd ..
	cd xform
	$(MAKE) $*
	cd ..
	cd drawlines
	$(MAKE) $*
	cd ..
	cd drawdemo
	$(MAKE) $*
	cd ..
	cd cursor
	$(MAKE) $*
	cd ..
	cd forever
	$(MAKE) $*
	cd ..
	cd menu
	$(MAKE) $*
	cd ..
	cd progress
	$(MAKE) $*
	cd ..
	cd splitter
	$(MAKE) $*
	cd ..
	cd hello
	$(MAKE) $*
	cd ..
	cd table
	$(MAKE) $*
	cd ..
	cd desktop
	$(MAKE) $*
	cd ..
	cd rot13
	$(MAKE) $*
	cd ..
	cd tooltip
	$(MAKE) $*
	cd ..
	cd wizard
	$(MAKE) $*
	cd ..
	cd i18n
	$(MAKE) $*
	cd ..
	cd lineedits
	$(MAKE) $*
	cd ..
	cd listviews
	$(MAKE) $*
	cd ..
	cd buttons_groups
	$(MAKE) $*
	cd ..
	cd rangecontrols
	$(MAKE) $*
	cd ..
	cd progressbar
	$(MAKE) $*
	cd ..
	cd tabdialog
	$(MAKE) $*
	cd ..
	cd listbox_combo
	$(MAKE) $*
	cd ..
	cd themes
	$(MAKE) $*
	cd ..
	cd checklists
	$(MAKE) $*
	cd ..
	cd richtext
	$(MAKE) $*
	cd ..
	cd qiconview
	$(MAKE) $*
	cd ..
	cd customlayout
	$(MAKE) $*
	cd ..


Makefile: simple.t simple.pro
	$(TMAKE) simple.pro -o Makefile

