#############################################################################
# $Id: //depot/qt/main/tests/textcodec/GNUmakefile#1 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = textcodec

include $(QTDIR)/GNUmakefile.inc
