#############################################################################
# $Id: //depot/qt/main/util/qws/GNUmakefile#1 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = qtfb

include $(QTDIR)/GNUmakefile.inc
