#############################################################################
# $Id: //depot/qt/main/tutorial/t1/Makefile#17 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = t1

!INCLUDE $(QTDIR)\Makefile.inc
