#############################################################################
# $Id: //depot/qt/main/extensions/xt/examples/mainlyMotif/GNUmakefile#1 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = editor

include $(QTDIR)/GNUmakefile.inc
