######################################################################
# Automatically generated by qmake (1.03a) Tue Aug 6 10:59:53 2002
######################################################################

TEMPLATE = app

# Input
CONFIG += console
HEADERS += packageserver.h
SOURCES += main.cpp packageserver.cpp
