#############################################################################
# $Id: //depot/qt/main/tests/well/Makefile#5 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = well

!INCLUDE $(QTDIR)\Makefile.inc
