#############################################################################
# $Id: //depot/qt/main/extensions/nsplugin/examples/qtimage/GNUmakefile#3 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = qtimage

include $(QTDIR)/GNUmakefile.inc
