#############################################################################
# $Id: //depot/qt/main/extensions/nsplugin/examples/qtimage/Makefile#7 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = qtimage

!INCLUDE $(QTDIR)\Makefile.inc
