#############################################################################
# $Id: //depot/qt/main/extensions/nsplugin/examples/qtimage/Makefile#9 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = qtimage

!INCLUDE $(QTDIR)\Makefile.inc
