TEMPLATE	= lib
CONFIG		+= qt dll release
HEADERS		= 
SOURCES		= qtimage.cpp
unix:LIBS	= -lqnp -lXt
win32:LIBS	+= $$QT_BUILD_TREE/lib/qnp.lib
DEF_FILE	= qtimage.def
RC_FILE		= qtimage.rc
TARGET		= qtimage
win32:TARGET	= npqtimage
