#############################################################################
# $Id: //depot/qt/main/examples/i18n/Makefile#3 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = i18n

!INCLUDE $(QTDIR)\Makefile.inc
