#############################################################################
# $Id: //depot/qt/main/examples/qwerty/GNUmakefile#4 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = qwerty

include $(QTDIR)/GNUmakefile.inc
