SOURCES	+= main.cpp 
HEADERS	+= receiver.h 
TARGET      = receiver
SOURCES += receiver.cpp
INTERFACES	= mainform.ui 
TEMPLATE	=app
CONFIG	+= qt warn_on release
INCLUDEPATH	+= $(QTDIR)/tools/designer/uilib
win32:LIBS	+= $(QTDIR)/lib/qui.lib
unix:LIBS	+= -lqui
DBFILE	= receiver.db
IMAGEFILE	= images.cpp
PROJECTNAME	= receiver
LANGUAGE	= C++
