SOURCES	+= main.cpp  receiver.cpp
HEADERS	+= receiver.h 
TARGET      = receiver
FORMS	= mainform.ui 
TEMPLATE	=app
CONFIG	+= qt warn_on release
INCLUDEPATH	+= $$QT_SOURCE_TREE/tools/designer/uilib
win32:LIBS	+= $$QT_BUILD_TREE/lib/qui.lib
unix:LIBS	+= -lqui
DBFILE	= receiver.db
IMAGEFILE	= images.cpp
LANGUAGE	= C++
