namespace QMsNet
{
    using System;
    using System.IO;
    using System.Drawing;
    using System.Windows.Forms;
    using Microsoft.Win32;

    public class Resource
    {
	public static string Version = "v.1.0.0";
	// The command bar constants.
	public static string CommandBarName = "QMsNet";
	public static string QtDir = "";
	public static string qtVersion = "";
	public static bool   qtShared = false;
	public static bool   qtThreaded = false;
    
	// All the constants for the NewQtProject command.
	public static int NewQtProjectBitmapID = 1 ;
	public static string 
	    NewQtProject		= "NewQtProject",
	    NewQtProjectButtonText	= "New a Qt Project ",
	    NewQtProjectToolTip		= "This create a new Qt project",
	    NewQtProjectFullCommand	= "QMsNet.NewQtProject";

	// All the constants for the MakeQtProject command.
	public static int MakeQtProjectBitmapID = 2 ;
	public static string 
	    MakeQtProject		= "MakeQtProject",
	    MakeQtProjectButtonText	= "Make a Qt Project ",
	    MakeQtProjectToolTip	= "This will convert the current project to use the Qt library",
	    MakeQtProjectFullCommand	= "QMsNet.MakeQtProject";

	// All the constants for the LoadQtProject command.
	public static int LoadDesignerBitmapID = 3 ;
	public static string 
	    LoadDesigner		= "LoadDesigner",
	    LoadDesignerButtonText	= "Load Designer",
	    LoadDesignerToolTip		= "This will start Qt Designer and load the current project",
	    LoadDesignerFullCommand	= "QMsNet.LoadDesigner";

	// All the constants for the LoadQtProject command.
	public static int LoadQtProjectBitmapID = 4 ;
	public static string 
	    LoadQtProject		= "LoadQtProject",
	    LoadQtProjectButtonText	= "Load a Qt Project ",
	    LoadQtProjectToolTip	= "This will load a project generated by the Qt Designer",
	    LoadQtProjectFullCommand	= "QMsNet.LoadQtProject";

	// All the constants for the SaveQtProject command.
	public static int SaveQtProjectBitmapID = 5 ;
	public static string 
	    SaveQtProject		= "SaveQtProject",
	    SaveQtProjectButtonText	= "Save a Qt Project ",
	    SaveQtProjectToolTip	= "This will Save a project which can be edited in Qt Designer",
	    SaveQtProjectFullCommand	= "QMsNet.SaveQtProject";

	// All the constants for the LoadQtProject command.
	public static int DLLQtProjectBitmapID = 6 ;
	public static string 
	    DLLQtProject		= "DLLProject",
	    DLLQtProjectButtonText	= "DLLify project",
	    DLLQtProjectToolTip		= "This will turn the current Qt App project into a DLL project",
	    DLLQtProjectFullCommand	= "QMsNet.DLLProject";

	// All the constants for the MocQtProject command.
	public static int AddMocStepBitmapID = 7 ;
	public static string 
	    AddMocStep			= "MocFile",
	    AddMocStepButtonText	= "Moc a Qt Project",
	    AddMocStepToolTip		= "This will add a Moc step for the current file",
	    AddMocStepFullCommand	= "QMsNet.MocFile";

	// All the constants for the Monitor Events command.
	public static string 
	    mntEvents			= "MonitorEvents",
	    mntEventsButtonText		= "Monitor Events",
	    mntEventsToolTip		= "This will start event monitoring",
	    mntEventsFullCommand	= "QMsNet.MonitorEvents";

	// All the constants for the Stop Monitor Events command.
	public static string 
	    unmntEvents			= "StopMonitoringEvents",
	    unmntEventsButtonText	= "Stop Monitor Events",
	    unmntEventsToolTip		= "This will stop event monitoring",
	    unmntEventsFullCommand	= "QMsNet.StopMonitoringEvents";
    }
}
