#############################################################################
# $Id: makeqtmake,v 1.3 1996/01/22 13:46:00 hanord Exp $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = fileinfo

!INCLUDE $(QTDIR)\Makefile.inc
