#############################################################################
# $Id: makeqtmake.bat,v 1.2 1998/02/26 09:37:12 hanord Exp  Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = glpixmap

include $(QTDIR)/GNUmakefile.inc
