#############################################################################
# $Id: //depot/qt/main/tutorial/t14/Makefile#19 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = t14

!INCLUDE $(QTDIR)\Makefile.inc
