#############################################################################
# $Id: //depot/qt/main/examples/buttons_groups/GNUmakefile#1 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = buttons_groups

include $(QTDIR)/GNUmakefile.inc
