#############################################################################
# $Id: //depot/qt/main/tutorial/t12/Makefile#18 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = t12

!INCLUDE $(QTDIR)\Makefile.inc
