#############################################################################
# $Id: makeqtmake,v 1.2 1998/02/26 09:36:21 hanord Exp  Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = t12

!INCLUDE $(QTDIR)\Makefile.inc
