#############################################################################
#!
#! This is a tmake template for creating a makefile that invokes make in
#! sub directories - for Unix.
#!
#$ StdInit();
#!
# Makefile for building targets in sub directories.
# Generated by tmake at #$ Now();
#     Project: #$ Expand("PROJECT");
#    Template: #$ Expand("TEMPLATE");
#############################################################################

SUBDIRS =	#$ ExpandList("SUBDIRS");

all: $(SUBDIRS)

$(SUBDIRS): FORCE
	if [ -d $$i ]; then cd $$i ; $(MAKE); fi

clean:
	for i in $(SUBDIRS); do ( if [ -d $$i ]; then cd $$i ; $(MAKE) $@; fi; ) ; done

FORCE:
