SOURCES	+= main.cpp 
TARGET	= richedit
INTERFACES	= richedit.ui 
TEMPLATE	=app
CONFIG	+= qt warn_on release
DBFILE	= richedit.db
IMAGEFILE	= images.cpp
PROJECTNAME	= richedit
LANGUAGE	= C++
{SOURCES+=images.cpp}
