#############################################################################
# $Id: //depot/qt/2.1/util/scripts/makeqtmake.bat#1  Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = guithreads

include $(QTDIR)/GNUmakefile.inc
