#############################################################################
# $Id: //depot/qt/2.1/util/scripts/makeqtmake.bat#1  Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = guithreads

!INCLUDE $(QTDIR)\Makefile.inc
