#############################################################################
# $Id: //depot/qt/main/examples/listviews/Makefile#2 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = listviews

!INCLUDE $(QTDIR)\Makefile.inc
