##############################################################
# Automatically generated by qmake Thu Jun 21 17:15:54 2001
##############################################################

TEMPLATE += app
TARGET += changelists

# Input
HEADERS += mainform.h
INTERFACES += mainformbase.ui
SOURCES += main.cpp mainform.cpp
