#############################################################################
# $Id: //depot/qt/main/tutorial/t7/Makefile#18 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = t7

!INCLUDE $(QTDIR)\Makefile.inc
