.TH lrelease 1 "17 May 2001" "Trolltech AS" \" -*- nroff -*-
.\"
.\" Copyright 2001 Trolltech AS.  All rights reserved.
.\"
.\" This file is part of Qt and may be distributed and used according to
.\" the terms and conditions described in the LICENSE file.
.\"
.SH NAME
lrelease \- generate Qt message files from Qt Linguist translation files
.SH SYNOPSIS
.B lrelease
[options] project-file
.SH DESCRIPTION
This page documents the
.B Qt Linguist Release
tool for the Qt GUI application framework.
.B Lrelease
reads a tmake/qmake project file (.pro file) and converts the
translation files (.ts files) specified in it into Qt message files
(.qm files) used by the application to translate.
.PP
The .qm file format is a compact binary format that provides
extremely fast lookups for translations and that is used by Qt.
.SH OPTIONS
.TP
.I "-help"
Displays the usage and exits.
.TP
.I "-verbose"
Explains what is being done.
.TP
.I "-version"
Displays the version of
.B lrelease
and exits.
.SH USAGE
Here is an example .pro file that can be given to
.B lrelease:
.PP
.in +4
.nf
HEADERS         = funnydialog.h \\
                  wackywidget.h
SOURCES         = funnydialog.cpp \\
                  main.cpp \\
                  wackywidget.cpp
FORMS           = fancybox.ui
TRANSLATIONS    = gnomovision_dk.ts \\
                  gnomovision_fi.ts \\
                  gnomovision_no.ts \\
                  gnomovision_se.ts
.fi
.in -4
.PP
When running
.B lrelease
on this project file, the Qt message files gnomovision_dk.qm,
gnomovision_fi.qm, gnomovision_no.qm and gnomovision_se.qm will be
generated from gnomovision_dk.ts, gnomovision_fi.ts,
gnomovision_no.ts and gnomovision_se.ts, respectively.
.SH "SEE ALSO"
.BR lupdate (1)
and
.BR http://doc.trolltech.com/i18n.html
.SH AUTHOR
Jasmin Blanchette, Trolltech AS <jasmin@trolltech.com>
