#############################################################################
# $Id: //depot/qt/2.1/examples/iconview/Makefile#1 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = iconview

!INCLUDE $(QTDIR)\Makefile.inc
