#!/usr/bin/perl

############################################################################
#
# A very simple, non-robust cgi-bin program that prints the bytes in/out
# per second, each second, forever.
#
# Only tested with our Trolltech Australia office connection.
#

$channels = 4;

#
############################################################################

$MAX_CHANNELS = 64;

use IO::Handle;
STDOUT->autoflush(1);

print "Content-type: text/plain\n\n";


open ISDNINFO, "/dev/isdninfo";

sub IIOCGETCPS() { 0x4915; }

$getcps = &IIOCGETCPS;

$iobytes_t = "ll"; # 2 longs
$iobytes=$iobytes_t x (4 * $MAX_CHANNELS);


($period) = $ENV{"QUERY_STRING"} =~ /period=(\d+)/;
$period = 1 if $period < 1;

while (1) {
    if (ioctl(ISDNINFO,$getcps,$iobytes)) {
	@io = unpack($iobytes_t x $channels, $iobytes);

	$ni=$no=0;

	while (@io) {
	    $ni += shift @io;
	    $no += shift @io;
	}

	if ( defined($i) ) {
	    $cpsi = int(($ni - $i)/$period);
	    $cpso = int(($no - $o)/$period);

	    print "$cpsi $cpso\n";
	}
	$i = $ni;
	$o = $no;

    } else {
	die "/dev/isdninfo: no CPS";
    }
    sleep $period;
}
