#############################################################################
# $Id: //depot/qt/main/tutorial/t6/GNUmakefile#5 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = t6

include $(QTDIR)/GNUmakefile.inc
