#############################################################################
# $Id: //depot/qt/main/tutorial/t6/GNUmakefile#3 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = t6

include $(QTDIR)/GNUmakefile.inc
