/* XPM */
const char *widgeticon[] = {
/* columns rows colors chars-per-pixel */
"48 48 32 1",
"  c #cebaa2",
". c #dec8ad",
"X c #878686",
"o c #72706e",
"O c #b9b9b9",
"+ c #c5c4c4",
"@ c #998a78",
"# c #a4a4a4",
"$ c Gray84",
"% c #544e48",
"& c #b6a48e",
"* c Gray98",
"= c #e6e6e6",
"- c #9a9a99",
"; c #312e29",
": c #a89783",
"> c #867969",
", c #71675c",
"< c #080706",
"1 c #49443e",
"2 c #615c56",
"3 c #3d3933",
"4 c #211f1c",
"5 c #cecdcc",
"6 c #aeaeaf",
"7 c #c1af98",
"8 c #7f7f7e",
"9 c #8e8e8e",
"0 c Gray87",
"q c #dcd5ce",
"w c #f1f0f0",
"e c None",
/* pixels */
"eeeeeeeeee*w=5O-8,1;443=eeeeeeeeeeeeeeeeeeeeeeee",
"eee*w$O-8o2%33;;;;;;;4<2*eeeeeeeeeeeeeeeeeeeeeee",
"wO9o%33;;33333331%%2,oo2+eeeeeeeeeeeeeeeeeeeeeee",
"6o2%%1111%%289#O+5555++0+*eeeeeeeeeeeeeeeeeeeeee",
"+6ooo9#O+5$$5O#-9X8ooo2O$=eeeeeeeeeeeeeeeeeeeeee",
"+55==$+O#9Xooo888XXXXXo#==eeeeeeeeeeeeeeeeeeeeee",
"+wwO988XX99999XXXX8888o#==eeeeeeeeeeeeeeeeeeeeee",
"5w5O#--9999XXXXXX88888o60=eeeeeeeeeeeeeeeeeeeeee",
"5w+#99999XXXX9XX8X8888o60=eeeeeeeeeeeeeeeeeeeeee",
"5=O#999XXXX98%8X888888oO=*eeeeeeeeeeeeeeeeeeeeee",
"5=O-99999XXo;4XXX8888ooO=*eeeeeeeeeeeeeeeeeeeeee",
"5=O-999XXXX1%;XXXXX888oO0*eeeeeeeeeeeeeeeeeeeeee",
"5=O-99XXXXX9,;8%331o88o+$*eeeeeeeeeeeeeeeeeeeeee",
"5=O-9X9XXXXX2434<<<<42o5=*eeeeeeeeeeeeeeeeeeeeee",
"5=+-99XXXXXX21%134<<<42$0*eeeeeeeeeeeeeeeeeeeeee",
"$=+99XXXXXX88>,%%;4<<<<%12o+eeeeeeeeeeeeeeeeeeee",
"$=+9XXXXXX8X8X@>,%;4333;;4<45eeeeeeeeeeeeeeeeeee",
"00+9XXXXX8X88>:&@>,>>>>,21;<<oweeeeeeeeeeeeeeeee",
"$05XXXXX8XXX9X@77::::::@>2%34<1=eeeeeeeeeeeeeeee",
"0059999--##666#:  &&7&7:@>,21;<;0eeeeeeeeeeeeeee",
"00$O6OOOOOOO666#&7&&7777&:>,%13<4Oeeeeeeeeeeeeee",
"0$$55++OOOOOOO66#::@:&7  &@>,%134<9*eeeeeee=682o",
"=$5$5+++OOOO6##66#->8@:  7&:>,%1;<<36*eeee#13;;<",
"=$5$0++OOOO#%1386666#-X&. 7&@,%1;4<<<;o$wX31%%33",
"w$+5=++OOOOo16o166###-8@ . 7:>2%3;44<<<;%;11%%13",
"w$++w5+OOOO2oO#3-6###-8-    &@>>>2214444;3311%%1",
"*55Ow++OOOO22O6186###-XX5   7&:::>,%3;;;;;333111",
"*556*5+OOOOo2O6186####98$w7  77  7@>%;;;;;;33111",
"*55-w5+OOOO836#396####98$eq&  ... &@,1;;33;33331",
"*$$9w5+OOOO611%26####--80e*+7.... &@>,%113333333",
"e$$X=$OOOOOO6X966#####-X*eew7 ... &:@>,2%1133333",
"e=$85$OOOOO66O66###---9Oeeee5 ... 7:@>,,2%%11333",
"e*=-O0+OOOO66##---#O50weeeee0 ... 7&:@>,,,2%1333",
"eew05=666###6O5$=w*eeeeeeeeew7...  &:@>>>,,22%13",
"ee*w=$O+50=**eeeeeeeeeeeeeee*  ... 7&::>>,,,22%1",
"eeeee*eeeeeeeeeeeeeeeeeeeeeee57...  7&:@>>>,,22%",
"eeeeeeeeeeeeeeeeeeeeeeeeeeeeew7.... 7&&:@@>>,,22",
"eeeeeeeeeeeeeeeeeeeeeeeeeeeeee5 ...  7&&:@@>>,,,",
"eeeeeeeeeeeeeeeeeeeeeeeeeeeeee= ....  7&&:@@>>,,",
"eeeeeeeeeeeeeeeeeeeeeeeeeeeeee*  ...  77&::@@>>>",
"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee57....  7&&::@@>>",
"eeeeeeeeeeeeeeeeeeeeeeeeeeeeee*O: ....  7&&::@@>",
"eeeeeeeeeeeeeeeeeeeeeeeeeeee=-24, ..... 77&&::@@",
"eeeeeeeeeeeeeeeeeeeeeeeeeeeO2;44;&.....  77&&::@",
"eeeeeeeeeeeeeeeeeeeeeeeeee+>,14<<> ...... 77&&::",
"eeeeeeeeeeeeeeeeeeeeeeeeew@@>%4<<37......  77&&:",
"eeeeeeeeeeeeeeeeeeeeeeeeeO:&:,3<<<@..q..... 77&&",
"eeeeeeeeeeeeeeeeeeeeeeee*777:>%4<<2....q...  77&"
};

/* XPM */
const char *dbicon[] = {
/* columns rows colors chars-per-pixel */
"48 48 256 2",
"   c Gray100",
".  c #181818",
"X  c Gray13",
"o  c Gray16",
"O  c #313131",
"+  c #393939",
"@  c Gray26",
"#  c Gray29",
"$  c Gray32",
"%  c #5a5a5a",
"&  c Gray39",
"*  c Gray42",
"=  c Gray45",
"-  c #7b7b7b",
";  c #848484",
":  c Gray55",
">  c Gray58",
",  c Gray61",
"<  c #a5a5a5",
"1  c Gray68",
"2  c Gray71",
"3  c Gray74",
"4  c #c6c6c6",
"5  c #cecece",
"6  c Gray84",
"7  c Gray87",
"8  c #cec6c6",
"9  c #d6cece",
"0  c #bdb5b5",
"q  c #ada5a5",
"w  c #b5adad",
"e  c #c6bdbd",
"r  c #948c8c",
"t  c #9c9494",
"y  c #a59c9c",
"u  c #8c8484",
"i  c #7b7373",
"p  c #736b6b",
"a  c #847b7b",
"s  c #6b6363",
"d  c #5a5252",
"f  c #635a5a",
"g  c #736b63",
"h  c #cecec6",
"j  c #bdbdb5",
"k  c #adada5",
"l  c #b5b5ad",
"z  c #c6c6bd",
"x  c #94948c",
"c  c #9c9c94",
"v  c #a5a59c",
"b  c #8c8c84",
"n  c #7b7b73",
"m  c #73736b",
"M  c #84847b",
"N  c #6b6b63",
"B  c #5a5a52",
"V  c #63635a",
"C  c #4a4a42",
"Z  c #c6cec6",
"A  c #ced6ce",
"S  c #b5bdb5",
"D  c #a5ada5",
"F  c #adb5ad",
"G  c #bdc6bd",
"H  c #8c948c",
"J  c #949c94",
"K  c #9ca59c",
"L  c #737b73",
"P  c #7b847b",
"I  c #636b63",
"U  c #c6cece",
"Y  c #ced6d6",
"T  c #b5bdbd",
"R  c #a5adad",
"E  c #adb5b5",
"W  c #bdc6c6",
"Q  c #8c9494",
"!  c #949c9c",
"~  c #9ca5a5",
"^  c #848c8c",
"/  c #737b7b",
"(  c #6b7373",
")  c #7b8484",
"_  c #636b6b",
"`  c #9cadad",
"'  c #94a5a5",
"]  c #849494",
"[  c #7b8c8c",
"{  c #637373",
"}  c #9cb5b5",
"|  c #94adad",
" . c #7b9494",
".. c #9cbdbd",
"X. c #94b5b5",
"o. c #8cadad",
"O. c #9cc6c6",
"+. c #94b5bd",
"@. c #9cbdc6",
"#. c #9cb5bd",
"$. c #94adb5",
"%. c #8ca5ad",
"&. c #94a5ad",
"*. c #7b8c94",
"=. c #84949c",
"-. c #bdc6ce",
";. c #7b848c",
":. c #6b737b",
">. c #636b73",
",. c #424a52",
"<. c #949ca5",
"1. c #9c9ca5",
"2. c #73737b",
"3. c #6b6b73",
"4. c #292931",
"5. c #bdb5bd",
"6. c #ada5ad",
"7. c #b5adb5",
"8. c #9c949c",
"9. c Gray0",
"0. c Gray0",
"q. c Gray0",
"w. c Gray0",
"e. c Gray0",
"r. c Gray0",
"t. c Gray0",
"y. c Gray0",
"u. c Gray0",
"i. c Gray0",
"p. c Gray0",
"a. c Gray0",
"s. c Gray0",
"d. c Gray0",
"f. c Gray0",
"g. c Gray0",
"h. c Gray0",
"j. c Gray0",
"k. c Gray0",
"l. c Gray0",
"z. c Gray0",
"x. c Gray0",
"c. c Gray0",
"v. c Gray0",
"b. c Gray0",
"n. c Gray0",
"m. c Gray0",
"M. c Gray0",
"N. c Gray0",
"B. c Gray0",
"V. c Gray0",
"C. c Gray0",
"Z. c Gray0",
"A. c Gray0",
"S. c Gray0",
"D. c Gray0",
"F. c Gray0",
"G. c Gray0",
"H. c Gray0",
"J. c Gray0",
"K. c Gray0",
"L. c Gray0",
"P. c Gray0",
"I. c Gray0",
"U. c Gray0",
"Y. c Gray0",
"T. c Gray0",
"R. c Gray0",
"E. c Gray0",
"W. c Gray0",
"Q. c Gray0",
"!. c Gray0",
"~. c Gray0",
"^. c Gray0",
"/. c Gray0",
"(. c Gray0",
"). c Gray0",
"_. c Gray0",
"`. c Gray0",
"'. c Gray0",
"]. c Gray0",
"[. c Gray0",
"{. c Gray0",
"}. c Gray0",
"|. c Gray0",
" X c Gray0",
".X c Gray0",
"XX c Gray0",
"oX c Gray0",
"OX c Gray0",
"+X c Gray0",
"@X c Gray0",
"#X c Gray0",
"$X c Gray0",
"%X c Gray0",
"&X c Gray0",
"*X c Gray0",
"=X c Gray0",
"-X c Gray0",
";X c Gray0",
":X c Gray0",
">X c Gray0",
",X c Gray0",
"<X c Gray0",
"1X c Gray0",
"2X c Gray0",
"3X c Gray0",
"4X c Gray0",
"5X c Gray0",
"6X c Gray0",
"7X c Gray0",
"8X c Gray0",
"9X c Gray0",
"0X c Gray0",
"qX c Gray0",
"wX c Gray0",
"eX c Gray0",
"rX c Gray0",
"tX c Gray0",
"yX c Gray0",
"uX c Gray0",
"iX c Gray0",
"pX c Gray0",
"aX c Gray0",
"sX c Gray0",
"dX c Gray0",
"fX c Gray0",
"gX c Gray0",
"hX c Gray0",
"jX c Gray0",
"kX c Gray0",
"lX c Gray0",
"zX c Gray0",
"xX c Gray0",
"cX c Gray0",
"vX c Gray0",
"bX c Gray0",
"nX c Gray0",
"mX c Gray0",
"MX c Gray0",
"NX c Gray0",
"BX c Gray0",
"VX c Gray0",
"CX c Gray0",
"ZX c Gray0",
"AX c Gray0",
"SX c Gray0",
"DX c Gray0",
"FX c Gray0",
"GX c Gray0",
"HX c Gray0",
"JX c Gray0",
"KX c Gray0",
"LX c Gray0",
"PX c Gray0",
"IX c Gray0",
"UX c None",
/* pixels */
"UXUXUXUXUXUXUXUXUXUX4 3 3 3 2 2 , : , : - = = * * * - ; ; , 1 , 1 3 2 4 3 4 UXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUX4 2 1 > ; * $ # # # # # @ # # $ $ $ % % % % % $ $ % % % % & & ; > < 3 3 4 UXUXUXUXUX",
"UXUXUX4 3 : % + O O O O + + @ @ @ # # # # $ $ $ % % & & & & % % % % % % $ $ $ $ $ & ; 1 4 4 UXUX",
"UXUX4 - o X X o o o o O O O + + + @ @ # # $ $ $ % & & & % % % % % % $ $ $ $ $ $ $ # # # % 2 UXUX",
"UX5 @ . X X X X X X X X X o X o o o o O O + @ $ % % % $ $ $ $ $ # # # # # @ @ @ @ @ @ + + + 2 UX",
"UX, . O o O O O O O O O O O O O O + + + + @ # $ $ @ + O O o o o o o o o o o o o o o o o o X $ UX",
"UX1 + + @ + @ @ @ @ # # # # $ $ $ $ % % % & & & % $ # @ + + O o o o X X X X X X X X X X X . = UX",
"UX4 M $ # # # # $ $ $ $ $ % % % % % % & & * & & % $ $ # # @ @ @ + + O O O o o o X X . . o # 1 UX",
"UX4 q , M * % % $ $ % % % % % % & & & & * & & % % $ $ $ # # # @ @ @ @ + + + O O O O $ { [ > l UX",
"UX4 v < y 1 y x a - * & % % & & & & * * & * & & % % $ $ $ $ # # # @ @ @ @ # $ B & <.O.#.! Q 1 UX",
"UX4 < y , k < 1 < j 1 q 8.- = = m * * * * & & % % $ % $ $ $ $ $ $ B % & N i n - - %.O.$.! Q l UX",
"UX4 v v t < v q < 2 w 2 2 t t r : a * s g s f f s & & * L i * N p p * p = i - n - %.@.$.! x 7.UX",
"UX5 y , c < y q y 2 1 w 1 > > r > a * s p s V f & s & m - n * s * p N * * = i n - %.@.| ! > 1 UX",
"UXh v y > < v < < 2 w E w > t r > a * s g s f f & s & = a i * N * m N * p = n - - %.@.$.' > < UX",
"UX4 v , t v y q y 2 1 w 1 t > : > a * N g s f V & s s m - n p * p p s * * = i n - %.@.| ' > l UX",
"UX5 y , t < y q < 2 1 1 w t > r > a * s p s f f s * & = a i m * m m s * N = n a / %.@.| ~ > 2 UX",
"UX5 v c t K y < y 2 w w 1 > r r > a N g g s V f s N * = P n = m = * s * * = n - / &.@.| ~ > S UX",
"UX9 , c t , y < v 2 1 1 w t > : > a * s p s f V s * N = a n = m = p & N * = - n / %.@.| ~ J w UX",
"UX6 y c > y , q < w w 1 2 > r r > a * g g s f f s * * = M i = = n p & * N m - a 2.| @.&.~ ! l UX",
"UX5 v t > , c < y 2 1 1 w t x : t a * N g s f V * * * i M n i L - * & N N i - n 2.%.@.| < , 2 UX",
"UX3 y > x y , v y 2 k 1 w > r : t a N g p s f f N p p L M - n n - p V s * = - - 2.| @.&.D ! l UX",
"UX4 v t > c y < v w 1 k w t r : t a * g g s V f * * p n M i - n - * f * s m a n = $...&.R t 2 UX",
"UX4 v > r c t < y l 1 6.l t r : , a s p g s f f N = p - ; n n - M p % N N = P - = %.@.' R J 3 UX",
"UX4 v > x , c < y 1 1 k w t r b 8.a * g g N f V * = m n M - M M ; * % * s = M - ( $...&.R t 3 UX",
"UX4 < r r t c < y l 1 q l > r : t a N p g s f V p = m - ; n ; ; ; p % s N = a n ( $.#.' R c 3 UX",
"UX4 v x > t t v y 1 1 k w t r u 8.a * p p s f V p = = n M a b b b p % * s = ; n 3.$.+.&.1 > 3 UX",
"UX4 q r r > t < v 1 w < l > r b , a * g p s V s * i = - M a H x : = f N s = P - ( | #.' 1 J 4 UX",
"UXh < x r > t v y 1 1 q w t r u 8.a g p p s f & m i = - a M > J : = f * s m ; n 3.$.+.' 1 > 4 UX",
"UX4 v r r > t v y 1 1 q F t : u t a * p p V f N = = = n M a J , x = V I s = ) = ( $.#.' 1 ! z UX",
"UX5 < r x x > y y 1 k q w > r u , a * m p s V s = n i - - ; K < > i & N & = ; = 3.$.X.' 1 J 8 UX",
"UX5 v r r > x < y k 1 < w t : u t a p p p & f N = - n - a ; < D t - & N & = ) L 3.$.X.' F , 3 UX",
"UX5 < r x r > v , 6.1 q F t : u 8.a * m m & f * = - n - n ; 1 F , n & N & = ) = 3.$.$.' 1 c 3 UX",
"UX9 v : r > x y y k q v w t b u > a * m p s V * = - n - n b F 2 , - & N & = ) = ( $.X.1.E > 5 UX",
"UX4 q r r > r v , q 1 < w > : u t a p i m & f * i a - - - b T 3 y a & _ & ( ) = >.$.$.! E c 8 UX",
"UX3 k : r x r y v < 6.v w t u u > a p m m & & * = - n - i b T G K ; & N & = ) = * $.X.! 7.J h UX",
"UXW k r r > x , , q 1 v w > : u t a p p i V & p L a - - n H 3 W y a * * N ( ) = >.$.| ~ E , 2 UX",
"UX4 1 : r r r y v < k y 1 t u u > a * m p & & m = - n - - > G z , M * = * / ) = >.X.| 1.F y 0 UX",
"UX4 w : r x : , y < 6.v w c u u > a * m p & & = = - n - - > W 4 , a * L = / ) ( >.$.| , E K 3 UX",
"UXe 1 r : r r y , v 1 y 1 8.u u > a p p p & s = m - n - - c W 4 , M = - - / ;.= >.$.| ! 2 , j UX",
"UXW w : r r : , v < q , w c u u r - p m p & N = = i n - - , Z 4 y - = ; P ) [ ( >.X.| 1.2 , 3 UX",
"UX4 1 b : r : , y y 1 y 1 , u ; > a p p p & * = = n - - a K U 4 , P / ; ; [ [ = >.} ' K E , z UX",
"UX4 2 b : : b , v < q , w 8.u u x - * p p & * i m i n - - v U Z , a - : : [ [ ( >.$.&.~ 2 , U UX",
"UXUX5 u u : u , y , k y 1 , M ; > i p p * & * i = i n - M D 5 4 , M - Q x ^ *.( >.} ' , F l 8 UX",
"UXUX4 e > u u 8.v y 6., 1 8.u u r i p p * & * - m i n - - D A h , a ) J > ] ] ( >.X.' 1.4 5 UXUX",
"UXUXUXUX4 q ; t y , k y 6., M ; r i p p * f = n p = n - M F Y 4 , a ; , , ]  .3._ $.` Z W UXUXUX",
"UXUXUXUXUX4 e 3 < y < t k , u a r - * p * & = - m i n - M 1 6 Z c - ; K K =. .:.Q -.5 3 UXUXUXUX",
"UXUXUXUXUXUXUXUX4 4 4 2 0 < a ; r p s p s & = - m = i = M k A 4 , M : E 2 T Z 3 4 UXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXe 4 e 4 e 0 2 y : : : > > : x t , c 3 7 5 4 3 W 4 4 UXUXUXUXUXUXUXUXUXUXUX"
};

/* XPM */
const char *texticon[] = {
/* columns rows colors chars-per-pixel */
"48 48 256 2",
"   c Gray100",
".  c Gray3",
"X  c #101010",
"o  c #181818",
"O  c Gray13",
"+  c Gray16",
"@  c #313131",
"#  c #393939",
"$  c Gray26",
"%  c Gray29",
"&  c Gray32",
"*  c #5a5a5a",
"=  c Gray39",
"-  c Gray42",
";  c Gray45",
":  c #7b7b7b",
">  c #848484",
",  c Gray55",
"<  c Gray58",
"1  c Gray61",
"2  c #a5a5a5",
"3  c Gray68",
"4  c Gray71",
"5  c Gray74",
"6  c #c6c6c6",
"7  c #bdb5b5",
"8  c #ada5a5",
"9  c #c6bdbd",
"0  c #948c8c",
"q  c #9c9494",
"w  c #a59c9c",
"e  c #736b6b",
"r  c #423939",
"t  c #393131",
"y  c #312929",
"u  c #292121",
"i  c #211818",
"p  c #181010",
"a  c #947b73",
"s  c #84736b",
"d  c #6b5a52",
"f  c #bdada5",
"g  c #7b6b63",
"h  c #5a4a42",
"j  c #b5a59c",
"k  c #73635a",
"l  c #ceb5a5",
"z  c #b59c8c",
"x  c #c6ad9c",
"c  c #bda594",
"v  c #9c8473",
"b  c #c6bdb5",
"n  c #c6b5a5",
"m  c #635a52",
"M  c #ad9c8c",
"N  c #a59484",
"B  c #8c7b6b",
"V  c #847363",
"C  c #423931",
"Z  c #bdb5ad",
"A  c #9c948c",
"S  c #736b63",
"D  c #bdad9c",
"F  c #5a524a",
"G  c #b5a594",
"H  c #524a42",
"J  c #9c8c7b",
"K  c #948473",
"L  c #ceb59c",
"P  c #c6ad94",
"I  c #bda58c",
"U  c #7b6b5a",
"Y  c #393129",
"T  c #736352",
"R  c #312921",
"E  c #ada59c",
"W  c #6b635a",
"Q  c #4a4239",
"!  c #cebda5",
"~  c #ad9c84",
"^  c #c6b59c",
"/  c #a5947b",
"(  c #bdad94",
")  c #b5a58c",
"_  c #9c8c73",
"`  c #94846b",
"'  c #847b6b",
"]  c #635a4a",
"[  c #7b7363",
"{  c #cebd9c",
"}  c #5a5242",
"|  c #ada594",
" . c #948c7b",
".. c #8c8473",
"X. c #736b5a",
"o. c #6b6352",
"O. c #524a39",
"+. c #4a4231",
"@. c #a59c84",
"#. c #ada58c",
"$. c #9c947b",
"%. c #948c73",
"&. c #bdbdb5",
"*. c #b5b5ad",
"=. c #c6c6bd",
"-. c #94948c",
";. c #a5a59c",
":. c #7b7b73",
">. c #52524a",
",. c #4a4a42",
"<. c #424239",
"1. c #393931",
"2. c #737363",
"3. c #313129",
"4. c #636352",
"5. c #292921",
"6. c #4a4a39",
"7. c #424231",
"8. c #212118",
"9. c #313121",
"0. c #181810",
"q. c #101008",
"w. c #73845a",
"e. c #6b7363",
"r. c #081000",
"t. c #425239",
"y. c #102908",
"u. c #316b21",
"i. c #297321",
"p. c #297b21",
"a. c #085200",
"s. c #b5bdb5",
"d. c #a5ada5",
"f. c #bdc6bd",
"g. c #9ca59c",
"h. c #636b63",
"j. c #5a635a",
"k. c #293129",
"l. c #7b947b",
"z. c #212921",
"x. c #182118",
"c. c #101810",
"v. c #103910",
"b. c #003900",
"n. c #005200",
"m. c #006b00",
"M. c #007b00",
"N. c #182121",
"B. c #101818",
"V. c #100810",
"C. c Gray0",
"Z. c Gray0",
"A. c Gray0",
"S. c Gray0",
"D. c Gray0",
"F. c Gray0",
"G. c Gray0",
"H. c Gray0",
"J. c Gray0",
"K. c Gray0",
"L. c Gray0",
"P. c Gray0",
"I. c Gray0",
"U. c Gray0",
"Y. c Gray0",
"T. c Gray0",
"R. c Gray0",
"E. c Gray0",
"W. c Gray0",
"Q. c Gray0",
"!. c Gray0",
"~. c Gray0",
"^. c Gray0",
"/. c Gray0",
"(. c Gray0",
"). c Gray0",
"_. c Gray0",
"`. c Gray0",
"'. c Gray0",
"]. c Gray0",
"[. c Gray0",
"{. c Gray0",
"}. c Gray0",
"|. c Gray0",
" X c Gray0",
".X c Gray0",
"XX c Gray0",
"oX c Gray0",
"OX c Gray0",
"+X c Gray0",
"@X c Gray0",
"#X c Gray0",
"$X c Gray0",
"%X c Gray0",
"&X c Gray0",
"*X c Gray0",
"=X c Gray0",
"-X c Gray0",
";X c Gray0",
":X c Gray0",
">X c Gray0",
",X c Gray0",
"<X c Gray0",
"1X c Gray0",
"2X c Gray0",
"3X c Gray0",
"4X c Gray0",
"5X c Gray0",
"6X c Gray0",
"7X c Gray0",
"8X c Gray0",
"9X c Gray0",
"0X c Gray0",
"qX c Gray0",
"wX c Gray0",
"eX c Gray0",
"rX c Gray0",
"tX c Gray0",
"yX c Gray0",
"uX c Gray0",
"iX c Gray0",
"pX c Gray0",
"aX c Gray0",
"sX c Gray0",
"dX c Gray0",
"fX c Gray0",
"gX c Gray0",
"hX c Gray0",
"jX c Gray0",
"kX c Gray0",
"lX c Gray0",
"zX c Gray0",
"xX c Gray0",
"cX c Gray0",
"vX c Gray0",
"bX c Gray0",
"nX c Gray0",
"mX c Gray0",
"MX c Gray0",
"NX c Gray0",
"BX c Gray0",
"VX c Gray0",
"CX c Gray0",
"ZX c Gray0",
"AX c Gray0",
"SX c Gray0",
"DX c Gray0",
"FX c Gray0",
"GX c Gray0",
"HX c Gray0",
"JX c Gray0",
"KX c Gray0",
"LX c Gray0",
"PX c Gray0",
"IX c Gray0",
"UX c None",
/* pixels */
"UXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUX",
": O + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + @ 4 UXUXUXUXUXUXUXUXUXUX",
"& * 5 4 5 4 5 5 5 5 5 5 5 5 5 5 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 2 X 3 UXUXUXUXUXUXUXUXUXUX",
"& - UXUXUXUXUX4 3 2 2 2 2 2 2 4 UXUXUXUXUX4 2 2 2 2 2 2 3 4 UXUXUXUXUX3 o 2 UXUXUXUXUXUXUXUXUXUX",
"% ; UXUX3 = # $ $ % % % % % $ @ 4 UXUXUX5 @ # % % % % % $ $ $ * 3 UXUX4 o 2 UXUXUXUXUXUXUXUXUXUX",
"# : UX2 O # 2 4 5 5 5 5 5 5 4 O 3 UXUXUX4 O < 5 5 5 5 5 5 5 2 * + < UX4 o 1 UXUXUXUXUXUXUXUXUXUX",
"@ > 3 o - UXUXUXUXUXUXUXUXUX5 + 4 UXUXUX5 O < UXUXUXUXUXUXUXUXUX, o < 6 O 1 UXUXUXUXUXUXUXUXUXUX",
"+ < & # UXUXUXUXUXUXUXUXUX6 8 <.1 &.5 UXUXO < UXUXUXUXUXUXUXUXUXUX, + 3 O < UXUXUXUXUXUXUXUXUXUX",
"O : O 3 UXUXUXUXUXUX5 ;.0 s S ../ ..s E 8 + 2 UXUXUXUXUXUXUXUXUXUXUX@ = # , UXUXUXUXUXUXUXUXUXUX",
"O $ $ UXUXUXUXUXf.4 e H Q <.} B J N J B V X.q 5 6 UXUXUXUXUXUXUXUXUX; # # , UXUXUXUXUXUXUXUXUXUX",
"o O = UXUXUXs.l.e.m Q Y R u o H ' J ~ ~ %.B B ' A 7 5 UXUXUXUXUXUXUX2 + @ > UXUXUXUXUXUXUXUXUXUX",
"o @ & , 2 3 t.3.C +.1.0.8.O 8.5.} V J ~ N K V V B / M E 7 UXUXUXUXUX5 + X > UXUXUXUXUXUXUXUXUXUX",
", , % x.z.O V.i R O 8.C 2 5 3 + 8.H V %._ K %.$.~ G ( ) ~ &.UXUXUXUXUX< > 4 UXUXUXUXUXUXUXUXUXUX",
"UXUX5 ; o o y.a.u.d h k *.UX6 @ * 8.H X.s %.c P x ( ( x ( ( 7 UXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUX6 3 , v.m.M.w.K H ; 2 3 @ 4 > i O.k ..G ^ ^ P ( P P ^ I 7 6 UXUXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUX> b.M.p.K K @ 3.% # 1 6 ; Y d ' z ^ P x ( ( ( P ^ I *.5 UXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUX5 k.n.i.V z W z.+ 3.@ h.j.Y ] B ) ^ ^ ( ( P ( x P P ) &.UXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUX< . ] X._ ) q h.3.3.O O k.<.m J l ! ^ P ( P ( ^ x I j 6 UXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUX6 & Q k ' z &.6 @ : e.@ + O + 1.m ..) ^ ^ ^ x P ^ P I &.UXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUX3 R ] V M n 3 @ 5 5 4 3.+ z.x.o N.@ m K ) P ^ L x P D 5 UXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUX6 & C [ ) L | # 5 UX5 t 8.F F t 8.B.B.O @ >.B ( L L ( Z UXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUX4 3.] K ( l N ;.5 1 0.q.H X.' ' o.<.x.B.o O 1.4...) P 5 UXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUX< 8.] B ~ ^ ( E F u o O.d [ J D ^ J F 3.x.B.o O @ m  .5 UXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUX6 > 5.H g J ( ( J g ] h ] X.' N ( ! ! (  .] 5.o o x.O & 1 6 UXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUX1 5.H X.K G x %.o.] d o.U K M D ^ l l L M V <.x.o & ; 5 UXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUX3 3.Q o.V @.J g o.o.W X.' $.G ^ ^ ^ ^ ^ ^ x N X.e g.UXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX1 y Q ] g B V g k X.U V K N G ^ ^ ^ P ( P L { P ( 5 UXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX6 + R Q ] X.[ [ [ [ [ s B J M ( n ^ ^ x ( ( P x I 7 UXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX4 @ : 1.1.} d U g [ g [ ' B $.M D ^ ^ ^ ( ( D P P G 5 UXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX4 + 5 3 ,.u 6.m k X.U U [ s K N #.D ^ ^ x P ( ( P P Z UXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX4 + 3 UX5 : 5.Y H d W k X.U ' K N G D ^ ^ ^ ( ( ( P ( 5 UXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX4 + 3 UXUXUX3 @ 5.Y } o.o.k X.V %.~ c ^ ^ ^ x ( ( ^ P f 6 UXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX4 + 3 UXUXUX5 + - r 8.Q ] m o.k V  .@.c ^ ^ ^ ( ( ( x P &.UXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX4 + 3 UXUXUX7 O 2 s.& p Y H ] ] d [ K M G ^ ^ x ( ( P P f 5 UXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX4 + 3 UXUXUX5 O < UX5 , X 8.C ,.H ] U K M D ^ ^ x ( ( P P D 5 UXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX4 + 3 UXUXUX4 O < UXUXUX3 >.X R C Q F U ..N ( ^ D ( ( ( ( P Z 6 UXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX4 + 3 UXUXUX5 O < UXUXUXUX5 > O 0.Y C H X.B M D ^ ( x ( ( P I &.UXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX4 + 3 UXUXUX4 O < UXUXUXUXUXUX4 - X 8.1.H X.K G ^ l { l ^ ( P D 5 UX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX4 + 3 UXUXUX5 O < UXUXUXUXUXUXUX6 2 # 0.Y } g ..' X.X.X.J ) P ^ b UX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX4 + 3 UXUXUX4 O , UXUXUXUXUXUXUXUXUX7 & 0.y o r.C.C.C.C.C.q.+ ] N =.",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX2 O 5 UXUXUX5 O > UXUXUXUXUXUXUXUXUXUX5 O C.C.C.C.C.C.C.C.C.C.C.q.< ",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX, + 5 UXUXUX6 @ ; UXUXUXUXUXUXUXUXUXUXUX3 . C.C.C.C.C.C.C.C.C.C.C.+ ",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUX# & UXUXUXUXUX= # UXUXUXUXUXUXUXUXUXUXUXUX3 @ C.C.C.C.C.C.C.C.. % 3 ",
"UXUXUXUXUXUXUXUXUX5 4 4 1 & O 3 UXUXUXUXUX5 # & 1 4 4 5 UXUXUXUXUXUXUXUX5 , & + X X o # = 2 6 UX",
"UXUXUXUXUXUXUXUX2 O + @ # = 3 UXUXUXUXUXUXUX4 - $ @ + + 2 UXUXUXUXUXUXUXUXUXUX5 5 4 5 5 UXUXUXUX",
"UXUXUXUXUXUXUXUX1 X # $ $ & & % % % % % % % % & % # # o < UXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUXUX"
};

/* XPM */
const char *2dicon[] = {
/* columns rows colors chars-per-pixel */
"49 69 32 1",
"  c None",
". c #646464",
"X c #323232",
"o c #979797",
"O c Gray5",
"+ c #bcbcbc",
"@ c Gray0",
"# c Gray69",
"$ c Gray64",
"% c Gray49",
"& c #4b4b4b",
"* c #191919",
"= c Gray54",
"- c #717171",
"; c Gray15",
": c #3f3f3f",
"> c #585858",
", c Gray0",
"< c Gray0",
"1 c Gray0",
"2 c Gray0",
"3 c Gray0",
"4 c Gray0",
"5 c Gray0",
"6 c Gray0",
"7 c Gray0",
"8 c Gray0",
"9 c Gray0",
"0 c Gray0",
"q c Gray0",
"w c Gray0",
"e c Gray0",
/* pixels */
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"       %X@@@O:%       #*@OXXXXXXX@@@@*:%         ",
"     $*X%#  #%*;$     .: #ooooooo+   o-**o       ",
"    $O-        .O$    ..                %O%      ",
"   +O%  +=..o   -*+   .& $o    #-...%#   $O%     ",
"   &:  .@X>&**=  X.   #O@*;;+  O&...XOXo  $@$    ",
"  #@# :;#    =O% #O+       X- o*     +.O-  .X    ",
"  -& .;+      =O+ ;%       .. oX       $O% +Oo   ",
"  X% *o        &. -&       .. oX        $O# .&   ",
"  O# @         =* oX       .. oX         && #O   ",
"  @  @:+        @ +@       .. oX         #O+ ;=  ",
"  @  $:-        *$ @       .. oX          ;= >.  ",
"  @   =X        Xo @       .. oX          .> =X  ",
"  @+  oX        @+ @       .. oX          oX $O  ",
"  ;%  >>       #O +@       .. oX          #O  @  ",
"  %*#oOo       .: oX       .. oX           @  O$ ",
"   >@O%       +Oo -&       .. oX           O# Xo ",
"             o*&  ;%       .. oX           Xo Xo ",
"           +&O-  oO+       .. oX           Xo Xo ",
"          .O:#  +;.        .. oX           Xo Xo ",
"        o*Xo   +;&         .. oX           Xo Xo ",
"      +:O%    =O&          .. oX           Xo Xo ",
"     +;:+   #XO=           .. oX           Xo Xo ",
"    +;&   #&O.+            .. oX           Xo Xo ",
"    X&   .O&#              .. oX           @+ Xo ",
"   -*+ $;;o      $+        .. oX           @  O# ",
"  +Oo %O.      #*OO%       .. oX          $*  @  ",
"  -X %Oo       && =O+      .. oX          =X o*  ",
"  ;=+Oo        @#  &-      .. oX          >. %:  ",
" #O .:.XX:$    @   %X      .. oX          *o &-  ",
" -: X@X=o.O%   O#+$$*      .. oX         $O  *$  ",
" >. @:    $O%  .*OO @      .. oX         &> $*   ",
" Xo -+     =O$  $=O @      .. oX        $O# &>   ",
" Xo  #oo+   %O$  =X @      .. oX       +*- +@#   ",
" Xo =OX;O=   &O$ X.o;      &. $*      o*&  &&    ",
" Xo X&  =O%   -OOX+%:  .X.%O#  *X.o%.;O-  oO#    ",
" X= =O#  $O%   +$  :- %*%>:=   +-.XX.%+  $O%     ",
" .>  &-   $O%     #@+ ..                $O>      ",
" o*  >.    $O%    X>  ..              #&O%       ",
"  ;&oOo     $O&ooX;+  oOXXX@@@@OXXXXX*O&#        ",
"  $:X.       #&XX.+    #ooo#   #ooooo$           ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 ",
"                                                 "
};
