/* XPM */
const char *dbicon[] = {
/* columns rows colors chars-per-pixel */
"48 48 256 2",
"   c Gray100",
".  c #181818",
"X  c Gray13",
"o  c Gray16",
"O  c #313131",
"+  c #393939",
"@  c Gray26",
"#  c Gray29",
"$  c Gray32",
"%  c #5a5a5a",
"&  c Gray39",
"*  c Gray42",
"=  c Gray45",
"-  c #7b7b7b",
";  c #848484",
":  c Gray55",
">  c Gray58",
",  c Gray61",
"<  c #a5a5a5",
"1  c Gray68",
"2  c Gray71",
"3  c Gray74",
"4  c #c6c6c6",
"5  c #cecece",
"6  c Gray84",
"7  c Gray87",
"8  c #cec6c6",
"9  c #d6cece",
"0  c #bdb5b5",
"q  c #ada5a5",
"w  c #b5adad",
"e  c #c6bdbd",
"r  c #948c8c",
"t  c #9c9494",
"y  c #a59c9c",
"u  c #8c8484",
"i  c #7b7373",
"p  c #736b6b",
"a  c #847b7b",
"s  c #6b6363",
"d  c #5a5252",
"f  c #635a5a",
"g  c #736b63",
"h  c #cecec6",
"j  c #bdbdb5",
"k  c #adada5",
"l  c #b5b5ad",
"z  c #c6c6bd",
"x  c #94948c",
"c  c #9c9c94",
"v  c #a5a59c",
"b  c #8c8c84",
"n  c #7b7b73",
"m  c #73736b",
"M  c #84847b",
"N  c #6b6b63",
"B  c #5a5a52",
"V  c #63635a",
"C  c #4a4a42",
"Z  c #c6cec6",
"A  c #ced6ce",
"S  c #b5bdb5",
"D  c #a5ada5",
"F  c #adb5ad",
"G  c #bdc6bd",
"H  c #8c948c",
"J  c #949c94",
"K  c #9ca59c",
"L  c #737b73",
"P  c #7b847b",
"I  c #636b63",
"U  c #c6cece",
"Y  c #ced6d6",
"T  c #b5bdbd",
"R  c #a5adad",
"E  c #adb5b5",
"W  c #bdc6c6",
"Q  c #8c9494",
"!  c #949c9c",
"~  c #9ca5a5",
"^  c #848c8c",
"/  c #737b7b",
"(  c #6b7373",
")  c #7b8484",
"_  c #636b6b",
"`  c #9cadad",
"'  c #94a5a5",
"]  c #849494",
"[  c #7b8c8c",
"{  c #637373",
"}  c #9cb5b5",
"|  c #94adad",
" . c #7b9494",
".. c #9cbdbd",
"X. c #94b5b5",
"o. c #8cadad",
"O. c #9cc6c6",
"+. c #94b5bd",
"@. c #9cbdc6",
"#. c #9cb5bd",
"$. c #94adb5",
"%. c #8ca5ad",
"&. c #94a5ad",
"*. c #7b8c94",
"=. c #84949c",
"-. c #bdc6ce",
";. c #7b848c",
":. c #6b737b",
">. c #636b73",
",. c #424a52",
"<. c #949ca5",
"1. c #9c9ca5",
"2. c #73737b",
"3. c #6b6b73",
"4. c #292931",
"5. c #bdb5bd",
"6. c #ada5ad",
"7. c #b5adb5",
"8. c #9c949c",
"9. c Gray0",
"0. c Gray0",
"q. c Gray0",
"w. c Gray0",
"e. c Gray0",
"r. c Gray0",
"t. c Gray0",
"y. c Gray0",
"u. c Gray0",
"i. c Gray0",
"p. c Gray0",
"a. c Gray0",
"s. c Gray0",
"d. c Gray0",
"f. c Gray0",
"g. c Gray0",
"h. c Gray0",
"j. c Gray0",
"k. c Gray0",
"l. c Gray0",
"z. c Gray0",
"x. c Gray0",
"c. c Gray0",
"v. c Gray0",
"b. c Gray0",
"n. c Gray0",
"m. c Gray0",
"M. c Gray0",
"N. c Gray0",
"B. c Gray0",
"V. c Gray0",
"C. c Gray0",
"Z. c Gray0",
"A. c Gray0",
"S. c Gray0",
"D. c Gray0",
"F. c Gray0",
"G. c Gray0",
"H. c Gray0",
"J. c Gray0",
"K. c Gray0",
"L. c Gray0",
"P. c Gray0",
"I. c Gray0",
"U. c Gray0",
"Y. c Gray0",
"T. c Gray0",
"R. c Gray0",
"E. c Gray0",
"W. c Gray0",
"Q. c Gray0",
"!. c Gray0",
"~. c Gray0",
"^. c Gray0",
"/. c Gray0",
"(. c Gray0",
"). c Gray0",
"_. c Gray0",
"`. c Gray0",
"'. c Gray0",
"]. c Gray0",
"[. c Gray0",
"{. c Gray0",
"}. c Gray0",
"|. c Gray0",
" X c Gray0",
".X c Gray0",
"XX c Gray0",
"oX c Gray0",
"OX c Gray0",
"+X c Gray0",
"@X c Gray0",
"#X c Gray0",
"$X c Gray0",
"%X c Gray0",
"&X c Gray0",
"*X c Gray0",
"=X c Gray0",
"-X c Gray0",
";X c Gray0",
":X c Gray0",
">X c Gray0",
",X c Gray0",
"<X c Gray0",
"1X c Gray0",
"2X c Gray0",
"3X c Gray0",
"4X c Gray0",
"5X c Gray0",
"6X c Gray0",
"7X c Gray0",
"8X c Gray0",
"9X c Gray0",
"0X c Gray0",
"qX c Gray0",
"wX c Gray0",
"eX c Gray0",
"rX c Gray0",
"tX c Gray0",
"yX c Gray0",
"uX c Gray0",
"iX c Gray0",
"pX c Gray0",
"aX c Gray0",
"sX c Gray0",
"dX c Gray0",
"fX c Gray0",
"gX c Gray0",
"hX c Gray0",
"jX c Gray0",
"kX c Gray0",
"lX c Gray0",
"zX c Gray0",
"xX c Gray0",
"cX c Gray0",
"vX c Gray0",
"bX c Gray0",
"nX c Gray0",
"mX c Gray0",
"MX c Gray0",
"NX c Gray0",
"BX c Gray0",
"VX c Gray0",
"CX c Gray0",
"ZX c Gray0",
"AX c Gray0",
"SX c Gray0",
"DX c Gray0",
"FX c Gray0",
"GX c Gray0",
"HX c Gray0",
"JX c Gray0",
"KX c Gray0",
"LX c Gray0",
"PX c Gray0",
"IX c Gray0",
"UX c None",
/* pixels */
"UXUXUXUXUXUXUXUXUXUX4 3 3 3 2 2 , : , : - = = * * * - ; ; , 1 , 1 3 2 4 3 4 UXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUX4 2 1 > ; * $ # # # # # @ # # $ $ $ % % % % % $ $ % % % % & & ; > < 3 3 4 UXUXUXUXUX",
"UXUXUX4 3 : % + O O O O + + @ @ @ # # # # $ $ $ % % & & & & % % % % % % $ $ $ $ $ & ; 1 4 4 UXUX",
"UXUX4 - o X X o o o o O O O + + + @ @ # # $ $ $ % & & & % % % % % % $ $ $ $ $ $ $ # # # % 2 UXUX",
"UX5 @ . X X X X X X X X X o X o o o o O O + @ $ % % % $ $ $ $ $ # # # # # @ @ @ @ @ @ + + + 2 UX",
"UX, . O o O O O O O O O O O O O O + + + + @ # $ $ @ + O O o o o o o o o o o o o o o o o o X $ UX",
"UX1 + + @ + @ @ @ @ # # # # $ $ $ $ % % % & & & % $ # @ + + O o o o X X X X X X X X X X X . = UX",
"UX4 M $ # # # # $ $ $ $ $ % % % % % % & & * & & % $ $ # # @ @ @ + + O O O o o o X X . . o # 1 UX",
"UX4 q , M * % % $ $ % % % % % % & & & & * & & % % $ $ $ # # # @ @ @ @ + + + O O O O $ { [ > l UX",
"UX4 v < y 1 y x a - * & % % & & & & * * & * & & % % $ $ $ $ # # # @ @ @ @ # $ B & <.O.#.! Q 1 UX",
"UX4 < y , k < 1 < j 1 q 8.- = = m * * * * & & % % $ % $ $ $ $ $ $ B % & N i n - - %.O.$.! Q l UX",
"UX4 v v t < v q < 2 w 2 2 t t r : a * s g s f f s & & * L i * N p p * p = i - n - %.@.$.! x 7.UX",
"UX5 y , c < y q y 2 1 w 1 > > r > a * s p s V f & s & m - n * s * p N * * = i n - %.@.| ! > 1 UX",
"UXh v y > < v < < 2 w E w > t r > a * s g s f f & s & = a i * N * m N * p = n - - %.@.$.' > < UX",
"UX4 v , t v y q y 2 1 w 1 t > : > a * N g s f V & s s m - n p * p p s * * = i n - %.@.| ' > l UX",
"UX5 y , t < y q < 2 1 1 w t > r > a * s p s f f s * & = a i m * m m s * N = n a / %.@.| ~ > 2 UX",
"UX5 v c t K y < y 2 w w 1 > r r > a N g g s V f s N * = P n = m = * s * * = n - / &.@.| ~ > S UX",
"UX9 , c t , y < v 2 1 1 w t > : > a * s p s f V s * N = a n = m = p & N * = - n / %.@.| ~ J w UX",
"UX6 y c > y , q < w w 1 2 > r r > a * g g s f f s * * = M i = = n p & * N m - a 2.| @.&.~ ! l UX",
"UX5 v t > , c < y 2 1 1 w t x : t a * N g s f V * * * i M n i L - * & N N i - n 2.%.@.| < , 2 UX",
"UX3 y > x y , v y 2 k 1 w > r : t a N g p s f f N p p L M - n n - p V s * = - - 2.| @.&.D ! l UX",
"UX4 v t > c y < v w 1 k w t r : t a * g g s V f * * p n M i - n - * f * s m a n = $...&.R t 2 UX",
"UX4 v > r c t < y l 1 6.l t r : , a s p g s f f N = p - ; n n - M p % N N = P - = %.@.' R J 3 UX",
"UX4 v > x , c < y 1 1 k w t r b 8.a * g g N f V * = m n M - M M ; * % * s = M - ( $...&.R t 3 UX",
"UX4 < r r t c < y l 1 q l > r : t a N p g s f V p = m - ; n ; ; ; p % s N = a n ( $.#.' R c 3 UX",
"UX4 v x > t t v y 1 1 k w t r u 8.a * p p s f V p = = n M a b b b p % * s = ; n 3.$.+.&.1 > 3 UX",
"UX4 q r r > t < v 1 w < l > r b , a * g p s V s * i = - M a H x : = f N s = P - ( | #.' 1 J 4 UX",
"UXh < x r > t v y 1 1 q w t r u 8.a g p p s f & m i = - a M > J : = f * s m ; n 3.$.+.' 1 > 4 UX",
"UX4 v r r > t v y 1 1 q F t : u t a * p p V f N = = = n M a J , x = V I s = ) = ( $.#.' 1 ! z UX",
"UX5 < r x x > y y 1 k q w > r u , a * m p s V s = n i - - ; K < > i & N & = ; = 3.$.X.' 1 J 8 UX",
"UX5 v r r > x < y k 1 < w t : u t a p p p & f N = - n - a ; < D t - & N & = ) L 3.$.X.' F , 3 UX",
"UX5 < r x r > v , 6.1 q F t : u 8.a * m m & f * = - n - n ; 1 F , n & N & = ) = 3.$.$.' 1 c 3 UX",
"UX9 v : r > x y y k q v w t b u > a * m p s V * = - n - n b F 2 , - & N & = ) = ( $.X.1.E > 5 UX",
"UX4 q r r > r v , q 1 < w > : u t a p i m & f * i a - - - b T 3 y a & _ & ( ) = >.$.$.! E c 8 UX",
"UX3 k : r x r y v < 6.v w t u u > a p m m & & * = - n - i b T G K ; & N & = ) = * $.X.! 7.J h UX",
"UXW k r r > x , , q 1 v w > : u t a p p i V & p L a - - n H 3 W y a * * N ( ) = >.$.| ~ E , 2 UX",
"UX4 1 : r r r y v < k y 1 t u u > a * m p & & m = - n - - > G z , M * = * / ) = >.X.| 1.F y 0 UX",
"UX4 w : r x : , y < 6.v w c u u > a * m p & & = = - n - - > W 4 , a * L = / ) ( >.$.| , E K 3 UX",
"UXe 1 r : r r y , v 1 y 1 8.u u > a p p p & s = m - n - - c W 4 , M = - - / ;.= >.$.| ! 2 , j UX",
"UXW w : r r : , v < q , w c u u r - p m p & N = = i n - - , Z 4 y - = ; P ) [ ( >.X.| 1.2 , 3 UX",
"UX4 1 b : r : , y y 1 y 1 , u ; > a p p p & * = = n - - a K U 4 , P / ; ; [ [ = >.} ' K E , z UX",
"UX4 2 b : : b , v < q , w 8.u u x - * p p & * i m i n - - v U Z , a - : : [ [ ( >.$.&.~ 2 , U UX",
"UXUX5 u u : u , y , k y 1 , M ; > i p p * & * i = i n - M D 5 4 , M - Q x ^ *.( >.} ' , F l 8 UX",
"UXUX4 e > u u 8.v y 6., 1 8.u u r i p p * & * - m i n - - D A h , a ) J > ] ] ( >.X.' 1.4 5 UXUX",
"UXUXUXUX4 q ; t y , k y 6., M ; r i p p * f = n p = n - M F Y 4 , a ; , , ]  .3._ $.` Z W UXUXUX",
"UXUXUXUXUX4 e 3 < y < t k , u a r - * p * & = - m i n - M 1 6 Z c - ; K K =. .:.Q -.5 3 UXUXUXUX",
"UXUXUXUXUXUXUXUX4 4 4 2 0 < a ; r p s p s & = - m = i = M k A 4 , M : E 2 T Z 3 4 UXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUXe 4 e 4 e 0 2 y : : : > > : x t , c 3 7 5 4 3 W 4 4 UXUXUXUXUXUXUXUXUXUXUX"
};
