#############################################################################
# $Id: //depot/qt/2.2/tests/qml/Makefile#1 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = png

!INCLUDE $(QTDIR)\Makefile.inc
