COMMERCIAL_OBJS = borland_bmake.o msvc_dsp.o msvc_vcproj.o \
                  msvc_nmake.o msvc_objectmodel.o 

COMMERCIAL_DEPEND_SRC = generators/win32/msvc_objectmodel.cpp \
                         generators/win32/msvc_nmake.cpp \
                        generators/win32/borland_bmake.cpp 

