OPENSOURCE_CXXFLAGS = -DQMAKE_OPENSOURCE_EDITION

OPENSOURCE_OBJS = metrowerks_xml.o  pbuilder_pbx.o borland_bmake.o msvc_dsp.o msvc_vcproj.o \
            msvc_nmake.o msvc_objectmodel.o 

OPEN_SOURCE_DEPEND_SRC = generators/mac/pbuilder_pbx.cpp generators/win32/msvc_objectmodel.cpp \
                         generators/mac/metrowerks_xml.cpp generators/win32/msvc_nmake.cpp \
                         generators/win32/borland_bmake.cpp 

