#############################################################################
# $Id: //depot/qt/qws/util/qws/GNUmakefile#2 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = qimpenedit

include $(QTDIR)/GNUmakefile.inc

