#############################################################################
# $Id: //depot/qt/qws/util/qws/Makefile#1 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = qimpenedit

!INCLUDE $(QTDIR)\Makefile.inc
