#############################################################################
# $Id: //depot/qt/2.1/util/scripts/makeqtmake.bat#1  Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = extrawidgets

!INCLUDE $(QTDIR)\Makefile.inc
