#############################################################################
# $Id: //depot/qt/main/tutorial/t5/GNUmakefile#3 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = t5

include $(QTDIR)/GNUmakefile.inc
