#############################################################################
# $Id: //depot/qt/main/examples/addressbook/Makefile#5 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = addressbook

!INCLUDE $(QTDIR)\Makefile.inc
