// axaptamail.idl : IDL source for axaptamail.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (axaptamail.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(E514925C-6823-419D-AF2B-9BA1B746E8B5),
		dual,
		helpstring("ITemplateParser Interface"),
		pointer_default(unique)
	]
	interface ITemplateParser : IDispatch
	{
		[id(1), helpstring("method addVariable")] HRESULT addVariable(BSTR name,BSTR value);
		[id(2), helpstring("method parseTemplate")] HRESULT parseTemplate(BSTR inStream,[out,retval]BSTR* outStream);
		[id(3), helpstring("method dropDictionary")] HRESULT dropDictionary();
	};

[
	uuid(A4CC5C89-1ECA-45D7-957F-23C81989767A),
	version(1.0),
	helpstring("axaptamail 1.0 Type Library")
]
library AXAPTAMAILLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(74013298-9F5A-41F5-BC49-6304B05921DC),
		helpstring("TemplateParser Class")
	]
	coclass TemplateParser
	{
		[default] interface ITemplateParser;
	};
};
