#############################################################################
# $Id: //depot/qt/main/extensions/nsplugin/examples/trivial/Makefile#3 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = trivial

!INCLUDE $(QTDIR)\Makefile.inc
