TEMPLATE	= lib
CONFIG		+= qt dll release
HEADERS		= 
SOURCES		= trivial.cpp
unix:LIBS	+= -lXt
LIBS	+= -lqnp
DEF_FILE	= trivial.def
RC_FILE		= trivial.rc
TARGET      	= trivial
win32:TARGET	= nptrivial
