TEMPLATE	= lib
CONFIG		+= qt dll release
HEADERS		= 
SOURCES		= trivial.cpp
unix:LIBS	= -lqnp -lXt
win32:LIBS	+= $$QT_BUILD_TREE/lib/qnp.lib
DEF_FILE	= trivial.def
RC_FILE		= trivial.rc
TARGET      	= trivial
win32:TARGET	= nptrivial
