#############################################################################
# $Id: makeqtmake,v 1.1 1998/02/25 18:12:02 hanord Exp  Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = t2

include $(QTDIR)/GNUmakefile.inc
