#! /bin/sh

# Compile a .cg file to a .h file that can be included in a C++ program

USAGE="Usage: $0 -p <profile> -o <file.h> <file.cg>"
CGC=cgc

while getopts o:p: opt
do
   case $opt in
      o) H_FILE=$OPTARG;;
      p) PROFILE=$OPTARG;;
      \?)  echo $USAGE; exit 1;;
   esac
done
shift `expr $OPTIND - 1`

CG_FILE=$1

echo "// Generated by src/gui/util/$0 from $1" > $H_FILE
$CGC -quiet -profile $PROFILE $CG_FILE | while read line
do
   if test `echo $line | cut -c1` != "#"
   then
      echo '"'$line'"' >> $H_FILE
   fi
done
echo "; // Generated by src/gui/util/$0 from $1" >> $H_FILE

