#############################################################################
# $Id: //depot/qt/main/extensions/opengl/examples/texture/GNUmakefile#1 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = texture

include $(QTDIR)/GNUmakefile.inc
