#!/usr/bin/perl
############################################################################
#
# Builds makefiles for Qt using tmake.
#
# Copyright (C) 1996-1998 by Troll Tech AS.  All rights reserved.
#
############################################################################

$qtdir = $ENV{"QTDIR"};
chdir "$qtdir";

$is_win32 = 0;
$is_dll = 0;
$tmakeargs = "";
$dllargs = "";

while ( @ARGV ) {
    $_ = shift @ARGV;
    if ( /^-win32$/ ) {
	$is_win32 = 1;
	$tmakeargs .= " -win32";
    } elsif ( /^-dll$/ ) {
	$is_dll = 1;
	$dllargs = "DEFINES+=QT_DLL";
    }
}

@projects = find_files('src','\.pro$',1);
push @projects, find_files('examples','\.pro$',1);
push @projects, find_files('tutorial','\.pro$',1);
push @projects, find_files('extensions','\.pro$',1);
for $p ( @projects ) {
    next if ( $p eq "src/qtinternal.pro" );    
    if ( ($p =~ /(.*\/)([^\/]+)/) ) {
	$dir  = $1;
	$file = $2;
	chdir $dir;
	$m = "Makefile";
	if ( $is_win32 ) {
	    if ( ($p eq "src/qt.pro") && $is_dll ) {
		$m = "qtdll.mak";
	    }
	    if ( $p eq "src/qtmain.pro" ) {
		if ( $is_dll ) {
		    $m = "qtmain.mak";
		    print STDERR "Building ${dir}$m\n";
		    `tmake $tmakeargs $file -o $m`;
		}
		$m = "";
	    }
	}
	if ( $m ) {
	    print STDERR "Building ${dir}$m\n";
	    `tmake $tmakeargs $dllargs $file -o $m`;
	}
	chdir $qtdir;
    }
}
exit;


#
# Finds files.
#
# Examples:
#   find_files("/usr","\.cpp$",1)   - finds .cpp files in /usr and below
#   find_files("/tmp","^#",0)	    - finds #* files in /tmp
#

sub find_files {
    my($dir,$match,$descend) = @_;
    my($file,$p,@files);
    local(*D);
    $dir =~ s=\\=/=g;
    ($dir eq "") && ($dir = ".");
    if ( opendir(D,$dir) ) {
	if ( $dir eq "." ) {
	    $dir = "";
	} else {
	    ($dir =~ /\/$/) || ($dir .= "/");
	}
	foreach $file ( readdir(D) ) {
	    next if ( $file  =~ /^\.\.?$/ );
	    $p = $dir . $file;
	    ($file =~ /$match/) && (push @files, $p);
	    if ( $descend && -d $p && ! -l $p ) {
		push @files, &find_files($p,$match,$descend);
	    }
	}
	closedir(D);
    }
    return @files;
}
