#!/usr/bin/perl
# Written by Arnt Gulbrandsen <agulbra@troll.no> and copyright 1996 Troll
# Tech AS, Postboks 6133 Etterstad, 0602 Oslo, Norway, fax +47 22646949.
#
# Use, modification and distribution is allowed without limitation,
# warranty, or liability of any kind.

# This script requires perl 5.

chdir( "/home/agulbra/qt" );

open( I, "cvs -Q log '-d>04/05/97 12:12:12' |" ) || die;

undef $/;
$_ = <I>;
close I;

# print $_;

foreach $logentry ( split( /\n=============*\n/s, $_ ) ) {
    if ( $logentry =~ /\nWorking file: (\S+)/s ) {
	$file = $1;
	while ( $logentry =~ s/^.*?----------------------------\n/\n/s ) {
	    if ( $logentry =~ /^\s*revision\s+(\S+)\s+date:\s+(\S+).*?author:\s+(\S+?);.*?lines:\s+(.*?)\s*\n(.*?)(?:$|(?:\n----------------------------\n))/s ) {
		$rev = $1;
		$date = $2;
		$author = $3;
		$lines = $4;
		$entry = $5;
		$entry =~ s/\n/\n  /gs;
		$entry =~ s/\s*$//s;
		$logs{$date}{$entry} .= "\n" . $file . "    " . $rev 
		    . "  " . $author . "  " . $lines;
	    } elsif ( $logentry =~ /^\s*revision\s+(\S+)\s+date:\s+(\S+).*?author:\s+(\S+?);.*?\s*\n(.*?)(?:$|(?:\n----------------------------\n))/s ) {
		$rev = $1;
		$date = $2;
		$author = $3;
		$entry = $4;
		$entry =~ s/\n/\n  /gs;
		$entry =~ s/\s*$//s;
		$logs{$date}{$entry} .= "\n" . $file . "    " . $rev 
		    . "  " . $author . "  initial checkin";
	    }
	}
    }
}

foreach $date ( sort keys %logs ) {
    $d = "  ($date)";
    foreach $logentry( sort { $a cmp $b } keys %{$logs{$date}} ) {
	$_ = $logs{$date}{$logentry};
	s/(\S)($|\n)/$1$d$2/;
	print $_, "\n\n  ", $logentry, "\n\n";
	$d = "";
    }
}

# =============================================================================
# 
# RCS file: /local/lib/cvs/qt/dist/changes-0.99,v
# Working file: dist/changes-0.99
# head: 1.4
# branch:
# locks: strict
# access list:
# symbolic names:
# keyword substitution: kv
# total revisions: 4;     selected revisions: 2
# description:
# ----------------------------
# revision 1.4
# date: 1996/09/05 09:51:39;  author: paul;  state: Exp;  lines: +0 -4
# lastWindowClosed not implemented after all.
# ----------------------------
# revision 1.3
# date: 1996/09/04 16:40:19;  author: paul;  state: Exp;  lines: +3 -1
# new FAQ
