#!/usr/bin/perl

#
# NOTE: The first argument is the Qt version.
#

die unless ( $#ARGV > 0 );

undef $/;

$copyright = "
** Copyright (C) 1992-1998 Troll Tech AS.  All rights reserved.
**
** This file is part of Qt Professional Edition, version " . $ARGV[0] . ".
**
** All intellectual property rights in this software are owned by
** Troll Tech AS.
**
** Holders of Qt Professional Edition licenses may use this software 
** under the terms specified in the license agreement, which is
** stated in the file LICENSE which is included in the distribution 
** of Qt Professional Edition.
** 
** Qt is a trademark of Troll Tech AS.
**
*****************************************************************************/";

shift @ARGV;

foreach $f ( @ARGV ) {
    if ( open( F, "< $f" ) ) {
	$i = <F>;
	close F;
	$i =~ s=\n\*\* Copyright.*?\*/=$copyright=s;
	$i =~ s-\s*$--s;
	if ( open( F, "> $f" ) ) {
	    print F $i, "\n";
	    close F;
	}
    }
}
