#!/usr/bin/perl

die unless ( $#ARGV >= 0 );

undef $/;

$copyright = "
** Copyright (C) 1992-1996 Troll Tech AS.  All rights reserved.
**
** This file is part of the non-commercial distribution of Qt " . $ARGV[0] . ".
**
** See the file LICENSE included in the distribution for the usage
** and distribution terms, or http://www.troll.no/qt/license.html.
**
** (This file differs from the one in the commercial distribution of
** Qt only by this comment.)
**
*****************************************************************************/";

foreach $f ( @ARGV ) {
    if ( open( F, "< $f" ) ) {
	$i = <F>;
	close F;
	$i =~ s=\n\*\* Copyright.*?\*/=$copyright=s;
	$i =~ s-\s*$--s;
	if ( open( F, "> $f" ) ) {
	    print F $i, "\n";
	    close F;
	}
    }
}
