#!/usr/bin/perl

#
# NOTE: The first argument is the Qt version.
#

die unless ( $#ARGV > 0 );

undef $/;

$copyright = "
** Copyright (C) 1992-1998 Troll Tech AS.  All rights reserved.
**
** This file is part of the free edition of Qt " . $ARGV[0] . ".
**
** See the file LICENSE included in the distribution for the usage
** and distribution terms, or http://www.troll.no/qt/license.html.
**
** IMPORTANT NOTE: You may NOT copy this file or any part of it into
** your own programs or libraries.
**
** (This file differs from the one in the commercial edition of Qt
** only by this comment.)
**
*****************************************************************************/";

shift @ARGV;

foreach $f ( @ARGV ) {
    if ( open( F, "< $f" ) ) {
	$i = <F>;
	close F;
	$i =~ s=\n\*\* Copyright.*?\*/=$copyright=s;
	$i =~ s-\s*$--s;
	if ( open( F, "> $f" ) ) {
	    print F $i, "\n";
	    close F;
	}
    }
}
