#!/usr/bin/perl

# 1. Check that you have submitted all p4 changes and have no opened files.
# 2. Edit the licensing terms in this file as required.
# 3. Run this script from $QTDIR, it will report p4 edit operations as needed.
# 4. p4 submit the results.

%professional_module =
(
    "tools" => 1,
    "kernel" => 1,
    "widgets" => 1,
    "dialogs" => 1,
    "iconview" => 1
);

sub relicense
{
    my($file,$content) = @_;

    $content =~ s/\bTroll Tech\b/Trolltech/g;

    $qpl_license=
"** This file may be distributed under the terms of the Q Public License
** as defined by Trolltech AS of Norway and appearing in the file
** LICENSE.QPL included in the packaging of this file.
**
";

    $gpl_license=
"** This file may be distributed and/or modified under the terms of the
** GNU General Public License version 2 as published by the Free Software
** Foundation and appearing in the file LICENSE.GPL included in the
** packaging of this file.
**
";

    $ent_license=
"** Licensees holding valid Qt Enterprise Edition licenses may use this
** file in accordance with the Qt Commercial License Agreement provided
** with the Software.
**
";

    $pro_license=
"** Licensees holding valid Qt Enterprise Edition or Qt Professional Edition
** licenses may use this file in accordance with the Qt Commercial License
** Agreement provided with the Software.
**
";

    $ent_license_win=
"** Licensees holding valid Qt Enterprise Edition licenses for Windows
** may use this file in accordance with the Qt Commercial License Agreement
** provided with the Software.
**
** This file is not available for use under any other license without
** express written permission from the copyright holder.
**
";

    $ent_license_emb=
"** Licensees holding valid Qt Enterprise Edition licenses for Qt/Embedded
** may use this file in accordance with the Qt Embedded Commercial License
** Agreement provided with the Software.
**
** This file is not available for use under any other license without
** express written permission from the copyright holder.
**
";

    $ent_license_x11=
"** Licensees holding valid Qt Enterprise Edition licenses for Unix/X11 may
** use this file in accordance with the Qt Commercial License Agreement
** provided with the Software.
**
";

    $ent_license_unix=
"** Licensees holding valid Qt Enterprise Edition licenses for Unix/X11 or
** for Qt/Embedded may use this file in accordance with the Qt Commercial
** License Agreement provided with the Software.
**
";

    $pro_license_win=
"** Licensees holding valid Qt Enterprise Edition or Qt Professional Edition
** licenses for Windows may use this file in accordance with the Qt Commercial
** License Agreement provided with the Software.
**
** This file is not available for use under any other license without
** express written permission from the copyright holder.
**
";

    $pro_license_emb=
"** Licensees holding valid Qt Enterprise Edition or Qt Professional Edition
** licenses for Qt/Embedded may use this file in accordance with the
** Qt Embedded Commercial License Agreement provided with the Software.
**
** This file is not available for use under any other license without
** express written permission from the copyright holder.
**
";

    $pro_license_x11=
"** Licensees holding valid Qt Enterprise Edition or Qt Professional Edition
** licenses for Unix/X11 may use this file in accordance with the Qt Commercial
** License Agreement provided with the Software.
**
";

    $pro_license_unix=
"** Licensees holding valid Qt Enterprise Edition or Qt Professional Edition
** licenses for Unix/X11 or for Qt/Embedded may use this file in accordance
** with the Qt Commercial License Agreement provided with the Software.
**
";

    $warranty=
"** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
";

    $ref_com=
"** See http://www.trolltech.com/pricing.html or email sales\@trolltech.com for
**   information about Qt Commercial License Agreements.
";

    $ref_qpl=
"** See http://www.trolltech.com/qpl/ for QPL licensing information.
";

    $ref_gpl=
"** See http://www.trolltech.com/gpl/ for GPL licensing information.
";

    $examples_license=
"**
** This file is part of an example program for Qt.  This example
** program may be used, distributed and modified without limitation.
**
*****************************************************************************/";

    $footer=
"**
** Contact info\@trolltech.com if any conditions of this licensing are
** not clear to you.
**
**********************************************************************/";


    if ($file =~ m{/src/([^/]*)/([^/]*)$} ) {
	$module = $1;

	if ( $file =~ m{_win.*\.(h|cpp)$} ) {
	    # Windows
	    $com_license = $professional_module{$module}
		? $pro_license_win : $ent_license_win;
	    $content =~
		s{module of the Qt.*?Qt Commercial License.*?\*/}
		{module of the Qt GUI Toolkit.\n**\n$com_license$warranty$ref_com$footer}s;
	} elsif ( $file =~ m{_unix.*\.(h|cpp)$} ) {
	    # X11 or Qt/Embedded (Unix)
	    $com_license = $professional_module{$module}
		? $pro_license_unix : $ent_license_unix;
	    $content =~
		s{module of the Qt.*?Qt Commercial License.*?\*/}
		{module of the Qt GUI Toolkit.\n**\n$qpl_license$gpl_license$com_license$warranty$ref_com$ref_qpl$ref_gpl$footer}s;
	} elsif ( $file =~ m{_x11.*\.(h|cpp)$} ) {
	    # X11
	    $com_license = $professional_module{$module}
		? $pro_license_x11 : $ent_license_x11;
	    $content =~
		s{module of the Qt.*?Qt Commercial License.*?\*/}
		{module of the Qt GUI Toolkit.\n**\n$qpl_license$gpl_license$com_license$warranty$ref_com$ref_qpl$ref_gpl$footer}s;
	} elsif ( $file =~ m{_qws.*\.(h|cpp)$} ) {
	    # Qt/Embedded
	    $com_license = $professional_module{$module}
		? $pro_license_emb : $ent_license_emb;
	    $content =~
		s{module of the Qt.*?Embedded.*?\*/}
		{module of the Qt GUI Toolkit.\n**\n$com_license$warranty$ref_com$footer}s;
	} elsif ( $professional_module{$module} ){
	    # Qt Professional or Enterprise Edition
	    $content =~
		s{module of the Qt.*?LICENSE.QPL.*?\*/}
		{module of the Qt GUI Toolkit.\n**\n$qpl_license$gpl_license$pro_license$warranty$ref_com$ref_qpl$ref_gpl$footer}s;
	} else {
	    # Qt Enterprise Edition
	    $content =~
		s{module of the Qt.*?LICENSE.QPL.*?\*/}
		{module of the Qt GUI Toolkit.\n**\n$qpl_license$gpl_license$ent_license$warranty$ref_com$ref_qpl$ref_gpl$footer}s;
	}
    } elsif ($file =~ m{/examples/} ) {
	# Examples
	$content =~
	    s{(/\*.*?Copyright[^\n]*Trolltech.*?\n).*?\*/}
	    {$1$examples_license}s;
    } elsif ($file =~ m{/doc/} || $file =~ m{/extensions/} ) {
	# Documentation, extensions
	$content =~
	    s{This file is part of the Qt.*?LICENSE.QPL.*?\*/}
	    {This file is part of the Qt GUI Toolkit.\n**\n$qpl_license$gpl_license$pro_license$warranty$ref_com$ref_qpl$ref_gpl$footer}s;
    } elsif ($file =~ m{/tools/designer/} ) {
	# GPL application
	$content =~
	    s{(/\*.*?Copyright[^\n]*Trolltech.*?This file is part of.*?\n).*?\*/}
	    {$1**\n$gpl_license$warranty$ref_gpl$footer}s;
    }

    return $content;
}



use File::Find;

sub change {
    if ( -f $_ && $_ =~ /\.(doc|cpp|h)$/ ) {
print STDERR "$File::Find::dir/$_\n";
	my $c = `cat $_`;
	my $cc = relicense("$File::Find::dir/$_", $c);
	if ( $cc ne $c ) {
	    system("p4 edit $_");
	    open O,">$_";
	    print O $cc;
	    close O;
	}
    }
}

$d=`pwd`; chomp $d;
find(\&change,$d);
