#!/usr/bin/perl

system("cd ~/troll; cvs update kunder.txt");

#Set the variable $dryrun to 0 to actually send mail to all customers

$dryrun="testrun";          # 0 for real, or file for test result

if ($dryrun) {
    open( MAIL, "> $dryrun" );
    print MAIL "All this WOULD have been sent...\n\n";
    close( MAIL );
}

if ( $#ARGV != 0 ) {
    die "Usage:  mail-to-customers mail-file\n";
}

$custfile = $ENV{"HOME"}."/troll/kunder.txt";

open( MESSAGE, "<".$ARGV[0] ) || die "1";

undef $/;
$message_template = <MESSAGE>;

$/ = "\n";
open( CUSTOMERS, "<".$custfile ) || die "1";

foreach $line ( <CUSTOMERS> ) {
    $exp = "";
    chomp $line;
    next unless ( $line =~ /\S/ );
    ($name, $addr, $platform, $exp, $org) = split( / *\t+ */, $line );
    die "$line\ninvalid line, stopped" unless ( $exp =~ m-^\d+/\d+/\d+$- );

    $to = $addr;

    if ($dryrun) {
        open( MAIL, ">> $dryrun" );
    } else {
        open( MAIL, "| /usr/sbin/sendmail -t" );
    }

    $message = $message_template;
    if ( $platform =~ m/xw|wx/i ) {
	$message =~ s/<both>(.*?)<\/both>/\1/sig;
    } else {
	$message =~ s/<both>.*?<\/both>//sig;
    }
    if ( $platform =~ m/x/i ) {
	$message =~ s/<x11>(.*?)<\/x11>/\1/sig;
    } else {
	$message =~ s/<x11>.*?<\/x11>//sig;
    }
    if ( $platform =~ m/w/i ) {
	$message =~ s/<win>(.*?)<\/win>/\1/sig;
    } else {
	$message =~ s/<win>.*?<\/win>//sig;
    }

    if ( $message =~ /^\s*$/ ) {
	print "No mail to ", $to, "\n";
    } else {
	print "Sending mail to ", $to, "\n";
	print MAIL  "To: ",$to,"\n";
	print MAIL $message,"\n";
	close MAIL;
    }
}
