#!/usr/bin/perl

$version="1.30";                      # May include "beta", etc.
$winfile="qtwin130.zip";                 # Name as presented to customer
$winsource="~/qtwin130.zip";             # File on zen.linpro.no
$xfile="qt-1.30-commercial.tar.gz";      # Name as presented to customer
$xsource="~/qt-1.30-commercial.tar.gz";  # File on zen.linpro.no
$custfile = $ENV{"HOME"}."/troll/kunder.txt";
$dryrun=0; #"testrun";          # 0 for real, or file for test result


$message=			     # Footer of message
"Please send me mail when I can delete the files, and feel free to send
any questions to support\@troll.no.

- Paul";




open( CUSTOMERS, "<".$custfile ) || die "1";
open( SSH, "| ssh zen.linpro.no" ) || die "2";
print SSH "cd www/ftp/.private\n";

foreach $line ( <CUSTOMERS> ) {
    $exp = "";
    chomp $line;
    ($name, $addr, $platform, $exp, $org) = split( / *\t+ */, $line );
    die "$line\ninvalid line, stopped" unless ( $exp =~ m-^\d+/\d+/\d+$- );

    $key = lc $org;
    $key =~ s/[^a-z0-9].*//;
    $_ = `mcookie`;
    $_ =~ s/(........).*/\1/s;
    $key = "$key-$_";


    $to = $addr;
    if ($dryrun) {
        open( MAIL, ">> $dryrun" );
    } else {
        open( MAIL, "| /usr/sbin/sendmail -t" );
    }

    print MAIL  "To: ",$to,"\n",
		"Subject: Qt ",$version," released\n",
		"Organization: Troll Tech AS; fax +47 22646949; http://www.troll.no\n",
		"Cc: support\@troll.no\n",
		"Reply-To: support\@troll.no\n",
		"MIME-Version: 1.0\n",
		"Content-Type: text/plain; charset=US-ASCII\n",
		"\n" ;
    print MAIL
"Dear Qt customer, 

Qt version 1.30 is now released, it is the next major release
after 1.2. 
";


    print SSH "mkdir ", $key, "\n";


    if ( $platform =~ /w/ ) {
	print SSH "ln ",$winsource," ", $key, "\n";
	print MAIL "
Here is a URL for the Windows version:

   ftp://ftp.troll.no/.private/", $key, "/", $winfile, "
";
    }

    if ( $platform =~ /x/ ) {
	print SSH "ln ",$xsource," ", $key, "\n";
	print MAIL "
Here is a URL for the X11 version:

   ftp://ftp.troll.no/.private/", $key, "/", $xfile, "
";
    }


    print MAIL "
",$message,"
";
    close MAIL;
}

close SSH;




