#!/usr/bin/perl

$version="1.31";                      # May include "beta", etc.
$sourcedir="~/qt";                       # Location on zen.linpro.no
$winfile="qtwin131.zip";                 # Name of Windows archive
$xfile="qt-1.31-commercial.tar.gz";      # Name of X11 archive
$winpatch="qtdif131.zip";                 # Name of Windows patch or 0 if no
$xpatch="qt-1.31-commercial.diff.gz";      # Name of X11 patch or 0 if no
$custfile = $ENV{"HOME"}."/troll/kunder.txt";
$dryrun=0; #"testrun";          # 0 for real, or file for test result

$message=			     # Footer of message
"Please send me mail when I can delete the files, and feel free to send
any questions to support\@troll.no.

- Paul";

# WARNING WARNING WARNING
#
# There are hardcoded values and strings in this version, please
# examine carefully before using.


open( CUSTOMERS, "<".$custfile ) || die "1";
open( SSH, "| ssh zen.linpro.no" ) || die "2";
print SSH "cd www/ftp/.private\n";

foreach $line ( <CUSTOMERS> ) {
    $exp = "";
    chomp $line;
    ($name, $addr, $platform, $exp, $org) = split( / *\t+ */, $line );
    die "$line\ninvalid line, stopped" unless ( $exp =~ m-^\d+/\d+/\d+$- );

    $key = lc $org;
    $key =~ s/[^a-z0-9].*//;
    $_ = `mcookie`;
    $_ =~ s/(........).*/\1/s;
    $key = "$key-$_";


    $to = $addr;
    if ($dryrun) {
        open( MAIL, ">> $dryrun" );
    } else {
        open( MAIL, "| /usr/sbin/sendmail -t" );
    }

    print MAIL  "To: ",$to,"\n",
		"Subject: Qt ",$version," released\n",
		"Organization: Troll Tech AS; fax +47 22646949; http://www.troll.no\n",
		"Cc: support\@troll.no\n",
		"Reply-To: support\@troll.no\n",
		"MIME-Version: 1.0\n",
		"Content-Type: text/plain; charset=US-ASCII\n",
		"\n" ;
    print MAIL
"Dear Qt customer, 

Qt version 1.31 is now released, it is a bug fix release with the
following bugs fixed (compared to 1.30):

Changing the font of a QButton, QPushButton, QCheckBox or QRadioButton now
works correctly.

QRadiobutton:    Correct toggling in a QButtonGroup when activated by an
                 accelerator.

QPopupMenu:      Items updated correctly when activated by an accelerator.

QProgressBar:    Base color is no longer fixed to white.

QProgressDialog: setLabel() and setCancelButton() now ensure that a given
	         widget is shown and is a child of QProgressDialog.

QWidget:         setEnabled( FALSE ) now moves focus correctly.

QLineEdit and
QMultiLineEdit:  In keyPressEvent() backspace no longer inserts an
                 unprintable character with some rare keyboard layouts.

QMenubar:        Mouse presses on items without any popup menu are now
		 always recognized.

 * Changes to fix compile problems under IRIX.

 * Changes to fix compile problems on some versions of AIX.

 * Changes to fix compile problems with aCC on HP-UX.

 * Minor documentation fixes.

Qt 1.31 is released both as a complete archive, and as patches to
Qt 1.30. The patches are in unified diff format. Note that the patches
contain source code fixes only. Documentation fixes are included
in the complete archive.
";

    print MAIL "
Note that you may have to use \"patch -p0\" on Windows. 
"   if ( $platform =~ /w/ );

    print SSH "mkdir ", $key, "\n";


    if ( $platform =~ /w/ ) {
	print SSH "ln $sourcedir/$winfile $key\n";
	print SSH "ln $sourcedir/$winpatch $key\n"	if ( $winpatch );

	print MAIL "
Here is a URL for the complete Windows version (2.4 MB):

   ftp://ftp.troll.no/.private/$key/$winfile
";
	print MAIL "
Here is a URL for the Windows patch (8 kB):

   ftp://ftp.troll.no/.private/$key/$winpatch
"	if ( $winpatch );
    }

    if ( $platform =~ /x/ ) {
	print SSH "ln $sourcedir/$xfile $key\n";
	print SSH "ln $sourcedir/$xpatch $key\n" if ( $xpatch );
	print MAIL "
Here is a URL for the complete X11 version (1.9 MB):

   ftp://ftp.troll.no/.private/$key/$xfile
";
	print MAIL "
Here is a URL for the X11 patch (10 kB):

   ftp://ftp.troll.no/.private/$key/$xpatch
"	if ( $xpatch );
    }


    print MAIL "
",$message,"
";
    close MAIL;
}

close SSH;




