#!/bin/sh
# 
# Copyright 1997 Troll Tech AS.  All rights reserved.
#

cd ${QTDIR}
unset CPLUS_INCLUDE_DIR
QT_VERSION=`perl -n -e 'if (/#define\s+QT_VERSION\s+(\d)(\d+)/) { $maj=$1; $min=$2; $min =~ s/00/0/; print "$maj.$min\n";}' src/tools/qglobal.h`

exec > Makefile

cat <<EOF
# -*- makefile -*-
#
# Main Makefile for building the Qt library, examples and tutorial.
# Read PORTING for instructions how to port Qt to a new platform.


all: moc src tutorial examples

moc: variables FORCE
	cd src/moc; \$(MAKE)
	cp src/moc/moc bin/moc

src: moc variables FORCE
	cd \$@; \$(MAKE)

tutorial examples: src FORCE
	cd \$@; \$(MAKE)

clean:
	-rm variables
	cd src/moc; \$(MAKE) clean
	cd src; \$(MAKE) clean
	cd tutorial; \$(MAKE) clean
	cd examples; \$(MAKE) clean

depend:
	cd src; \$(MAKE) depend
	cd tutorial; \$(MAKE) depend
	cd examples; \$(MAKE) depend

config: variables
	-rm variables
	\$(MAKE)

variables: Makefile
	@echo
	@echo These targets are available:
	@echo
	@ls configs
	@echo
	@echo Make any of them to configure Qt for building.  The make process
	@echo will now abort with an error.
	@echo
	@exit 1


# individual targets

EOF

for a in configs/* ; do
	A=`echo $a | sed -e 's-.*/--'`
	echo ${A}: Makefile
	echo '	./propagate configs/'${A}
	echo
done

cat <<EOF

dep: depend

FORCE:


EOF
