#!/usr/bin/perl -w

# $Id: //depot/qt/main/util/scripts/make-public-thing#2 $

use File::Find;

sub copy {
    if ( $_ ne "." && $_ ne ".." && $_ ne "Attic" ) {
	my $dir = $File::Find::dir;
	$dir =~ s-/?$-/-;
	$dir =~ s-^.*/qt/-$base/cvs/qt/-;
	if ( -d $_ ) {
	    mkdir("$dir$_", 0755);
	} elsif ( /,v$/ && !/_win/ && -d $dir && open( I, "< $_" ) ) {
	    my $f;
	    my $v;
	    $f = join( "", <I> );
	    $v = $f;
	    $v =~ s/\nsymbols[^;]*/\nsymbols/s;
	    close(I);
	    open( O, "> $dir$_" ) || die "could not open $dir$_, stopped";
	    print O $v;
	    close O;
	    $v = $f;
	    $f =~ s/;\s*\nlocks.*$/\n/s;
	    $f =~ s/^.*\bsymbols\b\s*//s;
	    $f =~ s/\s+/  /gs;
	    while ( $f =~ / ([a-zA-Z][-a-zA-Z0-9]*):((?:\d+\.)*)0\.2 /g ) {
		print "rcs -o${2}2.1: $dir$_\n";
		print SH "rcs -o${2}2.1: $dir$_\n";
	    }
	    $v =~ s/.*?\ncomment[^\n]*\n\s*//s;
	    $v =~ s/\n\ndesc\n.*$//s;
	    $v =~ s/\ndate\s+(\d+)\.(\d+)\.(\d+)\..*?\n\n/ $1$2$3\n/gs;
	    foreach $f ( split( /\n/, $v ) ) {
		if ( $f =~ /^(\S+)\s+(\d+)$/ && $2 < $date ) {
		    print "rcs -o1.1:$1 $dir$_\n";
		    print SH "rcs -o1.1:$1 $dir$_\n";
		    last;
		}
	    }
	}
    }
}

die '$TMAKEDIR not set - need $TMAKEDIR/lib/linux-g++/tmake.conf';
    if ( ! -f "$ENV{TMAKEDIR}/lib/linux-g++/tmake.conf" );

($junk, $junk, $junk, $d, $m, $y, $junk, $junk, $junk) =
  localtime( time() - 30 * 86400 );
$date = sprintf( "%2d%02d%02d", $y, 1+$m, $d );

$base = "/tmp/striptree-$$";
mkdir( $base, 0755 );
mkdir( "$base/cvs", 0755 );
mkdir( "$base/cvs/qt", 0755 );
mkdir( "$base/cvs/CVSROOT", 0755 );

open( SH, "| sh" );

find( \&copy, "/local/lib/cvs/qt" );

print SH "cd $base/cvs/qt
mv dist/free/LICENSE,v .
co -u LICENSE
rm -f LICENSE,v
cd ..
mkdir $base/head
cd $base/head
cvs -Q -d $base/cvs co qt
mkdir qt/doc/html
cd qt
cp gif/*.gif doc/html
export QTDIR=$base/head/qt
make -C src include

# Generate and check-in documentation
perl util/qdoc/qdoc
cd doc/html
mkdir $base/cvs/qt/html
cp /local/lib/cvs/qtpub/html/* $base/cvs/qt/html
for B in *.html
do
  ci -mnone -t-'' -u \$B ../../../../cvs/qt/html/\${B},v
done
cd ../..

# Generate and check-in X11 Makefiles
export QTDIR=$base/cvs/qt
for B in `util/scripts/makeunixmake -p`
do
  cd \$(dirname \$B)
  ci -mnone -t-'' -u \$(basename \$B)
done

cd $base/cvs/qt
mv gif/*.gif,v html
rm -rf bin bugs dist doc.conf,v etc iconify listview mlined netscape nsplugin printpicture reqs tests util
";
