#!/bin/sh
# 
# Copyright 1997 Troll Tech AS.  All rights reserved.
#

VERBOSE=
LIST=
SUBARGS=
SYMLINKS=
while [ -n "$1" ]
do
    case "$1" in
       -v) VERBOSE=1
    ;; -p) LIST=1
	    SUBARGS="$SUBARGS $1"
    ;; -s) SYMLINKS="symlinks "
    esac
    shift
done

cd ${QTDIR}
unset CPLUS_INCLUDE_DIR
QT_VERSION=`perl -n -e 'if (/#define\s+QT_VERSION\s+(\d)(\d+)/) { $maj=$1; $min=$2; $min =~ s/00/0/; print "$maj.$min\n";}' src/tools/qglobal.h`

if [ -n "$LIST" ] ; then echo Makefile ; fi

exec > Makefile

cat <<EOF
# -*- makefile -*-
#
# Main Makefile for building the Qt library, examples and tutorial.
# Read PORTING for instructions how to port Qt to a new platform.


all: $SYMLINKS moc src tutorial examples
	@echo
	@echo "The Qt library is now built in ./lib"
	@echo "The Qt examples are built in the directories in ./examples"
	@echo "The Qt tutorials are built in the directories in ./tutorial"
	@echo
	@echo "Enjoy!   - the Troll Tech team"
	@echo

moc: variables FORCE
	cd src/moc; \$(MAKE)
	cp src/moc/moc bin/moc

symlinks:
	@cd include; rm -f q*.h; ln -s ../src/*/q*.h .

src: moc variables FORCE
	cd \$@; \$(MAKE)

tutorial examples: src FORCE
	cd \$@; \$(MAKE)

clean:
	-rm variables
	cd src/moc; \$(MAKE) clean
	cd src; \$(MAKE) clean
	cd tutorial; \$(MAKE) clean
	cd examples; \$(MAKE) clean

depend:
	cd src; \$(MAKE) depend
	cd tutorial; \$(MAKE) depend
	cd examples; \$(MAKE) depend

config: variables
	-rm variables
	\$(MAKE)

variables: Makefile
	@echo
	@echo These targets are available:
	@echo
	@cd configs; ls *-*-*
	@echo
	@echo Make any of them to configure Qt for building.
	@echo
	@echo If you build Qt now reading of GIF images will not be
	@echo supported. Please see the file src/kernel/qt_gif.h
	@echo if you want to enable GIF reading support.
        @echo
        @echo The make process will now abort with an error.
	@echo
	@exit 1


# individual targets

EOF

# Explicit rules, for sucky makes...
for a in $(cd configs; ls); do
	echo ${a}: Makefile
	echo '	./propagate configs/'${a}
	echo
done

# Implicit...
echo '%-static: configs/%-shared'
echo '	./propagate configs/$*'
echo
echo '%-static: configs/%-shared'
echo '	./propagate configs/$*'
echo
echo '%-debug: configs/%-debug'
echo '	./propagate configs/$*'
echo

cat <<EOF

dep: depend

FORCE:


EOF
