#!/bin/sh


cd $QTDIR
PACKDIR=/tmp/qt-embedded-demo
rm -rf $PACKDIR
TOP=$PACKDIR/qt-embedded

mkdir -p $TOP/etc/fonts
mkdir -p $TOP/lib
mkdir -p $TOP/examples
mkdir -p $TOP/doc

#echo "WARNING: including all TTF and BDF fonts"
#cp dist/embedded/etc/fonts/*.ttf $TOP/etc/fonts
#cp dist/embedded/etc/fonts/*.bdf $TOP/etc/fonts

cp dist/embedded/etc/fonts/*.qpf $TOP/etc/fonts
cp dist/embedded/etc/fonts/fontdir $TOP/etc/fonts
cp dist/embedded/etc/fonts/babelfish.ttf $TOP/etc/fonts
cp -r dist/embedded/etc/qimpen $TOP/etc
cp -r doc/html $TOP/doc
cp -a lib/libqt.so* $TOP/lib
cp -a /lib/libm.so* $TOP/lib
cp -a /lib/libc.so* $TOP/lib
cp -a /lib/lib[cm]-2.* $TOP/lib
cp -a /usr/lib/libstdc++.so $TOP/lib
cp -a /usr/lib/libstdc++.so.2 $TOP/lib
cp -a /usr/lib/libstdc++.so.2.9 $TOP/lib
cp -a /usr/lib/libstdc++.so.2.9.0 $TOP/lib
strip $TOP/lib/*

for i in $( cd examples; echo * )
do
    if [ -d examples/$i -a -x examples/$i/$i -a ! -f examples/$i/NOT_IN_DEMO ]
    then
	mkdir $TOP/examples/$i
	cp examples/$i/$i $TOP/examples/$i
	strip $TOP/examples/$i/$i
	cp examples/$i/*.gif $TOP/examples/$i 2>/dev/null
	cp examples/$i/*.png $TOP/examples/$i 2>/dev/null
	cp examples/$i/*.xpm $TOP/examples/$i 2>/dev/null
	cp examples/$i/*.txt $TOP/examples/$i 2>/dev/null
	cp examples/$i/*.qm $TOP/examples/$i 2>/dev/null
	cp examples/$i/*.im $TOP/examples/$i 2>/dev/null
	cp examples/$i/*.mpg $TOP/examples/$i 2>/dev/null
	cp examples/$i/all $TOP/examples/$i 2>/dev/null
    fi
done

cp examples/launcher/start_demo $TOP
cp dist/embedded/FAQ $TOP
cp dist/embedded/HOWTO-* $TOP
cp dist/embedded/INSTALL $TOP
cp dist/embedded/README $TOP
cd $PACKDIR
echo "Packing $TOP ..."
tar cfz $PACKDIR.tar.gz *
echo "Created $PACKDIR.tar.gz"
