#!/bin/sh

VERBOSE=
LIST=
SUBARGS=
while [ -n "$2" ]
do
    case "$1" in
       -v) VERBOSE=1
    ;; -p) LIST=1
	    SUBARGS="$SUBARGS $1"
    ;; -s)  SUBARGS="$SUBARGS $1"
    esac
    shift
done

PLATFORM=$1

if [ "$PLATFORM" = "qws" ]
then
    PLATPRO=-e
else
    PLATPRO=
fi

if [ -n "$VERBOSE" ] ; then echo 'Building top-level make files...' >&2; fi

export UNIX_MKDIST_QT=1
export TMAKEPATH=$QTDIR/tmake:$TMAKEPATH
( cd $QTDIR/src/moc; tmake moc.pro >Makefile.in)
if [ -n "$LIST" ] ; then echo 'src/moc/Makefile.in' ; fi

$QTDIR/util/scripts/mkconfigs $SUBARGS $PLATFORM
$QTDIR/util/scripts/makemake $SUBARGS $PLATFORM

(cd $QTDIR/src; perl -p -i -e 's/(^CONFIG\s+\+=\s*png\s+zlib)/\# $1/' qt$PLATPRO.pro; tmake -t ../tmake/propagate.t qt$PLATPRO.pro | perl -p -e "s{$QTDIR}{\\\$(QTDIR)}" >Makefile.in )
if [ -n "$LIST" ] ; then echo 'src/Makefile.in' ; fi

cp -f $QTDIR/util/scripts/configure $QTDIR
if [ -n "$LIST" ] ; then echo 'configure' ; fi

if [ -n "$VERBOSE" ] ; then echo "Build tutorial, example, and extensions Makefiles" >&2 ; fi

cd $QTDIR
find tutorial \
 src/util \
 examples \
 extensions -name '*.pro' |
    while read pro_file
    do
	(
	DIR=$(dirname $pro_file)
	cd $DIR # we are in a subshell
	TEMPLATE=$(echo $(basename $DIR).t)
	if [ ! -f $TEMPLATE ]
	then
	    TEMPLATE=$QTDIR/tmake/propagate.t
	fi
	tmake -t ${TEMPLATE} $tmakearg $(basename $pro_file) > Makefile.in
        if [ -n "$LIST" ] ; then echo "$DIR/Makefile.in" ; fi
	)
    done

# #### redo for some reason
# Don't know why, but this _is_ necessary
(cd examples; tmake $tmakearg examples.pro > Makefile.in )
(cd tutorial; tmake $tmakearg tutorial.pro > Makefile.in )
(cd extensions/opengl/examples; tmake $tmakearg examples.pro > Makefile.in )
(cd extensions/xt/examples; tmake $tmakearg examples.pro > Makefile.in )
