#!/bin/sh

cd $QTDIR

#p4 sync ...
#p4 resolve -am ...


examples="aclock addressbook application buttongroups  canvas checklists cursor customlayout dclock dirview drawdemo drawlines dumbterm  fileiconview hello helpviewer i18n iconview kiosk launcher layout life lineedits listbox  listboxcombo listviews mdi memmeter menu movies multidoc picture popup progress progressbar qdir qfd qmag qwerty rangecontrols richtext rot13 scribble scrollview sheet showimg splitter tabdialog table tetrix themes tictac  tooltip validator widgets winmanager wizard xform"

tutorials="t1 t2 t7 t14"



make -C src/moc
make -C src release
make -C util/qws release
for name in  $examples; do make -C examples/$name release; done
#for name in  $tutorials; do make -C tutorial/$name release; done

cd ..

rm -rf qt-embedded
mkdir qt-embedded

mkdir qt-embedded/server

echo copying...

cp qws/util/qws/qws qt-embedded/server
cp qws/util/qws/startserver qt-embedded/server
cp qws/util/qws/*.html qt-embedded/server
cp qws/util/qws/*.gif qt-embedded/server

cp qws/GNUmakefile.inc qt-embedded

cp qws/dist/*.embedded qt-embedded
rm -f qt-embedded/GNUmakefile.embedded

mkdir qt-embedded/include
cp qws/include/*.h qt-embedded/include
rm -f qt-embedded/include/qgfx*.h
rm -f qt-embedded/include/qws*.h qt-embedded/include/*_qws.h
rm -f qt-embedded/include/*_ttf.h
rm -f qt-embedded/include/jri*.h qt-embedded/include/np*.h
rm -f qt-embedded/include/dlmalloc.h

mkdir qt-embedded/bin
cp qws/src/moc/moc qt-embedded/bin

mkdir qt-embedded/lib
cp -a qws/lib/libqt* qt-embedded/lib

echo examples

mkdir qt-embedded/examples
for name in  $examples; do (mkdir qt-embedded/examples/$name;  cp qws/examples/$name/* qt-embedded/examples/$name; strip qt-embedded/examples/$name/$name); done

rm qt-embedded/examples/*/moc_*
rm qt-embedded/examples/*/*.moc

#echo tutorial

#mkdir qt-embedded/tutorial
#for name in  $tutorials; do (mkdir qt-embedded/tutorial/$name;cp qws/tutorial/$name/* qt-embedded/tutorial/$name); done

echo Packing the archive...

tar cfz  qt-embedded.tar.gz qt-embedded

