#!/bin/bash

REL_VERSION=0.0.0
BRANCH=
OUT_TREE=`pwd`
LOCAL_TREE=
DO_DOC=yes
DO_WIN=yes
DO_X11=yes
DO_MAC=no
DO_QWS=yes
DO_FREE=yes
DO_GZIP=yes
TMP_FILE=/tmp/tmpf-$$

die()
{
    echo $1
    exit 666
}

#parse commandline
showhelp()
{
    [ ! -z "$1" ] && echo "Unknown Option: $1"
    echo "$0 [options]"
    echo
    echo "Options:"
    echo "-local <directory>"
    echo "-outdir <directory>"
    echo "-nodoc"
    echo "-nowin"
    echo "-nox11"
    echo "-noqws"
    echo "-nofree"
    echo "-nogzip"
    exit 666
}

while [ -n "$1" ]; do
   case $1 in
   -version)
       shift
       VAR=version
       VAL=$1
       ;;
   -help)
       showhelp
       ;;
   -outdir)
	shift
	VAR=outdir
	VAL=$1
	;;
   -local)
	shift
	VAR=local
	VAL=$1
	;;
   -no*)
	VAR=`echo $1 | sed "s,^-no-*,,g"`
	VAL=no
	;;
   -do*)
	VAR=`echo $1 | sed "s,^-do-*,,g"`
	VAL=yes
	;;
   --*=*)
	VAR=`echo $1 | sed "s,^--\(.*\)=.*$,\1,"`
	VAL=`echo $1 | sed "s,^--.*=\(.*\)$,\1,"`
	;;
   *)
	showhelp $1
	;;
   esac
   shift

   case $VAR in
   doc) DO_DOC=$VAL ;;
   win) DO_WIN=$VAL ;;
   x11) DO_X11=$VAL ;;
   mac) DO_MAC=$VAL ;;
   qws) DO_QWS=$VAL ;;
   free)DO_FREE=$VAL;;
   gzip)DO_GZIP=$VAL;;
   version)
       expr "$VAL" : ".*\.\d*" >/dev/null 2>&1 || die "Can't figure out version from $VAL"
       REL_VERSION=$VAL
       BRANCH=`echo $VAL | sed "s,\([0-9]*\.[0-9]*\).*,\1,"`
       LABEL="qt/$VAL";;
   local)
       [ -d "$VAL" ] || die "Unknown directory: $VAL"
       BRANCH="0.0.0"
       LOCAL_TREE=$VAL;;
   outdir)
	[ ! -d "$VAL" ] && mkdir -p "$VAL"
	OUT_TREE=$VAL;;
   esac
done
BRANCH="main"

BRANCH_DIGITS=`echo $BRANCH | sed "s,\.,,g" | sed "s,\(\d\d\d\).*,\1,"`
MYNAME=`whoami`
[ -z $MYNAME ] && MYNAME="shellssuck"
DISTDIR="/tmp/qt-$BRANCH-$MYNAME-$$"

#Checkout P4
if [ -z $LOCAL_TREE ]; then
    if ! p4 fstat //depot/qt/$BRANCH/doc.conf 2>&1 | grep " depotFile " >/dev/null 2>&1 ; then
	die "//depot/qt/$BRANCH/... is not in the depot, stopped"
    fi
    if ! p4 labels 2>&1 | grep "^Label $LABEL" >/dev/null 2>&1 ; then
	die "Label $LABEL does not exist, stopped"
    fi
    checkoutlabel=""
    if p4 label -o $LABEL | grep '^Options:.*locked' >/dev/null 2>&1; then
	checkoutlabel="@${LABEL}"
    fi
    echo "Exporting the entire Qt depot $checkoutlabel..";

    tmpclient="qt-release-tmp-$MYNAME";
    p4 client -t qt-release-3x -o $tmpclient >/tmp/tmp_file
    sed /tmp/tmp_file -e "s,^Root:.*,Root: $DISTDIR," -e "s,/qt/X.Y/,/qt/$BRANCH/,g" \
	    -e "s,^\(Client: \).*,\1qt-release-tmp-$$," -e "s,\bnomodtime\b,modtime," | \
      p4 -s client -i >/dev/null 2>&1

    p4 -s -c $tmpclient sync -f $DISTDIR/qt/...${checkoutlabel} >/dev/null 2>&1
else
    echo "Copying Qt depot.."
    [ ! -d $DISTDIR/qt ] && mkdir -p $DISTDIR/qt
    cp -ar $LOCAL_TREE $DISTDIR/qt
fi


#get include files
includefiles=`QTDIR=$DISTDIR/qt $DISTDIR/qt/bin/syncqt -show`
[ ! -d $DISTDIR/qt/include ] && mkdir -p "$DISTDIR/qt/include"
for fullname in $includefiles; do
    ln -sf "../$fullname" "$DISTDIR/qt/include/`basename $fullname`"
done

#Generate documentation
mkdir -p "$DISTDIR/qt/doc"
mkdir -p "$DISTDIR/qt/doc/html"
mkdir -p "$DISTDIR/qt/doc/man"
mkdir -p "$DISTDIR/qt/doc/html/designer"
mkdir -p "$DISTDIR/qt/doc/html/designer/figures"
mkdir -p "$DISTDIR/qt/doc/html/designer/arrows"
mkdir -p "$DISTDIR/qt/doc/man/man3"
# and do the moc.1 hack here
mkdir -p "$DISTDIR/qt/doc/man/man1"
mv "$DISTDIR/qt/src/moc/moc.1" "$DISTDIR/qt/doc/man/man1"
if [ "x$DO_DOC" = "xyes" ]; then
    cp $DISTDIR/qt/tools/designer/manual/*.html $DISTDIR/qt/doc/html/designer
    cp $DISTDIR/qt/tools/designer/manual/figures/*.png $DISTDIR/qt/doc/html/designer/figures
    cp $DISTDIR/qt/tools/designer/manual/arrows/*.png $DISTDIR/qt/doc/html/designer/arrows
    rm -rf $DISTDIR/qt/tools/designer/manual
    rm -rf $DISTDIR/qt/tools/designer/doc

    echo "Running qdoc..";
    $QTDIR/util/qdoc/qdoc $DISTDIR/qt/util/qdoc/qdoc.conf >/dev/null 2>&1 || die "could not run qdoc, stopped"
    $DISTDIR/qt/util/qdoc/man  $DISTDIR/qt >/dev/null 2>&1 || die "could not run man, stopped"

    find $DISTDIR/qt/gif -exec mv {} $DISTDIR/qt/doc/html/ \; >/dev/null 2>&1
fi

# Replace Netscape-owned code with dummies (direct user to PluginSDK)
for a in `find $DISTDIR/qt/extensions/nsplugin/src -name 'np*' -o -name 'jri*'`; do
    rm -f $a
    echo "#error \"$a must be provided by Netscape\"" > $a
    echo "#error \"This file is just a placeholder. Please see the documentation\"" >>$a
    echo "#error \"to learn how to obtain the real file\"" >>$a
done

# qt.h
rm -f "$DISTDIR/qt/include/qt.h"

#qgif.h
qgif="$DISTDIR/src/kernel/qgif.h"
if [ -e  "$qgif" ]; then
    sed "s,\(\#define QT_BUILTIN_GIF_READ[ ]*\)$,\1 0,g" $qgif >${TMP_FILE}
    mv ${TMP_FILE} $qgif
fi

# changes files
[ ! -f "$DISTDIR/qt/dist/changes-$BRANCH" ] && echo "Warning: qt/dist/changes-$BRANCH does not exist"
for a in `find $DISTDIR/qt/dist/ -name 'changes-$(echo $BRANCH | sed "s,^\([0-9\.]\)*,\1,")*'`; do
    mv $a $DISTDIR/qt/`basename $a`
done

# fixify qglobal's version number
qglobal="$DISTDIR/qt/src/tools/qglobal.h"
sed -e "s,\(\#define\s*QT_VERSION\s*\)[0-9]*,\1$BRANCH_DIGITS,g" \
    -e "s,\(\#define\s*QT_VERSION_STR\s+\"\)\([0-9.]*\),/1$BRANCH,g" $qglobal >${TMP_FILE}
mv ${TMP_FILE} $qglobal
type=`grep QT_VERSION_STR $DISTDIR/qt/src/tools/qglobal.h | awk '{ print $3 }' | sed 's,["0-9.]*\(-.*\)",\1,'`
if [ "$type" != "-snapshot" ] && ! myexpr "$type" : "^-beta[0-9]*$"; then
    die "The qt version is ${BRANCH}${type}, which confuses me terribly";
fi

#fix $Id
echo "Marking \$ID\$..."
for a in `find $DISTDIR/qt/`; do
    if [ -f $a ] && [ ! -L $a ] && grep '\$Id.*\$' $a >/dev/null 2>&1; then
	execut="no"
	[ -x $a ] && execut="yes"

	mtime=`ls -l $a | awk '{ print $6,$7,$8 }'` #mtime is pretty bogus, but a quick hack..
	tag_ID="`echo $a | sed "s,^.*/,qt/,"`   ${REL_VERSION}${type}   edited $mtime"
	sed "s,\(\$Id[:] \)[^\\$]*\\$,\1 ${tag_ID} \$,g" $a >${TMP_FILE}
	rm -f $a
	mv ${TMP_FILE} $a
	if [ "$execut" = "yes" ]; then
	    chmod 555 $a
	else
	    chmod 444 $a
	fi
    fi
done

myexpr () {
    echo "$1" | egrep "$3" >/dev/null 2>&1
    return
}

public_file () {
    { [ ! -e "$1" ] || [ -d "$1" ] ; } && return 1

    file_WHOLE=$1
    file_BASE=`basename $file_WHOLE`
    file=`echo $file_WHOLE | sed "s,^$DISTDIR/qt/,,"`
    { [ -z $file ] || [ $file = "/" ] ; } && return 1
    KEEP=

    if
	 # no qdoc conf
	 [ "$file_BASE" = "doc.conf" ] ||

	 # no make.help
	 [ "$file_BASE" = "make.help" ] ||

	 # Everything under dist
	 myexpr "$file" : '^dist\/' ||

	 # no tests
	 myexpr "$file" : '^tests\/.*' ||

	 # utils, except scripts
	 { myexpr "$file" : '^util\/' && ! myexpr "$file" : '^util\/scripts\/' ; } ||

	 # no ~ files
	 myexpr "$file_BASE" : '.*~$' ||

	 # no gif
	 myexpr "$file" : 'gif\/' ||

	 # no configs
	 myexpr "$file" : 'configs\/' ||
	 [ "$file" = "LICENSE.TROLL" ] ||

	 # no makefiles, except freetype2
	 { [ "$file_BASE" = "GNUmakefile" ] && myexpr "$file" : 'src\/3rdparty\/freetype2\/' ; }   ||
	 { [ "$file_BASE" = "GNUmakefile-kde" ] && myexpr "$file" : 'src\/3rdparty\/freetype2\/' ; } ||
	 { [ "$file_BASE" = "Makefile" ] && myexpr "$file" : 'src\/3rdparty\/freetype2\/' ; } ||
	 myexpr "$file" : 'src\/Makefile\..*' ||

	 # no mak files
	 { myexpr "$file_BASE" : '.*\.mak$' && ! myexpr "$file_BASE" : '.*\/libpng\/' ; } ||

	 # no *.inc files
	 myexpr "$file_BASE" : '.*\.inc$' ||

	 # some bins
	 myexpr "$file_BASE" : 'bin\/.*_make_.*$' ||
	 myexpr "$file" : 'bin\/syncqt.*$' ||
	 myexpr "$file" : 'bin\/qmake$'
     then
	    KEEP=no
     elif
	 # for the love of god! keep qmake! all hail qmake!
	 myexpr "$file" : "^qmake\/" || 

	 # the scripts, for now
	 myexpr "$file" : "^util\/scripts\/" ||

	 # everything in the subdirectories of src/doc/
	 { myexpr "$file" : "^src\/doc\/" && [ ! "$file_BASE" = "Makefile" ] ; } ||

	 # all c++ files under .../src/
	 myexpr "$file" : "\(^|\/\)src\/.*\.\(\(cpp\)|h|c|\(pro\)\)$" ||
	 myexpr "$file" : "\(^|\/\)src\/qt\.t$" ||

	 # include (empty)
	 [ "$file" = "include" ] ||

	 # all doc files except in tests
	 myexpr "$file_BASE" : ".*\.doc$" ||

	 # the changes files
	 myexpr "$file" : "^changes-" ||

	 # /configure
	 [ "$file" = "configure" ] ||

	 # the tools files
	 myexpr "$file" : "^tools\/.*\.\(\(cpp\)|h|\(pro\)|\(qm\)|\(po\)|\(xpm\)|\(xbm\)|\(png\)|\(bmp\)|\(gif\)|\(ui\)|1|\(txt\)|\(html\)|\(css\)\)$" ||
	 myexpr "$file" : "^tools\/designer\/integration\/.*\.\(\(clw\)|\(def\)|\(odl\)|\(rc\)|\(dsp\)|\(rc2\)|\(el\)|t\)" ||
	 myexpr "$file" : "^tools\/.*\/README" ||
	 myexpr "$file" : "^tools\/.*\/COPYING" ||
	 myexpr "$file" : "^tools\/.*\/HTML.manifest$" ||
	 myexpr "$file" : "^tools\/.*\/mkimages$" ||
	 myexpr "$file" : "^tools\/.*\/makeall$" ||
	 myexpr "$file" : "^tools\/designer\/designer\/.*\.\(\(rc\)|\(ico\)\)$" ||
	 myexpr "$file" : "^tools\/.*\/mksplash$" ||

	 # the tutorials
	 myexpr "$file" : "^tutorial\/t[0-9]*\/$" ||
	 # all c++ and pro files under tutorial
	 myexpr "$file" : "^tutorial\/.*\.\(\(cpp\)|h|\(pro\)\)$" ||

	 # the examples
	 myexpr "$file" : "^examples\/.*\/$" ||
	 # all c++, pro, qm, po and xpm files under examples
	 myexpr "$file" : "^examples\/.*\.\(\(cpp\)|h|\(pro\)|\(qm\)|\(po\)|\(xpm\)|\(map\)|\(txt\)|\(bmp\)|\(gif\)|\(pic\)|\(ppm\)|\(png\)|\(wav\)|\(any\)|\(xml\)\)$" ||
	 # all the junk from mpegplay in the kiosk example
	 myexpr "$file" : "^examples\/kiosk\/.+\..+$" ||
	 myexpr "$file" : "^examples\/kiosk\/README.*$" ||
	 myexpr "$file" : "^examples\/kiosk\/tags$" ||
	 # all the launcher files
	 myexpr "$file" : "^examples\/launcher\/.*\(\(\.im\)|\(\.pl\)|\(perpetual_launch\)|\(start_demo\)\)$" ||
	 # misc
	 [ "$file" = "examples/load/isdninfo" ] ||
	 myexpr "$file" : "examples/overlay_x11/README" ||
	 myexpr "$file" : "examples\/.*\.c$" ||

	 # the extensions
	 myexpr "$file" : "^extensions\/.*\/$" ||
	 # all c++, pro, qm, po and xpm files under extensions
	 myexpr "$file" : "^extensions\/.*\.\(\(cpp\)|h|\(pro\)|\(qm\)|\(po\)|\(xpm\)|\(map\)|\(txt\)|\(bmp\)|\(gif\)|\(pic\)|\(ppm\)|\(png\)|\(wav\)|\(any\)|c\)$" ||
	 myexpr "$file" : "^extensions\/.*\/isdninfo$" ||

	 # READMEs, NOTICE and such
	 myexpr "$file" : "^src\/\(\(.*\/\)|\)[A-Z]+$" ||
	 myexpr "$file" : "^src\/\(\(.*\/\)|\)[A-Z]+$" ||
	 myexpr "$file" : "^examples\/\(\(.*\/\)|\)[A-Z]+$" ||
	 myexpr "$file" : "^tutorial\/\(\(.*\/\)|\)[A-Z]+$" ||
	 myexpr "$file" : "^extensions\/\(\(.*\/\)|\)[A-Z]+$" ||
	 myexpr "$file" : "^extensions\/.*\/README\..*$" ||

	 # the moc
	 myexpr "$file" : "^src\/moc\/.*\.\(1|l|t|y\)$" ||

	 # All of tmake
	 myexpr "$file" : "^tmake\/" ||

	 # 3rdparty
	 myexpr "$file" : "src\/3rdparty\/$" ||
	 myexpr "$file" : "src\/3rdparty\/.*README$" ||
	 myexpr "$file" : "src\/3rdparty\/libmng\/" ||
	 myexpr "$file" : "src\/3rdparty\/libpng\/" ||
	 myexpr "$file" : "src\/3rdparty\/freetype2\/" ||
	 { myexpr "$file" : 'src\/3rdparty\/zlib\/' && [ ! "$file_BASE" = "Makefile" ] ; } ||
	 # More  of nsplugin example
	 myexpr "$file" : "extensions\/nsplugin\/examples\/.*\.\(\(mng\)|\(def\)|\(rc\)|\(cgi\)|\(g1n\)\)$" ||

	 # some bins
	 myexpr "$file" : "bin\/$" ||
	 myexpr "$file" : "bin\/findtr$" ||
	 myexpr "$file" : "bin\/qt20fix$" ||
	 myexpr "$file" : "bin\/qtrename140$"
     then
	 KEEP=yes
     fi

     #fall back to asking..
     if [ -z "$KEEP" ]; then
	 echo -n "I've no idea what to do with $file, keep it? (yes or no): "
	 read KEEP
     fi
      [ "$KEEP" = "yes" ] && return 0
     return 1
}

for plat in mac win x11 qws; do
    #handle commandline options
    PLATNAME=qt-${plat}-enterprise-${REL_VERSION}${type}
    PLATDIR=$DISTDIR/$PLATNAME
    free=no
    plat2=
    case $plat in
    mac)
	[ "x$DO_MAC" = "xyes" ] || continue
	plat2=unix
	;;
    qws)
	[ "x$DO_QWS" = "xyes" ] || continue
	plat2=unix
	free=$DO_FREE
	;;
    x11)
	[ "x$DO_X11" = "xyes" ] || continue
	plat2=unix
	free=$DO_FREE
	;;
    win)
	[ "x$DO_WIN" = "xyes" ] || continue
	;;
    *) die "Will probably need more info to package: $plat!" ;;
    esac
    echo "****** Packing for platform: $plat ****"

    echo "Removing unnecesary stuff.."
    for a in `find $DISTDIR/qt`; do
	[ -d $a ] && continue

	#Remove the platform dependent files
	if myexpr "$a" : '*_[a-z1]*.cpp' || myexpr "$a" : '*_[a-z1]*.h' || myexpr "$a" : '*_[a-z1]*.c'; then
	    match=`basename $a | sed "s,.*_,," | cut -d'.' -f1`
	    case $match in
	    mac|x11|unix|win|qws) [ "$match" != "$plat" ] && [ "$match" != "$plat2" ] && continue ;;
	    *) ;;
            esac
	fi

	#Remove non-dist files (tests-dir, util-dir, ... )
	if public_file $a; then
	    d=${PLATDIR}/`dirname "$a" | sed "s,^${DISTDIR}/qt,,"`
	    [ ! -d $d ] && mkdir -p $d
	    cp -a "$a" "$d/`basename $a`"
        fi
    done

    #cleanup some static things..
    rm -rf "$PLATDIR/examples/kiosk"
    rm -rf "$PLATDIR/src/3rdparty/libmng"
    rm -f "$PLATDIR/etc/fonts/unifont.bdf"
    rm -rf "$PLATDIR/tmake"
    rm -rf "$PLATDIR/util"
    mkdir -p $PLATDIR/lib
    echo "If this directory is empty, you forgot to build the Qt library" >$PLATDIR/lib/README
    if [ "$plat" = "x11" ] || [ "$plat" = "qws" ]; then
	if [ "$plat" = "x11" ]; then
	    rm -rf "$PLATDIR/examples/biff"
	    rm -rf "$PLATDIR/examples/desktop"
	    rm -rf "$PLATDIR/examples/overlay_x11"
	    rm -rf "$PLATDIR/extensions/xt"
	elif [ "$plat" = "qws" ]; then
	    rm -rf "$PLATDIR/examples/winmanager"
	    rm -rf "$PLATDIR/examples/compact"
	    rm -rf "$PLATDIR/examples/notepad"
	    rm -rf "$PLATDIR/examples/launcher"
	    rm -rf "$PLATDIR/extensions/imageio"
	    rm -rf "$PLATDIR/src/3rdparty/freetype2"
	    rm -f "$PLATDIR/src/widgets/qcompactstyle.h"
	    rm -f "$PLATDIR/src/widgets/qcompactstyle.cpp"
	fi
    elif [ "$plat" = "win" ]; then
	rm -rf "$PLATDIR/doc/man"
	#since there is no man pages, move all docs to doc/
	mv $PLATDIR/doc/html/* $PLATDIR/doc
	rm -rf $PLATDIR/doc/html
	# delete the xt estension
	rm -rf "$PLATDIR/extensions/xt"
	rm -f "$PLATDIR/configure"

	# move the files into include
	[ ! -d "$PLATDIR/include" ] && mkdir -p "$PLATDIR/include"
	cp "$PLATDIR/src/tools/qconfig-dist.h" "$PLATDIR/xxx"
	for a in $includefiles; do
	    FILE=$PLATDIR/include/`basename $a`
	    rm -f $FILE
	    mv $PLATDIR/$a $FILE >/dev/null 2>&1
	done
	mv "$PLATDIR/xxx" "$PLATDIR/src/tools/qconfig-dist.h"
    fi

    #don't need empty directories
    find $PLATDIR/ -type d -exec rmdir {} \; >/dev/null 2>&1

    platformname=$plat
    [ "$plat" = "qws" ] && platformname="embedded"
    for d in "$DISTDIR/qt/dist/commercial" "$DISTDIR/qt/dist/$platformname"; do
	[ ! -d $d ] && continue
	for a in `find $d`; do
	    a_file=`echo $a | sed "s,$d,,"`
	    o_file=$a_file
	    [ -z $a_file ] && continue

	    if [ "$plat" = "qws" ]; then
		case `basename $a` in
		LICENSE|MAINIFEST|ANNOUNCE|README.QT|README|LICENSE.QPL) continue ;;
		README.qws) o_file="README" ;;
		esac
	    elif [ "$plat" = "x11" ]; then
		[ `basename $a` = "README.qws" ] && continue
	    elif [ "$plat" = "win" ]; then
		[ `basename $a` = "qmake.cache" ] && o_file=".qmake.cache"
	    fi
	    #do copy
	    o_dir=`dirname $PLATDIR/$o_file`
	    [ ! -d $o_dir ] && mkdir -p $o_dir
	    [ -f $PLATDIR/$o_file ] && rm -f $PLATDIR/$o_file
	    if [ -f $d/$a_file ] && [ ! -e $PLATDIR/$o_file ]; then
		sed -e "s/%YEAR%/$year/g" -e "s/%VERSION%/${BRANCH}${type}/g" \
		    -e "s/$VERSIONWIN%/${BRANCH_DIGITS}/g" $d/$a_file >${TMP_FILE}
		if [ "$type" = "-snapshot" ]; then
		    sed -e "s/%SNAPSHOTONLY\([^%]*\)%/\1/g" -e "s/%STABLEONLY[^%]*%//g" ${TMP_FILE} >$PLATDIR/$o_file
		else
		    sed -e "s/%SNAPSHOTONLY[^%]*%//g" -e "s/%STABLEONLY\([^%]\)*%/\1/g" ${TMP_FILE} >$PLATDIR/$o_file
		fi
	    else
		cp -ar $d/$a_file $PLATDIR/$o_file
	    fi
	done
    done

    echo "Packing enterprise..."
    if [ "$plat" = "x11" ] || [ "$plat" = "qws" ]; then
	cd "$DISTDIR"
	tar cf "$OUT_TREE/${PLATNAME}.tar" "${PLATNAME}"
	[ "$DO_GZIP" = "yes" ] && gzip -c "$OUT_TREE/${PLATNAME}.tar" >"$OUT_TREE/${PLATNAME}.tar.gz"
    elif [ "$plat" = "win" ]; then
	cd "$DISTDIR"
	find "${PLATNAME}" | zip $OUT_TREE/${PLATNAME}.zip -@ >/dev/null 2>&1
    fi

    #Remove database sources
    [ -d "$PLATDIR/src/sql" ] && rm -rf "$PLATDIR/src/sql"

    #do professional
    echo "Packing professional..."
    cd "$DISTDIR"
    OLDPLATDIR=$PLATDIR
    PLATNAME=`echo $PLATNAME | sed "s,enterprise,professional,"`
    PLATDIR=$DISTDIR/$PLATNAME
    mv "$OLDPLATDIR" "$PLATDIR"
    if [ "$plat" = "x11" ] || [ "$plat" = "qws" ]; then
	cd "$DISTDIR"
	tar cf $OUT_TREE/${PLATNAME}.tar ${PLATNAME}
	[ "$DO_GZIP" = "yes" ] && gzip -c $OUT_TREE/${PLATNAME}.tar >$OUT_TREE/${PLATNAME}.tar.gz
    else
	cd "$DISTDIR"
	find "${PLATNAME}" | zip $OUT_TREE/${PLATNAME}.zip -@ >/dev/null 2>&1
    fi

    if [ "x$free" = "xyes" ]; then
	echo "**** Doing free.. ****"

	cd "$DISTDIR"
	OLDPLATDIR=$PLATDIR
	PLATNAME=`echo $PLATNAME | sed "s,professional,free,"`
	PLATDIR=$DISTDIR/$PLATNAME
	mv "$OLDPLATDIR" "$PLATDIR"

	#remove commercial licenses
	for a in `find $DISTDIR/qt/dist/commercial`; do
	    FILE=`echo $a | sed "s,$DISTDIR/qt/dist/commercial,,"`
	    [ -z $FILE ] && continue
	    rm -f $PLATDIR/$FILE
	done

	#copy free licenses
	for a in `find $DISTDIR/qt/dist/free`; do
	    a_file=`echo $a | sed "s,$DISTDIR/qt/dist/free,,"`
	    o_file=$a_file
	    [ -z $a_file ] && continue

	    if [ "$plat" = "qws" ]; then
		case `basename $a` in
		LICENSE|MAINIFEST|ANNOUNCE|README.QT|README|LICENSE.QPL) continue ;;
		README.qws) o_file="README" ;;
		esac
	    elif [ "$plat" = "x11" ]; then
		[ `basename $a` = "README.qws" ] && continue
	    elif [ "$plat" = "win" ]; then
		[ `basename $a` = "qmake.cache" ] && o_file=".qmake.cache"
	    fi
	    #do copy
	    o_dir=`dirname $PLATDIR/$o_file`
	    [ ! -d $o_dir ] && mkdir -p $o_dir
	    [ -f $PLATDIR/$o_file ] && rm -f $PLATDIR/$o_file
	    if [ -f $d/$a_file ] && [ ! -e $PLATDIR/$o_file ]; then
		sed -e "s/%YEAR%/2000/g" -e "s/%VERSION%/${BRANCH}$type/g" \
		    -e "s/%VERSIONWIN%/${BRANCH_DIGITS}/g" $d/$a_file >${TMP_FILE}
		if [ "$type" = "-snapshot" ]; then
		    sed -e "s/%SNAPSHOTONLY\([^%]*\)%/\1/g" -e "s/%STABLEONLY[^%]*%//g" ${TMP_FILE} >$PLATDIR/$o_file
		else
		    sed -e "s/%SNAPSHOTONLY[^%]*%//g" -e "s/%STABLEONLY\([^%]\)*%/\1/g" ${TMP_FILE} >$PLATDIR/$o_file
		fi
	    else
		cp -ar $DISTDIR/qt/dist/free/$a_file $PLATDIR/$o_file
	    fi
	done

	#tar free editions
	echo "Packing..."
	cd "$DISTDIR"
	tar cf $OUT_TREE/${PLATNAME}.tar ${PLATNAME}
	[ "$DO_GZIP" = "yes" ] && gzip -c $OUT_TREE/${PLATNAME}.tar >$OUT_TREE/${PLATNAME}.tar.gz
	echo "** Done with free.. **"
    fi
    echo "(cleaning up after package..)"
    rm -rf $PLATDIR
    echo "******** Done Packaging $plat *********"
done
echo "(mkdists cleanup..)"
rm -rf $DISTDIR
rm -f ${TMP_FILE}
echo "mkdists done"
