#!/bin/sh

p4 sync

echo Removing old directory 

rm -rf qt-embedded
cp -r qt qt-embedded

cd qt-embedded



echo Rearranging

rm -rf etc
mv dist/embedded/* .
rm -rf dist
mv examples/launcher/start_demo .

touch src/moc/GNUmakefile

echo Generating documentation...

QTDIR=$HOME/qt-embedded ./bin/syncqt
QTDIR=$HOME/qt-embedded ./util/qdoc/qdoc
rm include/*

cp gif/*.png doc/html

echo Removing platform specific files.

rm -f src/*/*_mac*
rm -f src/*/*_win*
rm -f src/*/*_x11*

echo Removing unnecessary files.

rm -rf util
rm -rf tests
rm -rf gif
rm -rf extensions/nsplugin
rm -rf extensions/xt
rm -rf extensions/xembed
rm -rf extensions/imageio
rm -rf extensions/opengl
rm -f extensions/Makefile

cd ..

echo Packing the archive...

tar cfz  qt-embedded.tar.gz qt-embedded

