#!/usr/bin/perl

open( I, "/local/bin/p4 opened -a |" ) || die "cannot run p4 opened, stopped";

$d = undef;
$ou = undef;

while( <I> ) {
    if ( /^(\S+)\/([^\/\s]+)\#\d+\s+.*\s(\S+)@(\S+)$/ ) {
	$u = $3 . " (" . $4 . ")\n";
	if ( $ou ne $u ) {
	    $d = undef;
	    $ou = $u;
	}
	if ( $d ne $1 ) {
	    $log{$u} .= "    $1\n";
	    $d = $1;
	}
	$log{$u} .= "        $2\n";
    }
}

foreach ( sort keys %log ) {
    print $_, $log{$_};
}
