#!/bin/sh

#
# function declarations
#

function error
{ 
    echo
    echo "usage:"
    echo
    echo "  $0 -n number"
    echo "      to show the last 'number' changes"
    echo
    echo "  $0 -l label"
    echo "      to show the changes made after the p4 label 'label'"
    echo
    exit -1
}

function separator
{
    echo
    echo
    echo "________________________________________________________________________________________________"
    echo
    echo
}

function changesMaximum
{
    export CHANGES=`p4 changes -i -m "$1" ... | cut -f 2 -d ' ' | sort -g`
}

function changesLabel
{
    TMPFILEFROM=tmp_p4changelist_tmp_from
    TMPFILETO=tmp_p4changelist_tmp_to
    p4 changes -i "...@$1" | sort -g > $TMPFILEFROM
    p4 changes -i "...#head" | sort -g > $TMPFILETO
    export CHANGES=`diff $TMPFILEFROM $TMPFILETO | grep Change | cut -f 3 -d ' ' | sort -g`
    rm $TMPFILEFROM
    rm $TMPFILETO
}

#
# the main code
#

if [ -z $1 ]
then
    error
else
    if [ "x$1" = 'x-n' ] && [ -n "$2" ]
    then
	changesMaximum $2
    elif [ "x$1" = 'x-l' ] && [ -n "$2" ]
    then
	changesLabel $2
    else
	error
    fi
fi

echo "The following changes are considered:"
echo
echo "$CHANGES"

for i in $CHANGES
do
    separator
    p4 describe -du $i
done

separator
