#!/bin/sh
perl -0777 -i -p \
    -e "s/%YEAR%/$(date +%Y)/g;" \
    -e "s/%VERSION%/$1/g;" \
    -e "s/%VERSIONWIN%/$2/g;" \
    -e "s/%SPECIAL-$3([^%]*)%/\$1/g;" \
    -e "s/%SPECIAL-[^%]*%//g;" \
	[A-Z]*
