##############################################################
# Automatically generated by qmake (1.01a) Fri Nov 23 15:46:17 2001
##############################################################

TEMPLATE = app
CONFIG -= moc
DEPENDPATH += /home/mark/p4/qt-3.0/tests/doc/make-images/iconset/

# Input
SOURCES += main.cpp
