######################################################################
# Automatically generated by qmake (2.00a) Tue Mar 1 11:50:47 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += button.h calculator.h
SOURCES += button.cpp calculator.cpp main.cpp
