TEMPLATE       = app
SOURCES        = qsettings.cpp qxml.cpp main.cpp
unix:SOURCES  += qsettings_unix.cpp
win32:SOURCES += qsettings_win.cpp
HEADERS        = qsettings.h qxml.h
SRCMOC         = moc_qsettings.cpp
SRCOCJ         = moc_qsettings.o
TARGET         = settings
CONFIG         += qt warn_on release
CLEAN_FILES     = *.core core variantrc variantrc3
