######################################################################
# Automatically generated by qmake (1.08a) Mon Jun 28 17:01:02 2004
######################################################################

TEMPLATE = app
CONFIG -= moc
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += qt warn_on debug  create_prl link_prl
OBJECTS_DIR=.obj/debug-shared
MOC_DIR=.moc/debug-shared
