#############################################################################
# $Id: //depot/qt/2.1/examples/listviews/GNUmakefile#1 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = listviews

include $(QTDIR)/GNUmakefile.inc
