TEMPLATE    =	lib
CONFIG      =   qt opengl
HEADERS     =	qgl.h
SOURCES     =	qgl.cpp
MOC_DIR     =   .
TARGET      =	qgl
DESTINCDIR  =   ../../../include
DESTDIR	    =   ../../../lib
VERSION     =	0.9
