#############################################################################
# $Id: //depot/qt/main/src/GNUmakefile#2 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = qt
LIBTARGET = 1

include $(QTDIR)/GNUmakefile.inc
