#############################################################################
# $Id: //depot/qt/main/src/GNUmakefile#7 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1999 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = qt
LIBTARGET = 1
include $(QTDIR)/GNUmakefile.inc

qpim:
	$(MAKE) CONFIG=QPIM static-release
