#############################################################################
# $Id: //depot/qt/main/src/GNUmakefile#4 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1999 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = qt
LIBTARGET = 1

include $(QTDIR)/GNUmakefile.inc
