#############################################################################
# $Id: //depot/qt/main/src/Makefile#72 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = qt
LIBTARGET = 1

!INCLUDE $(QTDIR)\Makefile.inc
