#############################################################################
# $Id: //depot/qt/main/src/Makefile.win32-dll#2 $
#
# Win32 Makefile for building the Qt libraries.
#
# Copyright (C) 1998-2000 by Trolltech AS.  All rights reserved.
#
#############################################################################


all: qtdll qtmain

qtdll:
	$(MAKE) -f qtdll.mak

qtmain:
	$(MAKE) -f qtmain.mak

clean:
	$(MAKE) -f qtdll.mak clean
	$(MAKE) -f qtmain.mak clean
