#############################################################################
# $Id: //depot/qt/main/examples/qfileiconview/Makefile#1 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = qfileiconview

!INCLUDE $(QTDIR)\Makefile.inc
