######################################################################
# Automatically generated by qmake (1.04a) Mo 9. Sep 14:14:53 2002
######################################################################
TEMPLATE = app

CONFIG  += console
LIBS    += -lqaxcontainer
QT = core gui

# Input
SOURCES += main.cpp
