/****************************************************************************
** $Id: //depot/qt/main/src/widgets/qpushbutton.h#39 $
**
** Definition of QPushButton class
**
** Created : 940221
**
** Copyright (C) 1992-1998 Troll Tech AS.  All rights reserved.
**
** This file is part of Troll Tech's internal development tree for Qt.
**
** This header text will be replaced by an appropriate text by the
** mkdist script which generates external distributions.
**
** If you are using the Qt Professional Edition or the Qt Free Edition,
** please notify Troll Tech at <info@troll.no> if you see this text.
**
** To Troll Tech developers: This header was generated by the script
** fixcopyright-int. It has the same number of text lines as the free
** and professional editions to avoid line number inconsistency.
**
*****************************************************************************/

#ifndef QPUSHBUTTON_H
#define QPUSHBUTTON_H

#ifndef QT_H
#include "qbutton.h"
#endif // QT_H


class QPushButton : public QButton
{
friend class QDialog;
    Q_OBJECT
public:
    QPushButton( QWidget *parent=0, const char *name=0 );
    QPushButton( const QString &text, QWidget *parent=0, const char* name=0 );

    virtual void	setToggleButton( bool );

    bool	autoDefault()	const	{ return autoDefButton; }
    virtual void	setAutoDefault( bool autoDef );
    bool	isDefault()	const	{ return defButton; }
    virtual void	setDefault( bool def );

    virtual void	setIsMenuButton( bool );
    bool	isMenuButton() const;
    
    QSize	sizeHint() const;

    void	move( int x, int y );
    void	move( const QPoint &p );
    void	resize( int w, int h );
    void	resize( const QSize & );
    virtual void	setGeometry( int x, int y, int w, int h );
    virtual void	setGeometry( const QRect & );

public slots:
    virtual void	setOn( bool );
    void	toggle();

protected:
    void	drawButton( QPainter * );
    void	drawButtonLabel( QPainter * );
    void	focusInEvent( QFocusEvent * );
    void	resizeEvent( QResizeEvent * );

private:
    void	init();

    uint	autoDefButton	: 1;
    uint	defButton	: 1;
    uint	lastDown	: 1;
    uint	lastDef		: 1;
    uint	lastEnabled	: 1;
    uint	hasMenuArrow	: 1;

private:	// Disabled copy constructor and operator=
    QPushButton( const QPushButton & );
    QPushButton &operator=( const QPushButton & );
};


#endif // QPUSHBUTTON_H
