######################################################################
# Automatically generated by qmake (2.00a) ma 2. mai 16:14:33 2005
######################################################################

load(qttest_p4)

# Input
SOURCES += tst_resourceengine.cpp
RESOURCES += testqrc/test.qrc 
