// Generated by src/opengl/util/./glsl_to_include.sh from texture_copy.glsl
"!!ARBfp1.0"
"OPTION NV_fragment_program2;"
"PARAM c[1] = { program.local[0] };"
"TEMP R0;"
"TEMP RC;"
"TEMP HC;"
"OUTPUT oCol = result.color;"
"RCPR R0.y, c[0].y;"
"RCPR R0.x, c[0].x;"
"MULR R0.xy, fragment.position, R0;"
"TEX oCol, R0, texture[0], 2D;"
"END"
; // Generated by src/opengl/util/./glsl_to_include.sh from texture_copy.glsl
