all:
	${QTDIR}/util/qdoc/qdoc2latex/q2l \
	${QTDIR}/util/qdoc/qdoc2latex/books/access-i18n.q2l \
	${QTDIR}/util/qdoc/qdoc2latex/books/added.q2l \
	${QTDIR}/util/qdoc/qdoc2latex/books/comms.q2l \
	${QTDIR}/util/qdoc/qdoc2latex/books/datastructures.q2l \
	${QTDIR}/util/qdoc/qdoc2latex/books/dialogs.q2l \
	${QTDIR}/util/qdoc/qdoc2latex/books/events.q2l \
	${QTDIR}/util/qdoc/qdoc2latex/books/graphics.q2l \
	${QTDIR}/util/qdoc/qdoc2latex/books/plugins.q2l \
	${QTDIR}/util/qdoc/qdoc2latex/books/programming.q2l \
	${QTDIR}/util/qdoc/qdoc2latex/books/qws.q2l sql.q2l \
	${QTDIR}/util/qdoc/qdoc2latex/books/thread.q2l \
	${QTDIR}/util/qdoc/qdoc2latex/books/widgets.q2l \
	${QTDIR}/util/qdoc/qdoc2latex/books/xml.q2l \
	${QTDIR}/qmake/book/qmake-manual.book \
	${QTDIR}/tools/assistant/book/assistant.book \
	${QTDIR}/tools/designer/book/designer-manual.book \
	${QTDIR}/tools/linguist/book/linguist-manual.book
