#############################################################################
# Makefile for building table
# Generated by tmake at 02:59, 1997/07/04
#     Project: table.pro
#    Template: e:\tmake\lib\win32-msvc\app.t
#############################################################################

####### Compiler, tools and options

CC	=	cl
CFLAGS	=	-nologo -W3 -O1
INCPATH	=	-I$(QTDIR)\include
LINK	=	link
LFLAGS	=	/NOLOGO /SUBSYSTEM:windows
LIBS	=	$(QTDIR)\lib\qt.lib user32.lib gdi32.lib comdlg32.lib wsock32.lib
MOC	=	moc

####### Files

HEADERS =	table.h
SOURCES =	main.cpp \
		table.cpp
OBJECTS =	main.obj \
		table.obj
SRCMOC	=	moc_table.cpp
OBJMOC	=	moc_table.obj
TARGET	=	table.exe

####### Implicit rules

.SUFFIXES: .cpp .c

.cpp.obj:
	$(CC) -c $(CFLAGS) $(INCPATH) -Fo$@ $<

.c.obj:
	$(CC) -c $(CFLAGS) $(INCPATH) -Fo$@ $<

####### Build rules

all: $(TARGET) 

$(TARGET): $(OBJECTS) $(OBJMOC)
	$(LINK) $(LFLAGS) /OUT:$(TARGET) @<<
	    $(OBJECTS) $(OBJMOC) $(LIBS)
<<

moc: $(SRCMOC)

clean:
	-del main.obj
	-del table.obj
	-del moc_table.cpp
	-del moc_table.obj
	-del $(TARGET)

####### Compile

main.obj: main.cpp

table.obj: table.cpp

moc_table.obj: moc_table.cpp \
		table.h

moc_table.cpp: table.h
	$(MOC) table.h -o moc_table.cpp

