#############################################################################
# $Id: //depot/qt/2.2/examples/application/GNUmakefile#1 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = application

include $(QTDIR)/GNUmakefile.inc
