#!/bin/sh

cat > "$2/Developer/Examples/Qt/.qmake.cache" << EOF
#nothing anymore...
EOF

for file in `find "$2/Developer/Examples/Qt"`; do
    case $file in
    *.pro)
        cd `dirname $file`
        base=`basename $file`
        #echo "/usr/bin/qmake -spec macx-g++ "$base" [$file]"
        #/usr/bin/qmake -spec macx-g++ "$base"
        echo "/usr/bin/qmake -spec macx-xcode "$base" [$file]" >&2
        /usr/bin/qmake -spec macx-xcode "$base"
    ;;
    esac
     chgrp admin "$file"
     if [ -d "$file" ] || [ -x "$file" ]; then
         chmod 775 "$file"
     elif [ -x "$file" ]; then
         chmod 664 "$file"
     fi
done
