#############################################################################
# $Id: //depot/qt/main/tools/mergetr/GNUmakefile#2 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = mergetr

include $(QTDIR)/GNUmakefile.inc
