#############################################################################
# $Id: //depot/qt/main/tools/mergetr/Makefile#2 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = mergetr

!INCLUDE $(QTDIR)\Makefile.inc
