#############################################################################
# $Id: //depot/qt/main/extensions/imageio/src/Makefile#11 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = qimageio

!INCLUDE $(QTDIR)\Makefile.inc
