TEMPLATE = subdirs

# Directories
SUBDIRS += bic \
           collections \
           compile \
           compilerwarnings \
           exceptionsafety \
           headers \
           macgui \
           moc \
           q3accel \
           q3action \
           q3actiongroup \
           q3buttongroup \
           q3canvas \
           q3cstring \
           q3databrowser \
           q3dateedit \
           q3datetimeedit \
           q3dict \
           q3dns \
           q3dockwindow \
           q3filedialog \
           q3groupbox \
           q3hbox \
           q3header \
           q3iconview \
           q3listview \
           q3listviewitemiterator \
           q3mainwindow \
           q3process \
           q3progressbar \
           q3progressdialog \
           q3ptrlist \
           q3richtext \
           q3semaphore \
           q3socketdevice \
           q3stylesheet \
           q3tabdialog \
           q3table \
           q3textbrowser \
           q3textedit \
           q3textstream \
           q3timeedit \
           q3toolbar \
           q3urloperator \
           q3valuelist \
           q3valuevector \
           qabstractbutton \
           qabstractitemmodel \
           qabstractitemview \
           qabstractprintdialog \
           qabstractscrollarea \
           qabstractslider \
           qabstractsocket \
           qabstractspinbox \
           qabstracttextdocumentlayout \
           qaccessibility \
           qaccessibility_mac \
           qaction \
           qactiongroup \
           qalgorithms \
           qapplication \
           qatomic \
           qatomicpointer \
           qaxcontainer \
           qbitarray \
           qbrush \
           qbuffer \
           qbuttongroup \
           qbytearray \
           qcache \
           qchar \
           qcheckbox \
           qchecklistitem \
           qclipboard \
           qcolor \
           qcombobox \
           qcompleter \
           qcomplextext \
           qcopchannel \
           qcoreapplication \
           qcssparser \
           qdatastream \
           qdatawidgetmapper \
           qdate \
           qdatetime \
           qdatetimeedit \
           qdebug \
           qdeepcopy \
           qdesktopservices \
           qdesktopwidget \
           qdial \
           qdialog \
           qdialogbuttonbox \
           qdir \
           qdirmodel \
           qdockwidget \
           qdom \
           qdoublespinbox \
           qdoublevalidator \
           qdrag \
           qeventloop \
           qfile \
           qfiledialog \
           qfileinfo \
           qfilesystemwatcher \
           qflags \
           qfocusevent \
           qfocusframe \
           qfont \
           qfontdatabase \
           qfontdialog \
           qfontmetrics \
           qftp \
           qgl \
           qglobal \
           qgraphicsitem \
           qgraphicsitemanimation \
           qgraphicsscene \
           qgraphicsview \
           qgridlayout \
           qgroupbox \
           qguivariant \
           qhash \
           qheaderview \
           qhostaddress \
           qhostinfo \
           qhttp \
           qicon \
           qimage \
           qimageiohandler \
           qimagereader \
           qimagewriter \
           qinputdialog \
           qintvalidator \
           qiodevice \
           qitemdelegate \
           qitemeditorfactory \
           qitemmodel \
           qitemselectionmodel \
           qitemview \
           qkeyevent \
           qkeysequence \
           qlabel \
           qlayout \
           qlcdnumber \
           qlibrary \
           qline \
           qlineedit \
           qlistbox \
           qlistview \
           qlistwidget \
           qlocale \
           qmainwindow \
           qmake \
           qmap \
           qmenu \
           qmenubar \
           qmessagebox \
           qmetaobject \
           qmetatype \
           qmouseevent \
           qmouseevent_modal \
           qmovie \
           qmutex \
           qmutexlocker \
           qnativesocketengine \
           qnetworkinterface \
           qnetworkproxy \
           qnumeric \
           qobject \
           qobjectrace \
           qpaintengine \
           qpainter \
           qpainterpath \
           qpen \
           qpicture \
           qpixmap \
           qpixmapcache \
           qpoint \
           qpointarray \
           qpointer \
           qpopupmenu \
           qprinter \
           qprocess \
           qprogressbar \
           qprogressdialog \
           qpushbutton \
           qqueue \
           qreadlocker \
           qreadwritelock \
           qrect \
           qregexp \
           qregexpvalidator \
           qregion \
           qresourceengine \
           qscriptengine \
           qscrollarea \
           qscrollview \
           qsemaphore \
           qserversocket \
           qset \
           qsettings \
           qshortcut \
           qsignalmapper \
           qsignalspy \
           qsize \
           qsizef \
           qslider \
           qsocket \
           qsocketnotifier \
           qsocks5socketengine \
           qsortfilterproxymodel \
           qsound \
           qspinbox \
           qsplitter \
           qsql \
           qsqlbatch \
           qsqlcursor \
           qsqldatabase \
           qsqlerror \
           qsqlfield \
           qsqlquery \
           qsqlquerymodel \
           qsqlrecord \
           qsqlrelationaltablemodel \
           qsqlselectcursor \
           qsqltablemodel \
           qsqlthread \
           qstackedlayout \
           qstackedwidget \
           qstandarditem \
           qstandarditemmodel \
           qstatusbar \
           qstl \
           qstring \
           qstringlist \
           qstringlistmodel \
           qstyle \
           qstyleoption \
           qsvgdevice \
           qsvgrenderer \
           qsyntaxhighlighter \
           qsystemtrayicon \
           qtabbar \
           qtableview \
           qtablewidget \
           qtabwidget \
           qtcpserver \
           qtcpsocket \
           qtemporaryfile \
	   qtessellator \
           qtextblock \
           qtextbrowser \
           qtextcodec \
           qtextcursor \
           qtextdocument \
           qtextdocumentfragment \
           qtextdocumentlayout \
           qtextedit \
           qtextformat \
           qtextlayout \
           qtextlist \
           qtextobject \
           qtextpiecetable \
           qtextstream \
           qtexttable \
           qthread \
           qthreadstorage \
           qtime \
           qtimeline \
           qtimer \
           qtmd5 \
           qtoolbar \
           qtoolbox \
           qtoolbutton \
           qtranslator \
           qtransformedscreen \
           qtreeview \
           qtreewidget \
           qtreewidgetitemiterator \
           qtwidgets \
           qudpsocket \
           qundogroup \
           qundostack \
           quridrag \
           qurl \
           quuid \
           qvariant \
	   qvarlengtharray \
	   qvector \
           qwaitcondition \
           qwidget \
           qwidgetaction \
           qwidgetstack \
           qwineventnotifier \
           qwmatrix \
           qworkspace \
           qwritelocker \
           qwsembedwidget \
           qwsinputmethod \
           qwswindowsystem \
           qx11info \
           qxml \
           qxmlsimplereader \
           selftests \
           symbols \
           qrand 

unix:!embedded:contains(QT_CONFIG, qdbus):SUBDIRS += \
           qdbusabstractadaptor \
           qdbusconnection \
           qdbusinterface \
           qdbusmarshall \
           qdbusmetaobject \
           qdbusmetatype \
           qdbusreply \
           qdbuslocalcalls \
           qdbusxmlparser
