SOURCES	+= main.cpp 
HEADERS	+= creditform.h 
TARGET	= credit
SOURCES += creditform.cpp
FORMS	= creditformbase.ui 
TEMPLATE	=app
CONFIG	+= qt warn_on release
DBFILE	= credit.db
IMAGEFILE	= images.cpp
LANGUAGE	= C++
