#############################################################################
# $Id: //depot/qt/main/tests/mdi/GNUmakefile#1 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Trolltech AS.  All rights reserved.
#
#############################################################################

PROJECT = mdi

include $(QTDIR)/GNUmakefile.inc
