#define Q_EXPORT_TEMPLATES

#include <qcanvas.h>
#include <qasciidict.h>
#include <qcstring.h>
#include <qdict.h>
#include <qintdict.h>
#include <qmemarray.h>
#include <qptrlist.h>
#include <qptrvector.h>
#include <qvaluelist.h>
#include <qvaluevector.h>
#include <qwidget.h>
#include <qeventloop_p.h>
#include <qguardedptr.h>
#include <qobject.h>
#include <qobjectcleanuphandler.h>
#include <qpoint.h>
#include <qrect.h>
#include <qwidget.h>
#include <qhttp.h>
#include <qsqlindex.h>
#include <qtable.h>
#include <qlibrary.h>
#include <qmap.h>
#include <qdockarea.h>
#include <qdockwindow.h>
