#############################################################################
# $Id: //depot/qt/main/tests/listview/GNUmakefile#3 $
#
# Unix Makefile, requires GNU make (gmake).
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = listview

include $(QTDIR)/GNUmakefile.inc
