#############################################################################
# $Id: //depot/qt/main/tests/listview/Makefile#6 $
#
# Win32 Makefile, requires Microsoft nmake.
#
# Copyright (C) 1998 by Troll Tech AS.  All rights reserved.
#
#############################################################################

PROJECT = listview

!INCLUDE $(QTDIR)\Makefile.inc
